-- dev/replay.lua
-- Generated by feather replay init.
--
-- Keep Session Replay integration here instead of scattering DEBUGGER calls
-- through gameplay code. This file is safe to require in production because it
-- no-ops when DEBUGGER is not available.

local M = {}

local STREAM = "game"

local function capture()
  -- Replace this with a compact game checkpoint.
  -- Good candidates:
  --   world = { seed = run.seed, levelId = currentLevel.id }
  --   player = { x = player.x, y = player.y, health = player.health }
  --   flags = saveSystem.captureFlags()
  return {
    world = {
      -- seed = run.seed,
      -- levelId = currentLevel.id,
    },
    player = {
      -- x = player.x,
      -- y = player.y,
    },
  }
end

local function restore(state)
  if not state then
    return
  end

  -- Restore fixed/generated content first, then mutable gameplay state.
  -- Example:
  -- if state.world and state.world.levelId then loadLevel(state.world.levelId) end
  -- if state.world and state.world.seed then generateArenaFromSeed(state.world.seed) end
  -- if state.player then restorePlayer(state.player) end
end

function M.register(debugger)
  debugger = debugger or rawget(_G, "DEBUGGER")
  if not (debugger and debugger.replayRegister) then
    return false
  end

  debugger:replayRegister(STREAM, capture, restore, {
    sampleInterval = 0.1,
  })
  return true
end

function M.start(debugger, opts)
  debugger = debugger or rawget(_G, "DEBUGGER")
  if not (debugger and debugger.startSessionReplay) then
    return nil, "DEBUGGER is not available"
  end

  opts = opts or {}
  opts.initialStates = opts.initialStates or {}
  opts.initialStates[STREAM] = opts.initialStates[STREAM] or capture()
  return debugger:startSessionReplay(opts)
end

function M.stop(debugger)
  debugger = debugger or rawget(_G, "DEBUGGER")
  if not (debugger and debugger.stopSessionReplay) then
    return nil
  end
  return debugger:stopSessionReplay()
end

function M.play(debugger, idOrPath)
  debugger = debugger or rawget(_G, "DEBUGGER")
  if not (debugger and debugger.playSessionReplay) then
    return nil
  end
  return debugger:playSessionReplay(idOrPath)
end

M.capture = capture
M.restore = restore

return M
