site_name: Feather
site_description: Real-time debug & inspect tool for LÖVE (love2d) games.
site_url: https://kyonru.github.io/feather
repo_url: https://github.com/Kyonru/feather
repo_name: Kyonru/feather

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Plugins: plugins.md
  - Recommendations: recommendations.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
