import type { Edge } from '@xyflow/react';
import type { NodeType, ShaderNodeData, ShaderNodeInstance } from '@/types/shader-graph';
import { NODE_DEFS } from './nodeDefs';

type PresetNode = {
  id: string;
  type: NodeType;
  x: number;
  y: number;
  label?: string;
  values?: Record<string, number | number[]>;
  min?: number;
  max?: number;
  step?: number;
};

type PresetEdge = {
  from: string;
  out: string;
  to: string;
  in: string;
};

export type ShaderGraphPreset = {
  id: string;
  name: string;
  description: string;
  shaderName: string;
  nodes: ShaderNodeInstance[];
  edges: Edge[];
};

const PRESET_LABELS: Record<string, string> = {
  amp: 'Amplitude',
  amount: 'Effect Amount',
  'a-color': 'Blue Circle Color',
  'a-shape': 'Blue Circle SDF',
  'a-mask': 'Blue Circle Mask',
  'a-layer': 'Blue Circle Layer',
  'b-color': 'Pink Square Color',
  'b-shape': 'Pink Square SDF',
  'b-mask': 'Pink Square Mask',
  'b-layer': 'Pink Square Layer',
  boolean: 'Subtract Shape',
  cells: 'Voronoi Cell Mask',
  center: 'Shape Center',
  'center-a': 'Main Circle Center',
  'center-b': 'Cutout Circle Center',
  'center-offset': 'Split Center Offset',
  checker: 'Checker Mask',
  chromatic: 'Channel Split',
  corner: 'Corner Radius',
  composite: 'Composite Layers',
  'composite-mode': 'Composite Mode',
  cut: 'Dissolve Cutoff',
  dissolve: 'Dissolve Texture',
  'edge-color': 'Edge Color',
  'energy-color': 'Energy Color',
  'fill-color': 'Fill Color',
  flash: 'Apply Color Mix',
  'flash-color': 'Flash Color',
  freq: 'Frequency',
  'frag-out': 'Texture Output',
  'glow-color': 'Glow Color',
  halftone: 'Apply Halftone',
  'halftone-mode': 'Halftone Mode',
  'halftone-scale': 'Dot Scale',
  intensity: 'Glow Intensity',
  invert: 'Invert Mask',
  mask: 'Alpha Mask Threshold',
  mix: 'Blend Glow',
  offset: 'UV Offset',
  'opacity-node': 'Apply Opacity',
  opacity: 'Opacity Amount',
  out: 'Final Output',
  outline: 'Build Outline',
  'outline-color': 'Outline Color',
  'offset-r': 'Red Dot Angle',
  'offset-g': 'Green Dot Angle',
  'offset-b': 'Blue Dot Angle',
  'pattern-scale': 'Pattern Scale',
  'pattern-widths': 'Stripe Widths',
  'pattern-whirl': 'Whirl Amount',
  'pattern-color': 'Pattern Color',
  pixelate: 'Pixelate UVs',
  pos: 'Vertex Position',
  posterize: 'Reduce Color Bands',
  power: 'Power',
  radius: 'Shape Radius',
  'radius-a': 'Main Circle Radius',
  'radius-b': 'Cutout Circle Radius',
  rect: 'Build Rectangle SDF',
  rim: 'Rim Mask',
  rotate: 'Rotate UVs',
  scale: 'Pattern Scale',
  sdf: 'Build SDF',
  'sdf-a': 'Main Circle SDF',
  'sdf-b': 'Cutout Circle SDF',
  sides: 'Polygon Sides',
  soft: 'Edge Softness',
  speed: 'Animation Speed',
  steps: 'Color Steps',
  strength: 'Effect Strength',
  strip: 'Sample Ring Band',
  tex: 'Source Texture',
  thickness: 'Outline Thickness',
  tiling: 'Tile Count',
  'tiling-offset': 'Tile And Offset UVs',
  time: 'Animated Time',
  'tile-size': 'Tile Size',
  'tile-width': 'Line Width',
  'tile-mode': 'Pattern Mode',
  'scroll-speed': 'Scroll Speed',
  twirl: 'Twirl UVs',
  uv: 'Source UVs',
  'vert-out': 'Final Vertex Position',
  wave: 'Wave Distortion',
  water: 'Water Offset',
  width: 'Rectangle Width',
  truchet: 'Build Truchet Mask',
  'line-color': 'Line Color',
  'lab-complement': 'Perceptual Complement',
  'lab-mix': 'Complement Mix',
};

const PRESET_LABELS_BY_ID: Record<string, string> = {
  height: 'Rectangle Height',
};

const PRESET_TYPE_LABELS: Partial<Record<NodeType, string>> = {
  FragmentOutput: 'Final Output',
  SampleTexture: 'Sample Texture',
  SDFSample: 'Sample SDF Mask',
  TextureColor: 'Source Texture',
  TextureCoords: 'Source UVs',
};

const PRESET_LABELS_BY_KEY: Partial<Record<`${NodeType}:${string}`, string>> = {
  'FloatConstant:opacity': 'Opacity Amount',
  'Opacity2D:opacity': 'Apply Opacity Mask',
};

function presetLabel(id: string, type: NodeType) {
  return PRESET_LABELS_BY_KEY[`${type}:${id}`] ?? PRESET_LABELS[id] ?? PRESET_LABELS_BY_ID[id] ?? PRESET_TYPE_LABELS[type] ?? NODE_DEFS[type].label;
}

function node({ id, type, x, y, label, values, min, max, step }: PresetNode): ShaderNodeInstance {
  return {
    id,
    type: 'shaderNode',
    position: { x, y },
    data: {
      label: label ?? presetLabel(id, type),
      nodeType: type,
      ...(values ? { values } : {}),
      ...(min !== undefined ? { min } : {}),
      ...(max !== undefined ? { max } : {}),
      ...(step !== undefined ? { step } : {}),
    } satisfies ShaderNodeData,
  };
}

function edge({ from, out, to, in: input }: PresetEdge): Edge {
  return {
    id: `${from}:${out}->${to}:${input}`,
    source: from,
    sourceHandle: out,
    target: to,
    targetHandle: input,
  };
}

function preset(
  id: string,
  name: string,
  description: string,
  shaderName: string,
  nodes: PresetNode[],
  edges: PresetEdge[],
): ShaderGraphPreset {
  return {
    id,
    name,
    description,
    shaderName,
    nodes: nodes.map(node),
    edges: edges.map(edge),
  };
}

export const SHADER_GRAPH_PRESETS: ShaderGraphPreset[] = [
  preset(
    'texture-pass',
    'Texture Pass',
    'Default LÖVE texture color multiplied by vertex color.',
    'texture-pass',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'out', type: 'FragmentOutput', x: 300, y: 0 },
    ],
    [{ from: 'tex', out: 'out', to: 'out', in: 'color' }],
  ),
  preset(
    'outline',
    'Outline',
    'Sprite-alpha outline with editable color and screen-space thickness.',
    'outline',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 130 },
      { id: 'thickness', type: 'FloatConstant', x: 0, y: 260, values: { val: 3 } },
      { id: 'outline-color', type: 'Vec4Constant', x: 0, y: 390, values: { val: [1, 1, 1, 1] } },
      { id: 'outline', type: 'Outline2D', x: 310, y: 120 },
      { id: 'out', type: 'FragmentOutput', x: 650, y: 160 },
    ],
    [
      { from: 'tex', out: 'out', to: 'outline', in: 'color' },
      { from: 'uv', out: 'out', to: 'outline', in: 'uv' },
      { from: 'thickness', out: 'out', to: 'outline', in: 'thickness' },
      { from: 'outline-color', out: 'out', to: 'outline', in: 'outlineColor' },
      { from: 'outline', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'wave',
    'Wave',
    'Sine-wave texture distortion useful for water, heat, magic, and flags.',
    'wave',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'time', type: 'Time', x: 0, y: 110 },
      { id: 'amp', type: 'FloatConstant', x: 0, y: 220, values: { val: 0.025 } },
      { id: 'freq', type: 'FloatConstant', x: 0, y: 330, values: { val: 28 } },
      { id: 'speed', type: 'FloatConstant', x: 0, y: 440, values: { val: 1.6 } },
      { id: 'wave', type: 'WaveDistort', x: 300, y: 150 },
      { id: 'sample', type: 'SampleTexture', x: 610, y: 180 },
      { id: 'out', type: 'FragmentOutput', x: 900, y: 180 },
    ],
    [
      { from: 'uv', out: 'out', to: 'wave', in: 'uv' },
      { from: 'time', out: 'out', to: 'wave', in: 'time' },
      { from: 'amp', out: 'out', to: 'wave', in: 'amp' },
      { from: 'freq', out: 'out', to: 'wave', in: 'freq' },
      { from: 'speed', out: 'out', to: 'wave', in: 'speed' },
      { from: 'wave', out: 'out', to: 'sample', in: 'uv' },
      { from: 'sample', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'dissolve',
    'Dissolve',
    'Noise threshold dissolve with a colored burning edge.',
    'dissolve',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 120 },
      { id: 'cut', type: 'FloatConstant', x: 0, y: 240, values: { val: 0.42 } },
      { id: 'soft', type: 'FloatConstant', x: 0, y: 360, values: { val: 0.08 } },
      { id: 'edge-color', type: 'Vec4Constant', x: 0, y: 480, values: { val: [1, 0.45, 0.05, 1] } },
      { id: 'dissolve', type: 'Dissolve2D', x: 320, y: 170 },
      { id: 'out', type: 'FragmentOutput', x: 660, y: 200 },
    ],
    [
      { from: 'tex', out: 'out', to: 'dissolve', in: 'color' },
      { from: 'uv', out: 'out', to: 'dissolve', in: 'uv' },
      { from: 'cut', out: 'out', to: 'dissolve', in: 'threshold' },
      { from: 'soft', out: 'out', to: 'dissolve', in: 'softness' },
      { from: 'edge-color', out: 'out', to: 'dissolve', in: 'edgeColor' },
      { from: 'dissolve', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'hit-flash',
    'Hit Flash',
    'Mixes a sprite toward a bright flash color.',
    'hit-flash',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'flash-color', type: 'Vec4Constant', x: 0, y: 140, values: { val: [1, 1, 1, 1] } },
      { id: 'amount', type: 'FloatConstant', x: 0, y: 280, values: { val: 0.65 } },
      { id: 'flash', type: 'HitFlash', x: 320, y: 95 },
      { id: 'out', type: 'FragmentOutput', x: 650, y: 115 },
    ],
    [
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'flash-color', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'amount', out: 'out', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'alpha-composite',
    'Alpha Composite',
    'Porter-Duff alpha compositing between a blue circle and a pink square.',
    'alpha-composite',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'a-color', type: 'Vec4Constant', x: 0, y: 130, values: { val: [0.28, 0.6, 0.94, 0.62] } },
      { id: 'b-color', type: 'Vec4Constant', x: 0, y: 260, values: { val: [0.85, 0.12, 0.39, 0.62] } },
      { id: 'composite-mode', type: 'FloatConstant', x: 0, y: 390, values: { val: 0 }, min: 0, max: 4, step: 1 },
      { id: 'a-shape', type: 'SDFCircle', x: 340, y: 0, values: { position: [0.43, 0.5], radius: 0.32 } },
      { id: 'b-shape', type: 'SDFRect', x: 340, y: 260, values: { position: [0.58, 0.5], width: 0.52, height: 0.52, corner: 0.03 } },
      { id: 'a-mask', type: 'SDFSample', x: 660, y: 30 },
      { id: 'b-mask', type: 'SDFSample', x: 660, y: 290 },
      { id: 'a-layer', type: 'Opacity2D', x: 940, y: 80 },
      { id: 'b-layer', type: 'Opacity2D', x: 940, y: 300 },
      { id: 'composite', type: 'CompositeAlpha', x: 1230, y: 190 },
      { id: 'out', type: 'FragmentOutput', x: 1530, y: 205 },
    ],
    [
      { from: 'uv', out: 'out', to: 'a-shape', in: 'uv' },
      { from: 'uv', out: 'out', to: 'b-shape', in: 'uv' },
      { from: 'a-shape', out: 'out', to: 'a-mask', in: 'sdf' },
      { from: 'b-shape', out: 'out', to: 'b-mask', in: 'sdf' },
      { from: 'a-color', out: 'out', to: 'a-layer', in: 'color' },
      { from: 'a-mask', out: 'out', to: 'a-layer', in: 'opacity' },
      { from: 'b-color', out: 'out', to: 'b-layer', in: 'color' },
      { from: 'b-mask', out: 'out', to: 'b-layer', in: 'opacity' },
      { from: 'a-layer', out: 'out', to: 'composite', in: 'a' },
      { from: 'b-layer', out: 'out', to: 'composite', in: 'b' },
      { from: 'composite-mode', out: 'out', to: 'composite', in: 'mode' },
      { from: 'composite', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'lab-complementary',
    'Lab Complementary',
    'Mixes a texture toward its perceptual Lab/LCH complementary color.',
    'lab-complementary',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'lab-complement', type: 'LabComplementary', x: 310, y: 0 },
      { id: 'lab-mix', type: 'FloatConstant', x: 0, y: 140, values: { val: 0.45 }, min: 0, max: 1, step: 0.01 },
      { id: 'flash', type: 'HitFlash', x: 650, y: 45, label: 'Mix Complement' },
      { id: 'out', type: 'FragmentOutput', x: 980, y: 65 },
    ],
    [
      { from: 'tex', out: 'out', to: 'lab-complement', in: 'color' },
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'lab-complement', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'lab-mix', out: 'out', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'rim-glow',
    'Rim Glow',
    'Fresnel-like 2D edge glow for particles and soft sprites.',
    'rim-glow',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'power', type: 'FloatConstant', x: 0, y: 120, values: { val: 2.8 } },
      { id: 'intensity', type: 'FloatConstant', x: 0, y: 240, values: { val: 1.2 } },
      { id: 'rim', type: 'Fresnel2D', x: 300, y: 70 },
      { id: 'tex', type: 'TextureColor', x: 300, y: 270 },
      { id: 'glow-color', type: 'Vec4Constant', x: 300, y: 400, values: { val: [0.25, 0.8, 1, 1] } },
      { id: 'mix', type: 'HitFlash', x: 620, y: 185 },
      { id: 'out', type: 'FragmentOutput', x: 940, y: 205 },
    ],
    [
      { from: 'uv', out: 'out', to: 'rim', in: 'uv' },
      { from: 'power', out: 'out', to: 'rim', in: 'power' },
      { from: 'intensity', out: 'out', to: 'rim', in: 'intensity' },
      { from: 'tex', out: 'out', to: 'mix', in: 'color' },
      { from: 'glow-color', out: 'out', to: 'mix', in: 'flashColor' },
      { from: 'rim', out: 'out', to: 'mix', in: 'amount' },
      { from: 'mix', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'pixelate',
    'Pixelate',
    'Crunchy low-resolution sampling for retro sprites or transitions.',
    'pixelate',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'amount', type: 'FloatConstant', x: 0, y: 140, values: { val: 10 } },
      { id: 'pixelate', type: 'Pixelate', x: 300, y: 50 },
      { id: 'sample', type: 'SampleTexture', x: 590, y: 70 },
      { id: 'out', type: 'FragmentOutput', x: 870, y: 70 },
    ],
    [
      { from: 'uv', out: 'out', to: 'pixelate', in: 'uv' },
      { from: 'amount', out: 'out', to: 'pixelate', in: 'amount' },
      { from: 'pixelate', out: 'out', to: 'sample', in: 'uv' },
      { from: 'sample', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'chromatic-aberration',
    'Chromatic Aberration',
    'Splits red and blue channels away from the center.',
    'chromatic-aberration',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'amount', type: 'FloatConstant', x: 0, y: 140, values: { val: 0.006 } },
      { id: 'center-offset', type: 'Vec2Constant', x: 0, y: 280, values: { val: [0, 0] } },
      { id: 'chromatic', type: 'ChromaticAberration', x: 300, y: 95 },
      { id: 'out', type: 'FragmentOutput', x: 660, y: 115 },
    ],
    [
      { from: 'uv', out: 'out', to: 'chromatic', in: 'uv' },
      { from: 'amount', out: 'out', to: 'chromatic', in: 'amount' },
      { from: 'center-offset', out: 'out', to: 'chromatic', in: 'offset' },
      { from: 'chromatic', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'posterize',
    'Posterize',
    'Quantizes color into a small number of bands for toon and retro looks.',
    'posterize',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'steps', type: 'FloatConstant', x: 0, y: 140, values: { val: 4 } },
      { id: 'posterize', type: 'PosterizeColor', x: 310, y: 55 },
      { id: 'out', type: 'FragmentOutput', x: 650, y: 75 },
    ],
    [
      { from: 'tex', out: 'out', to: 'posterize', in: 'color' },
      { from: 'steps', out: 'out', to: 'posterize', in: 'steps' },
      { from: 'posterize', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'halftone-dots',
    'Halftone Dots',
    'A comic-print treatment with posterized color, RGB dot screens, warm paper tint, and vignette.',
    'halftone-dots',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0, label: 'Source Texture' },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 130, label: 'Print UVs' },
      { id: 'print-contrast', type: 'FloatConstant', x: 0, y: 260, label: 'Ink Contrast', values: { val: 1.45 } },
      { id: 'color-steps', type: 'FloatConstant', x: 0, y: 390, label: 'Poster Color Steps', values: { val: 4 }, min: 2, max: 8, step: 1 },
      { id: 'halftone-mode', type: 'FloatConstant', x: 0, y: 520, label: 'Dot Style', values: { val: 0 }, min: 0, max: 2, step: 1 },
      { id: 'halftone-scale', type: 'FloatConstant', x: 0, y: 650, values: { val: 1 }, min: 0.1, max: 16, step: 0.1 },
      { id: 'offset-r', type: 'Vec2Constant', x: 0, y: 780, values: { val: [0.012, 0] } },
      { id: 'offset-g', type: 'Vec2Constant', x: 0, y: 910, values: { val: [0.0095, 0.0065] } },
      { id: 'offset-b', type: 'Vec2Constant', x: 0, y: 1040, values: { val: [0.006, 0.0105] } },
      { id: 'paper-color', type: 'Vec4Constant', x: 0, y: 1170, label: 'Warm Paper Tint', values: { val: [1, 0.88, 0.62, 1] } },
      { id: 'paper-mix', type: 'FloatConstant', x: 0, y: 1300, label: 'Paper Wash', values: { val: 0.16 }, min: 0, max: 1, step: 0.01 },
      { id: 'vignette-strength', type: 'FloatConstant', x: 0, y: 1430, label: 'Print Edge Fade', values: { val: 0.28 }, min: 0, max: 1, step: 0.01 },
      { id: 'vignette-softness', type: 'FloatConstant', x: 0, y: 1560, label: 'Fade Softness', values: { val: 0.42 }, min: 0, max: 1, step: 0.01 },
      { id: 'contrast', type: 'Contrast', x: 340, y: 65, label: 'Punch Ink Contrast' },
      { id: 'posterize', type: 'PosterizeColor', x: 640, y: 105, label: 'Limit Print Colors' },
      { id: 'halftone', type: 'HalftoneColor', x: 950, y: 330, label: 'RGB Dot Screens' },
      { id: 'paper', type: 'HitFlash', x: 1260, y: 465, label: 'Warm Paper Wash' },
      { id: 'vignette', type: 'Vignette', x: 1580, y: 580, label: 'Printed Edge Falloff' },
      { id: 'out', type: 'FragmentOutput', x: 1910, y: 610, label: 'Final Comic Print' },
    ],
    [
      { from: 'tex', out: 'out', to: 'contrast', in: 'color' },
      { from: 'print-contrast', out: 'out', to: 'contrast', in: 'amount' },
      { from: 'contrast', out: 'out', to: 'posterize', in: 'color' },
      { from: 'color-steps', out: 'out', to: 'posterize', in: 'steps' },
      { from: 'posterize', out: 'out', to: 'halftone', in: 'color' },
      { from: 'uv', out: 'out', to: 'halftone', in: 'uv' },
      { from: 'halftone-mode', out: 'out', to: 'halftone', in: 'mode' },
      { from: 'halftone-scale', out: 'out', to: 'halftone', in: 'scale' },
      { from: 'offset-r', out: 'out', to: 'halftone', in: 'offsetR' },
      { from: 'offset-g', out: 'out', to: 'halftone', in: 'offsetG' },
      { from: 'offset-b', out: 'out', to: 'halftone', in: 'offsetB' },
      { from: 'halftone', out: 'out', to: 'paper', in: 'color' },
      { from: 'paper-color', out: 'out', to: 'paper', in: 'flashColor' },
      { from: 'paper-mix', out: 'out', to: 'paper', in: 'amount' },
      { from: 'paper', out: 'out', to: 'vignette', in: 'color' },
      { from: 'uv', out: 'out', to: 'vignette', in: 'uv' },
      { from: 'vignette-strength', out: 'out', to: 'vignette', in: 'strength' },
      { from: 'vignette-softness', out: 'out', to: 'vignette', in: 'softness' },
      { from: 'vignette', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'twirl-portal',
    'Twirl Portal',
    'Twists UVs around the center, good for portals and magical particles.',
    'twirl-portal',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'strength', type: 'FloatConstant', x: 0, y: 140, values: { val: 3.5 } },
      { id: 'twirl', type: 'TwirlUV', x: 310, y: 55 },
      { id: 'sample', type: 'SampleTexture', x: 610, y: 70 },
      { id: 'out', type: 'FragmentOutput', x: 890, y: 70 },
    ],
    [
      { from: 'uv', out: 'out', to: 'twirl', in: 'uv' },
      { from: 'strength', out: 'out', to: 'twirl', in: 'strength' },
      { from: 'twirl', out: 'out', to: 'sample', in: 'uv' },
      { from: 'sample', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'rotating-texture',
    'Rotating Texture',
    'Rotates UVs over time around the center.',
    'rotating-texture',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'time', type: 'Time', x: 0, y: 140 },
      { id: 'rotate', type: 'RotateUV', x: 310, y: 55 },
      { id: 'sample', type: 'SampleTexture', x: 610, y: 70 },
      { id: 'out', type: 'FragmentOutput', x: 890, y: 70 },
    ],
    [
      { from: 'uv', out: 'out', to: 'rotate', in: 'uv' },
      { from: 'time', out: 'out', to: 'rotate', in: 'angle' },
      { from: 'rotate', out: 'out', to: 'sample', in: 'uv' },
      { from: 'sample', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'checker-flash',
    'Checker Flash',
    'Uses a checkerboard mask to flash alternating regions of a sprite.',
    'checker-flash',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 130 },
      { id: 'scale', type: 'FloatConstant', x: 0, y: 260, values: { val: 10 } },
      { id: 'flash-color', type: 'Vec4Constant', x: 0, y: 390, values: { val: [0.2, 0.9, 1, 1] } },
      { id: 'checker', type: 'Checkerboard', x: 310, y: 145 },
      { id: 'flash', type: 'HitFlash', x: 610, y: 120 },
      { id: 'out', type: 'FragmentOutput', x: 930, y: 140 },
    ],
    [
      { from: 'uv', out: 'out', to: 'checker', in: 'uv' },
      { from: 'scale', out: 'out', to: 'checker', in: 'scale' },
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'flash-color', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'checker', out: 'out', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'pattern-whirl',
    'Pattern Whirl',
    'A graphic radial whirl mask mixed into the sprite color.',
    'pattern-whirl',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 130 },
      { id: 'pattern-scale', type: 'FloatConstant', x: 0, y: 260, values: { val: 4 }, min: 0.1, max: 12, step: 0.1 },
      { id: 'pattern-widths', type: 'Vec2Constant', x: 0, y: 390, values: { val: [24, 18] } },
      { id: 'pattern-whirl', type: 'FloatConstant', x: 0, y: 520, values: { val: 95 }, min: -360, max: 360, step: 1 },
      { id: 'pattern-color', type: 'Vec4Constant', x: 0, y: 650, values: { val: [1, 0.25, 0.7, 1] } },
      { id: 'center', type: 'CenteredUV', x: 330, y: 135 },
      { id: 'scale', type: 'ScaleVec2', x: 610, y: 170 },
      { id: 'whirl', type: 'PatternWhirl', x: 900, y: 265 },
      { id: 'flash', type: 'HitFlash', x: 1210, y: 200 },
      { id: 'out', type: 'FragmentOutput', x: 1530, y: 220 },
    ],
    [
      { from: 'uv', out: 'out', to: 'center', in: 'uv' },
      { from: 'center', out: 'out', to: 'scale', in: 'vec' },
      { from: 'pattern-scale', out: 'out', to: 'scale', in: 'scale' },
      { from: 'scale', out: 'out', to: 'whirl', in: 'uv' },
      { from: 'pattern-widths', out: 'out', to: 'whirl', in: 'widths' },
      { from: 'pattern-whirl', out: 'out', to: 'whirl', in: 'whirl' },
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'pattern-color', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'whirl', out: 'out', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'voronoi-energy',
    'Voronoi Energy',
    'Cellular noise mask mixed into the texture for sparks, shields, and magic.',
    'voronoi-energy',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 130 },
      { id: 'scale', type: 'FloatConstant', x: 0, y: 260, values: { val: 16 } },
      { id: 'energy-color', type: 'Vec4Constant', x: 0, y: 390, values: { val: [0.1, 0.75, 1, 1] } },
      { id: 'cells', type: 'VoronoiCells', x: 310, y: 145 },
      { id: 'invert', type: 'OneMinus', x: 590, y: 160 },
      { id: 'flash', type: 'HitFlash', x: 820, y: 120 },
      { id: 'out', type: 'FragmentOutput', x: 1140, y: 140 },
    ],
    [
      { from: 'uv', out: 'out', to: 'cells', in: 'uv' },
      { from: 'scale', out: 'out', to: 'cells', in: 'scale' },
      { from: 'cells', out: 'out', to: 'invert', in: 'val' },
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'energy-color', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'invert', out: 'out', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'truchet-tiles',
    'Truchet Tiles',
    'Classic square Truchet arc tiles with randomized rotation, reflection, and scrolling motion.',
    'truchet-tiles',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 130 },
      { id: 'tile-size', type: 'FloatConstant', x: 0, y: 260, values: { val: 0.16 } },
      { id: 'tile-mode', type: 'FloatConstant', x: 0, y: 390, values: { val: 0 }, min: 0, max: 2, step: 1 },
      { id: 'seed', type: 'FloatConstant', x: 0, y: 520, label: 'Pattern Seed', values: { val: 7 } },
      { id: 'tile-width', type: 'FloatConstant', x: 0, y: 650, values: { val: 0.08 } },
      { id: 'time', type: 'Time', x: 0, y: 780 },
      { id: 'scroll-speed', type: 'Vec2Constant', x: 0, y: 910, values: { val: [0.04, 0.02] } },
      { id: 'line-color', type: 'Vec4Constant', x: 0, y: 1050, values: { val: [0.15, 0.9, 1, 1] } },
      { id: 'truchet', type: 'TruchetTiles', x: 340, y: 340 },
      { id: 'flash', type: 'HitFlash', x: 720, y: 220 },
      { id: 'out', type: 'FragmentOutput', x: 1040, y: 240 },
    ],
    [
      { from: 'uv', out: 'out', to: 'truchet', in: 'position' },
      { from: 'tile-size', out: 'out', to: 'truchet', in: 'size' },
      { from: 'tile-mode', out: 'out', to: 'truchet', in: 'mode' },
      { from: 'seed', out: 'out', to: 'truchet', in: 'seed' },
      { from: 'tile-width', out: 'out', to: 'truchet', in: 'width' },
      { from: 'time', out: 'out', to: 'truchet', in: 'time' },
      { from: 'scroll-speed', out: 'out', to: 'truchet', in: 'scroll' },
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'line-color', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'truchet', out: 'mask', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'tiled-scroll',
    'Tiled Offset',
    'Tiles and offsets UVs before sampling the texture.',
    'tiled-offset',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'tiling', type: 'Vec2Constant', x: 0, y: 140, values: { val: [2, 2] } },
      { id: 'offset', type: 'Vec2Constant', x: 0, y: 280, values: { val: [0.1, 0] } },
      { id: 'tiling-offset', type: 'TilingOffset', x: 310, y: 90 },
      { id: 'sample', type: 'SampleTexture', x: 620, y: 105 },
      { id: 'out', type: 'FragmentOutput', x: 900, y: 105 },
    ],
    [
      { from: 'uv', out: 'out', to: 'tiling-offset', in: 'uv' },
      { from: 'tiling', out: 'out', to: 'tiling-offset', in: 'tiling' },
      { from: 'offset', out: 'out', to: 'tiling-offset', in: 'offset' },
      { from: 'tiling-offset', out: 'out', to: 'sample', in: 'uv' },
      { from: 'sample', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'texture-strength',
    'Texture Strength',
    'Sharpens texture alpha and boosts color intensity for cracks, glows, and impact marks.',
    'texture-strength',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'power', type: 'FloatConstant', x: 0, y: 140, values: { val: 1.8 } },
      { id: 'strength', type: 'FloatConstant', x: 0, y: 280, values: { val: 1.45 } },
      { id: 'texture-strength', type: 'TextureStrength', x: 320, y: 75 },
      { id: 'out', type: 'FragmentOutput', x: 670, y: 95 },
    ],
    [
      { from: 'tex', out: 'out', to: 'texture-strength', in: 'color' },
      { from: 'power', out: 'out', to: 'texture-strength', in: 'power' },
      { from: 'strength', out: 'out', to: 'texture-strength', in: 'strength' },
      { from: 'texture-strength', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'opacity-fade',
    'Opacity Fade',
    'Simple texture alpha control for fade-in and fade-out effects.',
    'opacity-fade',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'opacity', type: 'FloatConstant', x: 0, y: 140, values: { val: 0.45 } },
      { id: 'opacity-node', type: 'Opacity2D', x: 320, y: 55 },
      { id: 'out', type: 'FragmentOutput', x: 650, y: 75 },
    ],
    [
      { from: 'tex', out: 'out', to: 'opacity-node', in: 'color' },
      { from: 'opacity', out: 'out', to: 'opacity-node', in: 'opacity' },
      { from: 'opacity-node', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'vertex-wave',
    'Vertex Wave',
    'Offsets sprite vertices over time while preserving the normal texture color.',
    'vertex-wave',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0 },
      { id: 'frag-out', type: 'FragmentOutput', x: 320, y: 0 },
      { id: 'pos', type: 'VertexPosition', x: 0, y: 180 },
      { id: 'time', type: 'Time', x: 0, y: 300 },
      { id: 'amp', type: 'FloatConstant', x: 0, y: 420, values: { val: 12 } },
      { id: 'freq', type: 'FloatConstant', x: 0, y: 540, values: { val: 0.035 } },
      { id: 'wave', type: 'VertexWave2D', x: 330, y: 300 },
      { id: 'vert-out', type: 'VertexOutput', x: 680, y: 330 },
    ],
    [
      { from: 'tex', out: 'out', to: 'frag-out', in: 'color' },
      { from: 'pos', out: 'out', to: 'wave', in: 'pos' },
      { from: 'time', out: 'out', to: 'wave', in: 'time' },
      { from: 'amp', out: 'out', to: 'wave', in: 'amp' },
      { from: 'freq', out: 'out', to: 'wave', in: 'freq' },
      { from: 'wave', out: 'out', to: 'vert-out', in: 'pos' },
    ],
  ),
  preset(
    'water-shimmer',
    'Water Shimmer',
    'Procedural noise displacement inspired by classic LÖVE water shaders.',
    'water-shimmer',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0, label: 'Source UVs' },
      { id: 'time', type: 'Time', x: 0, y: 120, label: 'Animated Time' },
      { id: 'speed', type: 'FloatConstant', x: 0, y: 240, label: 'Water Scroll Speed', values: { val: 0.18 } },
      { id: 'amp', type: 'FloatConstant', x: 0, y: 360, label: 'Ripple Strength', values: { val: 0.025 } },
      { id: 'scale', type: 'FloatConstant', x: 0, y: 480, label: 'Noise Scale', values: { val: 10 } },
      { id: 'water', type: 'WaterDisplace', x: 330, y: 170, label: 'Animated Water Offset' },
      { id: 'sample', type: 'SampleTexture', x: 650, y: 190, label: 'Sample Shifted Texture' },
      { id: 'out', type: 'FragmentOutput', x: 930, y: 190, label: 'Final Water Shader' },
    ],
    [
      { from: 'uv', out: 'out', to: 'water', in: 'uv' },
      { from: 'time', out: 'out', to: 'water', in: 'time' },
      { from: 'speed', out: 'out', to: 'water', in: 'speed' },
      { from: 'amp', out: 'out', to: 'water', in: 'amp' },
      { from: 'scale', out: 'out', to: 'water', in: 'scale' },
      { from: 'water', out: 'out', to: 'sample', in: 'uv' },
      { from: 'sample', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'sdf-circle-mask',
    'SDF Circle Mask',
    'Clips the texture to a soft anti-aliased circle using a signed distance field.',
    'sdf-circle-mask',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'tex', type: 'TextureColor', x: 0, y: 130 },
      { id: 'center', type: 'Vec2Constant', x: 0, y: 260, values: { val: [0.5, 0.5] } },
      { id: 'radius', type: 'FloatConstant', x: 0, y: 400, values: { val: 0.42 } },
      { id: 'sdf', type: 'SDFCircle', x: 340, y: 200 },
      { id: 'sample', type: 'SDFSample', x: 630, y: 230 },
      { id: 'opacity', type: 'Opacity2D', x: 900, y: 150 },
      { id: 'out', type: 'FragmentOutput', x: 1180, y: 175 },
    ],
    [
      { from: 'uv', out: 'out', to: 'sdf', in: 'uv' },
      { from: 'center', out: 'out', to: 'sdf', in: 'position' },
      { from: 'radius', out: 'out', to: 'sdf', in: 'radius' },
      { from: 'sdf', out: 'out', to: 'sample', in: 'sdf' },
      { from: 'tex', out: 'out', to: 'opacity', in: 'color' },
      { from: 'sample', out: 'out', to: 'opacity', in: 'opacity' },
      { from: 'opacity', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'sdf-rounded-rectangle',
    'SDF Rounded Rectangle',
    'Clips the texture to a rounded rectangle using a signed distance field.',
    'sdf-rounded-rectangle',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'tex', type: 'TextureColor', x: 0, y: 130 },
      { id: 'center', type: 'Vec2Constant', x: 0, y: 260, values: { val: [0.5, 0.5] } },
      { id: 'width', type: 'FloatConstant', x: 0, y: 400, values: { val: 0.58 } },
      { id: 'height', type: 'FloatConstant', x: 0, y: 520, values: { val: 0.36 } },
      { id: 'corner', type: 'FloatConstant', x: 0, y: 640, values: { val: 0.06 } },
      { id: 'rect', type: 'SDFRect', x: 340, y: 280 },
      { id: 'sample', type: 'SDFSample', x: 650, y: 310 },
      { id: 'opacity', type: 'Opacity2D', x: 920, y: 220 },
      { id: 'out', type: 'FragmentOutput', x: 1200, y: 245 },
    ],
    [
      { from: 'uv', out: 'out', to: 'rect', in: 'uv' },
      { from: 'center', out: 'out', to: 'rect', in: 'position' },
      { from: 'width', out: 'out', to: 'rect', in: 'width' },
      { from: 'height', out: 'out', to: 'rect', in: 'height' },
      { from: 'corner', out: 'out', to: 'rect', in: 'corner' },
      { from: 'rect', out: 'out', to: 'sample', in: 'sdf' },
      { from: 'tex', out: 'out', to: 'opacity', in: 'color' },
      { from: 'sample', out: 'out', to: 'opacity', in: 'opacity' },
      { from: 'opacity', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'sdf-ring-glow',
    'SDF Ring Glow',
    'Samples the strip outline of a circle SDF to overlay a glowing ring on the texture.',
    'sdf-ring-glow',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'tex', type: 'TextureColor', x: 0, y: 130 },
      { id: 'center', type: 'Vec2Constant', x: 0, y: 260, values: { val: [0.5, 0.5] } },
      { id: 'radius', type: 'FloatConstant', x: 0, y: 400, values: { val: 0.38 } },
      { id: 'ring-min', type: 'FloatConstant', x: 0, y: 520, values: { val: -0.04 } },
      { id: 'ring-max', type: 'FloatConstant', x: 0, y: 640, values: { val: 0.04 } },
      { id: 'glow-color', type: 'Vec4Constant', x: 0, y: 760, values: { val: [0.2, 0.9, 1, 1] } },
      { id: 'sdf', type: 'SDFCircle', x: 340, y: 300 },
      { id: 'strip', type: 'SDFSampleStrip', x: 640, y: 330 },
      { id: 'flash', type: 'HitFlash', x: 930, y: 230 },
      { id: 'out', type: 'FragmentOutput', x: 1210, y: 255 },
    ],
    [
      { from: 'uv', out: 'out', to: 'sdf', in: 'uv' },
      { from: 'center', out: 'out', to: 'sdf', in: 'position' },
      { from: 'radius', out: 'out', to: 'sdf', in: 'radius' },
      { from: 'sdf', out: 'out', to: 'strip', in: 'sdf' },
      { from: 'ring-min', out: 'out', to: 'strip', in: 'offsetMin' },
      { from: 'ring-max', out: 'out', to: 'strip', in: 'offsetMax' },
      { from: 'tex', out: 'out', to: 'flash', in: 'color' },
      { from: 'glow-color', out: 'out', to: 'flash', in: 'flashColor' },
      { from: 'strip', out: 'out', to: 'flash', in: 'amount' },
      { from: 'flash', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'sdf-hex-badge',
    'SDF Hex Badge',
    'Clips the texture to a visibly smaller hexagonal mask using SDFPolygon.',
    'sdf-hex-badge',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'tex', type: 'TextureColor', x: 0, y: 130 },
      { id: 'center', type: 'Vec2Constant', x: 0, y: 260, values: { val: [0.5, 0.5] } },
      { id: 'radius', type: 'FloatConstant', x: 0, y: 400, values: { val: 0.28 } },
      { id: 'sides', type: 'FloatConstant', x: 0, y: 520, values: { val: 6 } },
      { id: 'corner', type: 'FloatConstant', x: 0, y: 640, values: { val: 0 } },
      { id: 'sdf', type: 'SDFPolygon', x: 340, y: 290 },
      { id: 'sample', type: 'SDFSample', x: 650, y: 320 },
      { id: 'opacity', type: 'Opacity2D', x: 920, y: 230 },
      { id: 'out', type: 'FragmentOutput', x: 1200, y: 255 },
    ],
    [
      { from: 'uv', out: 'out', to: 'sdf', in: 'uv' },
      { from: 'center', out: 'out', to: 'sdf', in: 'position' },
      { from: 'radius', out: 'out', to: 'sdf', in: 'radius' },
      { from: 'sides', out: 'out', to: 'sdf', in: 'sides' },
      { from: 'corner', out: 'out', to: 'sdf', in: 'corner' },
      { from: 'sdf', out: 'out', to: 'sample', in: 'sdf' },
      { from: 'tex', out: 'out', to: 'opacity', in: 'color' },
      { from: 'sample', out: 'out', to: 'opacity', in: 'opacity' },
      { from: 'opacity', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'sdf-crescent',
    'SDF Crescent',
    'Subtracts one circle SDF from another using SDFBoolean Diff to produce a crescent shape.',
    'sdf-crescent',
    [
      { id: 'uv', type: 'TextureCoords', x: 0, y: 0 },
      { id: 'center-a', type: 'Vec2Constant', x: 0, y: 130, values: { val: [0.45, 0.5] } },
      { id: 'center-b', type: 'Vec2Constant', x: 0, y: 270, values: { val: [0.6, 0.5] } },
      { id: 'radius-a', type: 'FloatConstant', x: 0, y: 400, values: { val: 0.38 } },
      { id: 'radius-b', type: 'FloatConstant', x: 0, y: 520, values: { val: 0.3 } },
      { id: 'fill-color', type: 'Vec4Constant', x: 0, y: 640, values: { val: [0.9, 0.8, 0.2, 1] } },
      { id: 'sdf-a', type: 'SDFCircle', x: 340, y: 90 },
      { id: 'sdf-b', type: 'SDFCircle', x: 340, y: 340 },
      { id: 'boolean', type: 'SDFBoolean', x: 660, y: 195 },
      { id: 'sample', type: 'SDFSample', x: 950, y: 225 },
      { id: 'opacity', type: 'Opacity2D', x: 1220, y: 145 },
      { id: 'out', type: 'FragmentOutput', x: 1500, y: 170 },
    ],
    [
      { from: 'uv', out: 'out', to: 'sdf-a', in: 'uv' },
      { from: 'center-a', out: 'out', to: 'sdf-a', in: 'position' },
      { from: 'radius-a', out: 'out', to: 'sdf-a', in: 'radius' },
      { from: 'uv', out: 'out', to: 'sdf-b', in: 'uv' },
      { from: 'center-b', out: 'out', to: 'sdf-b', in: 'position' },
      { from: 'radius-b', out: 'out', to: 'sdf-b', in: 'radius' },
      { from: 'sdf-a', out: 'out', to: 'boolean', in: 'a' },
      { from: 'sdf-b', out: 'out', to: 'boolean', in: 'b' },
      { from: 'boolean', out: 'diff', to: 'sample', in: 'sdf' },
      { from: 'fill-color', out: 'out', to: 'opacity', in: 'color' },
      { from: 'sample', out: 'out', to: 'opacity', in: 'opacity' },
      { from: 'opacity', out: 'out', to: 'out', in: 'color' },
    ],
  ),
  preset(
    'masked-water-shimmer',
    'Masked Water Shimmer',
    'Displaces only opaque texture regions, keeping transparent/shoreline edges stable.',
    'masked-water-shimmer',
    [
      { id: 'tex', type: 'TextureColor', x: 0, y: 0, label: 'Original Texture' },
      { id: 'uv', type: 'TextureCoords', x: 0, y: 120, label: 'Source UVs' },
      { id: 'time', type: 'Time', x: 0, y: 240, label: 'Animated Time' },
      { id: 'speed', type: 'FloatConstant', x: 0, y: 360, label: 'Water Scroll Speed', values: { val: 0.18 } },
      { id: 'amp', type: 'FloatConstant', x: 0, y: 480, label: 'Ripple Strength', values: { val: 0.02 } },
      { id: 'scale', type: 'FloatConstant', x: 0, y: 600, label: 'Noise Scale', values: { val: 12 } },
      { id: 'mask', type: 'FloatConstant', x: 0, y: 720, label: 'Alpha Mask Threshold', values: { val: 0.5 } },
      { id: 'water', type: 'MaskedWaterDisplace', x: 350, y: 270, label: 'Masked Water Offset' },
      { id: 'out', type: 'FragmentOutput', x: 730, y: 315, label: 'Final Masked Water' },
    ],
    [
      { from: 'tex', out: 'out', to: 'water', in: 'color' },
      { from: 'uv', out: 'out', to: 'water', in: 'uv' },
      { from: 'time', out: 'out', to: 'water', in: 'time' },
      { from: 'speed', out: 'out', to: 'water', in: 'speed' },
      { from: 'amp', out: 'out', to: 'water', in: 'amp' },
      { from: 'scale', out: 'out', to: 'water', in: 'scale' },
      { from: 'mask', out: 'out', to: 'water', in: 'maskThreshold' },
      { from: 'water', out: 'out', to: 'out', in: 'color' },
    ],
  ),
];
