import { readFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

export interface FeatherConfig {
  sessionName?: string;
  include?: string[];
  exclude?: string[];
  pluginOptions?: Record<string, Record<string, unknown>>;
  host?: string;
  port?: number;
  [key: string]: unknown;
}

// Minimal Lua table parser for simple `return { key = value, ... }` configs.
// Handles strings, numbers, booleans, and flat string arrays.
function parseLuaTable(src: string): Record<string, unknown> {
  // Strip the outer `return { ... }` wrapper
  const match = src.match(/return\s*\{([\s\S]*)\}/);
  if (!match) return {};

  const body = match[1];
  const result: Record<string, unknown> = {};

  // key = "string"
  for (const m of body.matchAll(/(\w+)\s*=\s*"([^"]*)"/g)) {
    result[m[1]] = m[2];
  }
  // key = 'string'
  for (const m of body.matchAll(/(\w+)\s*=\s*'([^']*)'/g)) {
    result[m[1]] = m[2];
  }
  // key = number
  for (const m of body.matchAll(/(\w+)\s*=\s*(-?\d+(?:\.\d+)?)\b/g)) {
    result[m[1]] = Number(m[2]);
  }
  // key = true/false
  for (const m of body.matchAll(/(\w+)\s*=\s*(true|false)\b/g)) {
    result[m[1]] = m[2] === "true";
  }
  // key = { "a", "b", ... }  (string array)
  for (const m of body.matchAll(/(\w+)\s*=\s*\{([^}]*)\}/g)) {
    const items = [...m[2].matchAll(/"([^"]*)"/g)].map((i) => i[1]);
    if (items.length > 0) result[m[1]] = items;
  }

  return result;
}

export function loadConfig(gamePath: string, override?: string): FeatherConfig | null {
  const candidates = override
    ? [resolve(override)]
    : [
        join(gamePath, "feather.config.lua"),
        join(gamePath, ".featherrc.lua"),
      ];

  for (const path of candidates) {
    if (!existsSync(path)) continue;
    try {
      const src = readFileSync(path, "utf8");
      return parseLuaTable(src) as FeatherConfig;
    } catch (err) {
      throw new Error(`Failed to parse ${path}: ${(err as Error).message}`);
    }
  }

  return null;
}

const isIdentifier = (key: string) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key);

export function luaKey(key: string): string {
  return isIdentifier(key) ? key : `[${JSON.stringify(key)}]`;
}

export function luaValue(value: unknown, indent = 2): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `{ ${value.map((item) => luaValue(item, indent)).join(", ")} }`;

  if (value && typeof value === "object") {
    if (Object.keys(value as Record<string, unknown>).length === 0) return "{}";
    const pad = " ".repeat(indent);
    const childPad = " ".repeat(indent + 2);
    const rows = Object.entries(value as Record<string, unknown>).map(
      ([key, item]) => `${childPad}${luaKey(key)} = ${luaValue(item, indent + 2)},`,
    );
    return `{\n${rows.join("\n")}\n${pad}}`;
  }

  return "nil";
}

type ConfigTemplateContext = {
  mode?: string;
  installDir?: string;
  source?: string;
  manualEntrypoint?: string;
};

function managedHeader(context: ConfigTemplateContext = {}): string {
  const installDir = context.installDir ?? "feather";
  const mode = context.mode ?? "unknown";
  const source = context.source ?? "unknown";
  const manualEntrypoint = context.manualEntrypoint ?? "(none)";

  return `-- feather.config.lua
-- Generated by feather init.
-- See https://kyonru.github.io/feather/configuration/
--
-- FEATHER-MANAGED-BEGIN
-- Keep this metadata block intact. A future \`feather remove\` command can use
-- it, plus the FEATHER-INIT markers in main.lua, to strip Feather from builds
-- before shipping production packages.
--
-- mode: ${mode}
-- source: ${source}
-- installDir: ${installDir}
-- coreDir: ${installDir}
-- pluginsDir: ${installDir}/plugins
-- configFile: feather.config.lua
-- manualEntrypoint: ${manualEntrypoint}
--
-- Main.lua markers inserted by init:
--   FEATHER-INIT-BEGIN require
--   FEATHER-INIT-END require
--   FEATHER-INIT update
--
-- The generated require block is guarded by USE_DEBUGGER. Set USE_DEBUGGER=1
-- when running local/dev builds that should connect to Feather. Leave it unset,
-- 0, or false to skip loading Feather.
--
-- Examples:
--   macOS/Linux shell: USE_DEBUGGER=1 love .
--   Windows PowerShell: $env:USE_DEBUGGER = "1"; love .
--   Windows cmd.exe: set USE_DEBUGGER=1 && love .
--
-- Managed files/directories usually safe to remove for production:
--   ${installDir}/
--   feather.config.lua
--   ${manualEntrypoint}
-- FEATHER-MANAGED-END
--
-- Notes:
-- - This file is Lua. Comments start with --.
-- - Values below are read by feather.auto and the CLI shim.
-- - Manual mode also copies the same values into feather.debugger.lua.
-- - Unknown keys are ignored by Feather, but keep custom data commented unless
--   you intentionally want to pass it to the runtime.
`;
}

function optionReference(): string {
  return `
  -- Security: set ONE of the two options below. Feather errors at startup if neither is set.
  --
  -- Option A (recommended): bind to your specific Feather desktop instance.
  --   Copy from Feather desktop app → Settings → Security → Desktop App ID.
  -- appId = "feather-app-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  --
  -- Option B: explicitly allow any desktop to send commands.
  --   Set this to acknowledge that any Feather desktop on the network can control this game.
  -- __DANGEROUS_INSECURE_CONNECTION__ = true,

  -- Common connection options:
  -- host = "127.0.0.1",
  -- port = 4004,
  -- mode = "socket", -- "socket" for live desktop, "disk" for log files only

  -- Runtime behavior:
  -- debug = true,
  -- wrapPrint = true,
  -- defaultObservers = true,
  -- autoRegisterErrorHandler = true,
  -- writeToDisk = true,
  -- outputDir = "logs",

  -- Feature toggles:
  -- debugger = false,
  --
  -- Hot reload safety:
  --   Hot reload lets the Feather app send Lua source into the running game.
  --   It only works when the opt-in "hot-reload" plugin is installed and
  --   included. Do not include that plugin in production builds.
  --   Treat it as development-only remote code execution. Keep it disabled
  --   unless you are actively using it, keep allow as narrow as possible, and
  --   remove/disable it before shipping builds.
  -- debugger = {
  --   enabled = false,
  --   hotReload = {
  --     enabled = false,
  --     allow = { "game.player" }, -- Prefer exact modules over broad "game.*".
  --     deny = { "main", "conf", "feather.*" },
  --     persistToDisk = false,
  --     clearOnBoot = false,
  --     requireLocalNetwork = true,
  --   },
  -- },
  -- assetPreview = true,
  -- captureScreenshot = false,

  -- Performance / transport:
  -- sampleRate = 1,
  -- updateInterval = 0.1,
  -- maxTempLogs = 200,
  -- retryInterval = 5,
  -- connectTimeout = 2,
  -- errorWait = 3,
  -- binaryTextThreshold = 4096,

  -- Plugin controls:
  -- include = { "console" },
  -- include = { "hot-reload" }, -- development-only remote code execution
  -- exclude = { "hump.signal", "lua-state-machine" },
  -- capabilities = "all",

  -- Per-plugin option overrides:
  -- pluginOptions = {
  --   screenshots = { fps = 60 },
  --   ["memory-snapshot"] = { autoInterval = 5 },
  -- },
`;
}

function renderConfig(config: Record<string, unknown>, context?: ConfigTemplateContext): string {
  const rows = Object.entries(config).map(([key, value]) => `  ${luaKey(key)} = ${luaValue(value, 2)},`);
  return `${managedHeader(context)}
return {
${rows.join("\n")}
${optionReference()}
}
`;
}

export function configTemplate(config?: Record<string, unknown>, context?: ConfigTemplateContext): string {
  if (config && Object.keys(config).length > 0) {
    return renderConfig(config, context);
  }

  return `${managedHeader(context)}
return {
  sessionName = "My Game",
${optionReference()}
}
`;
}
