import { createSyntaxHighlighterStyle, type AppTheme, type GitHubThemeId, type ThemeSeed } from './types';

type GitHubSeedInput = {
  label: string;
  mode: 'light' | 'dark';
  swatches: string[];
  background: string;
  foreground: string;
  card: string;
  mutedForeground: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  accent: string;
  destructive: string;
  border: string;
  input: string;
  ring: string;
  success: string;
  warning: string;
  purple: string;
  syntax: ThemeSeed['syntax'];
};

function createGitHubSeed(theme: GitHubSeedInput): ThemeSeed {
  return {
    label: theme.label,
    mode: theme.mode,
    swatches: theme.swatches,
    variables: {
      background: theme.background,
      foreground: theme.foreground,
      card: theme.card,
      'card-foreground': theme.foreground,
      popover: theme.card,
      'popover-foreground': theme.foreground,
      primary: theme.primary,
      'primary-foreground': theme.primaryForeground,
      secondary: theme.secondary,
      'secondary-foreground': theme.foreground,
      muted: theme.secondary,
      'muted-foreground': theme.mutedForeground,
      accent: theme.accent,
      'accent-foreground': theme.primary,
      destructive: theme.destructive,
      border: theme.border,
      input: theme.input,
      ring: theme.ring,
      'chart-1': theme.primary,
      'chart-2': theme.success,
      'chart-3': theme.warning,
      'chart-4': theme.purple,
      'chart-5': theme.destructive,
      sidebar: theme.card,
      'sidebar-foreground': theme.mutedForeground,
      'sidebar-primary': theme.primary,
      'sidebar-primary-foreground': theme.primaryForeground,
      'sidebar-accent': theme.secondary,
      'sidebar-accent-foreground': theme.foreground,
      'sidebar-border': theme.border,
      'sidebar-ring': theme.ring,
      'plugin-accent': theme.purple,
      'plugin-active': theme.accent,
      'plugin-active-foreground': theme.foreground,
      'plugin-active-icon': theme.primary,
      'plugin-active-border': theme.ring,
    },
    syntax: theme.syntax,
  };
}

const githubThemeSeeds = {
  'github-light-default': createGitHubSeed({
    label: 'GitHub Light Default',
    mode: 'light',
    swatches: ['#ffffff', '#0969da', '#1f883d', '#8250df'],
    background: '#ffffff',
    foreground: '#1f2328',
    card: '#f6f8fa',
    mutedForeground: '#656d76',
    primary: '#0969da',
    primaryForeground: '#ffffff',
    secondary: '#eaeef2',
    accent: '#ddf4ff',
    destructive: '#cf222e',
    border: '#d0d7de',
    input: '#ffffff',
    ring: '#218bff',
    success: '#1f883d',
    warning: '#9a6700',
    purple: '#8250df',
    syntax: {
      comment: '#6e7781',
      text: '#1f2328',
      keyword: '#cf222e',
      variable: '#953800',
      annotation: '#8250df',
      constant: '#0550ae',
      tag: '#116329',
      string: '#0a3069',
      interpolated: '#0550ae',
      number: '#0550ae',
      function: '#8250df',
      support: '#0550ae',
      misc: '#57606a',
      invalid: '#b31d28',
    },
  }),
  'github-light-high-contrast': createGitHubSeed({
    label: 'GitHub Light High Contrast',
    mode: 'light',
    swatches: ['#ffffff', '#0349b4', '#055d20', '#622cbc'],
    background: '#ffffff',
    foreground: '#0e1116',
    card: '#e7ecf0',
    mutedForeground: '#66707b',
    primary: '#0349b4',
    primaryForeground: '#ffffff',
    secondary: '#e7ecf0',
    accent: '#dff7ff',
    destructive: '#a0111f',
    border: '#20252c',
    input: '#ffffff',
    ring: '#368cf9',
    success: '#055d20',
    warning: '#744500',
    purple: '#622cbc',
    syntax: {
      comment: '#66707b',
      text: '#0e1116',
      keyword: '#a0111f',
      variable: '#702c00',
      annotation: '#622cbc',
      constant: '#023b95',
      tag: '#024c1a',
      string: '#032563',
      interpolated: '#023b95',
      number: '#023b95',
      function: '#622cbc',
      support: '#023b95',
      misc: '#4b535d',
      invalid: '#6e011a',
    },
  }),
  'github-light-colorblind': createGitHubSeed({
    label: 'GitHub Light Colorblind',
    mode: 'light',
    swatches: ['#ffffff', '#0969da', '#218bff', '#8250df'],
    background: '#ffffff',
    foreground: '#24292f',
    card: '#f6f8fa',
    mutedForeground: '#57606a',
    primary: '#0969da',
    primaryForeground: '#ffffff',
    secondary: '#eaeef2',
    accent: '#ddf4ff',
    destructive: '#b35900',
    border: '#d0d7de',
    input: '#ffffff',
    ring: '#218bff',
    success: '#0969da',
    warning: '#9a6700',
    purple: '#8250df',
    syntax: {
      comment: '#6e7781',
      text: '#24292f',
      keyword: '#b35900',
      variable: '#8a4600',
      annotation: '#8250df',
      constant: '#0550ae',
      tag: '#0550ae',
      string: '#0a3069',
      interpolated: '#0550ae',
      number: '#0550ae',
      function: '#8250df',
      support: '#0550ae',
      misc: '#57606a',
      invalid: '#6f3800',
    },
  }),
  'github-dark-default': createGitHubSeed({
    label: 'GitHub Dark Default',
    mode: 'dark',
    swatches: ['#0d1117', '#2f81f7', '#3fb950', '#a371f7'],
    background: '#0d1117',
    foreground: '#e6edf3',
    card: '#161b22',
    mutedForeground: '#7d8590',
    primary: '#2f81f7',
    primaryForeground: '#ffffff',
    secondary: '#21262d',
    accent: '#0d419d',
    destructive: '#f85149',
    border: '#30363d',
    input: '#161b22',
    ring: '#58a6ff',
    success: '#3fb950',
    warning: '#d29922',
    purple: '#a371f7',
    syntax: {
      comment: '#8b949e',
      text: '#e6edf3',
      keyword: '#ff7b72',
      variable: '#ffa657',
      annotation: '#d2a8ff',
      constant: '#79c0ff',
      tag: '#7ee787',
      string: '#a5d6ff',
      interpolated: '#79c0ff',
      number: '#79c0ff',
      function: '#d2a8ff',
      support: '#79c0ff',
      misc: '#8b949e',
      invalid: '#f85149',
    },
  }),
  'github-dark-high-contrast': createGitHubSeed({
    label: 'GitHub Dark High Contrast',
    mode: 'dark',
    swatches: ['#0a0c10', '#409eff', '#26cd4d', '#b780ff'],
    background: '#0a0c10',
    foreground: '#f0f3f6',
    card: '#272b33',
    mutedForeground: '#f0f3f6',
    primary: '#71b7ff',
    primaryForeground: '#0a0c10',
    secondary: '#272b33',
    accent: '#1e60d5',
    destructive: '#ff6a69',
    border: '#7a828e',
    input: '#272b33',
    ring: '#409eff',
    success: '#26cd4d',
    warning: '#f0b72f',
    purple: '#b780ff',
    syntax: {
      comment: '#bdc4cc',
      text: '#f0f3f6',
      keyword: '#ff9492',
      variable: '#ffb757',
      annotation: '#dbb7ff',
      constant: '#91cbff',
      tag: '#72f088',
      string: '#addcff',
      interpolated: '#91cbff',
      number: '#91cbff',
      function: '#dbb7ff',
      support: '#91cbff',
      misc: '#bdc4cc',
      invalid: '#ff6a69',
    },
  }),
  'github-dark-colorblind': createGitHubSeed({
    label: 'GitHub Dark Colorblind',
    mode: 'dark',
    swatches: ['#0d1117', '#58a6ff', '#d47616', '#a371f7'],
    background: '#0d1117',
    foreground: '#c9d1d9',
    card: '#161b22',
    mutedForeground: '#8b949e',
    primary: '#58a6ff',
    primaryForeground: '#ffffff',
    secondary: '#21262d',
    accent: '#0d419d',
    destructive: '#d47616',
    border: '#30363d',
    input: '#161b22',
    ring: '#58a6ff',
    success: '#58a6ff',
    warning: '#d29922',
    purple: '#a371f7',
    syntax: {
      comment: '#8b949e',
      text: '#c9d1d9',
      keyword: '#ec8e2c',
      variable: '#fdac54',
      annotation: '#d2a8ff',
      constant: '#79c0ff',
      tag: '#a5d6ff',
      string: '#a5d6ff',
      interpolated: '#79c0ff',
      number: '#79c0ff',
      function: '#d2a8ff',
      support: '#79c0ff',
      misc: '#8b949e',
      invalid: '#d47616',
    },
  }),
  'github-dark-dimmed': createGitHubSeed({
    label: 'GitHub Dark Dimmed',
    mode: 'dark',
    swatches: ['#22272e', '#539bf5', '#57ab5a', '#986ee2'],
    background: '#22272e',
    foreground: '#adbac7',
    card: '#2d333b',
    mutedForeground: '#768390',
    primary: '#539bf5',
    primaryForeground: '#22272e',
    secondary: '#373e47',
    accent: '#143d79',
    destructive: '#e5534b',
    border: '#444c56',
    input: '#2d333b',
    ring: '#6cb6ff',
    success: '#57ab5a',
    warning: '#c69026',
    purple: '#986ee2',
    syntax: {
      comment: '#768390',
      text: '#adbac7',
      keyword: '#f47067',
      variable: '#f69d50',
      annotation: '#dcbdfb',
      constant: '#6cb6ff',
      tag: '#8ddb8c',
      string: '#96d0ff',
      interpolated: '#6cb6ff',
      number: '#6cb6ff',
      function: '#dcbdfb',
      support: '#6cb6ff',
      misc: '#768390',
      invalid: '#e5534b',
    },
  }),
  'github-light': createGitHubSeed({
    label: 'GitHub Light',
    mode: 'light',
    swatches: ['#ffffff', '#0366d6', '#28a745', '#6f42c1'],
    background: '#ffffff',
    foreground: '#24292e',
    card: '#f6f8fa',
    mutedForeground: '#586069',
    primary: '#0366d6',
    primaryForeground: '#ffffff',
    secondary: '#e1e4e8',
    accent: '#dbedff',
    destructive: '#cb2431',
    border: '#e1e4e8',
    input: '#fafbfc',
    ring: '#2188ff',
    success: '#28a745',
    warning: '#dbab09',
    purple: '#6f42c1',
    syntax: {
      comment: '#6a737d',
      text: '#24292e',
      keyword: '#d73a49',
      variable: '#e36209',
      annotation: '#6f42c1',
      constant: '#005cc5',
      tag: '#22863a',
      string: '#032f62',
      interpolated: '#005cc5',
      number: '#005cc5',
      function: '#6f42c1',
      support: '#005cc5',
      misc: '#586069',
      invalid: '#b31d28',
    },
  }),
} satisfies Record<GitHubThemeId, ThemeSeed>;

export const githubThemes = Object.fromEntries(
  Object.entries(githubThemeSeeds).map(([id, theme]) => [
    id,
    {
      id,
      label: theme.label,
      family: 'GitHub',
      mode: theme.mode,
      swatches: theme.swatches,
      variables: theme.variables,
      syntax: createSyntaxHighlighterStyle(theme),
    },
  ]),
) as Record<GitHubThemeId, AppTheme>;
