import { createSyntaxHighlighterStyle, type AppTheme, type RainglowThemeId, type ThemeSeed } from './types';

const rainglowThemeSeeds = {
  'rainglow-absent-light': {
    label: 'Absent Light (Rainglow)',
    mode: 'light',
    swatches: ['#ffffff', '#228a96', '#6ba77f', '#465360'],
    variables: {
      background: '#ffffff',
      foreground: '#465360',
      card: '#f5f5f5',
      'card-foreground': '#465360',
      popover: '#f2f2f2',
      'popover-foreground': '#465360',
      primary: '#228a96',
      'primary-foreground': '#ffffff',
      secondary: '#e6e6e6',
      'secondary-foreground': '#465360',
      muted: '#f2f2f2',
      'muted-foreground': '#8293a4',
      accent: '#d9eeee',
      'accent-foreground': '#228a96',
      destructive: '#a30e29',
      border: '#e0e0e0',
      input: '#ffffff',
      ring: '#228a96',
      'chart-1': '#228a96',
      'chart-2': '#6ba77f',
      'chart-3': '#f7b83d',
      'chart-4': '#9d37fc',
      'chart-5': '#e61f44',
      sidebar: '#f2f2f2',
      'sidebar-foreground': '#465360',
      'sidebar-primary': '#228a96',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#e6e6e6',
      'sidebar-accent-foreground': '#228a96',
      'sidebar-border': '#e0e0e0',
      'sidebar-ring': '#228a96',
      'plugin-accent': '#6ba77f',
      'plugin-active': '#d9eeee',
      'plugin-active-foreground': '#465360',
      'plugin-active-icon': '#228a96',
      'plugin-active-border': '#6ba77f',
    },
    syntax: {
      comment: '#aeb9c4',
      text: '#465360',
      keyword: '#228a96',
      variable: '#353f49',
      annotation: '#6ba77f',
      constant: '#6ba77f',
      tag: '#228a96',
      string: '#478e5f',
      interpolated: '#478e5f',
      number: '#61bcc6',
      function: '#465360',
      support: '#6ba77f',
      misc: '#8293a4',
      invalid: '#cf433e',
    },
  },
} satisfies Record<RainglowThemeId, ThemeSeed>;

export const rainglowThemes = Object.fromEntries(
  Object.entries(rainglowThemeSeeds).map(([id, theme]) => [
    id,
    {
      id,
      label: theme.label,
      family: 'Rainglow',
      mode: theme.mode,
      swatches: theme.swatches,
      variables: theme.variables,
      syntax: createSyntaxHighlighterStyle(theme),
    },
  ]),
) as Record<RainglowThemeId, AppTheme>;
