import { createSyntaxHighlighterStyle, type AppTheme, type RainglowThemeId, type ThemeMode, type ThemeSeed } from './types';

type RainglowThemeKind = 'light' | 'dark' | 'contrast';

type RainglowSeed = {
  id: RainglowThemeId;
  label: string;
  mode: ThemeMode;
  kind: RainglowThemeKind;
  swatches: string[];
  background: string;
  foreground: string;
  card: string;
  popover: string;
  primary: string;
  primaryForeground: string;
  secondary: string;
  mutedForeground: string;
  accent: string;
  destructive: string;
  border: string;
  input: string;
  ring: string;
  success: string;
  warning: string;
  purple: string;
  syntax: ThemeSeed['syntax'];
};

function createRainglowSeed(theme: RainglowSeed): ThemeSeed {
  return {
    label: theme.label,
    mode: theme.mode,
    swatches: theme.swatches,
    variables: {
      background: theme.background,
      foreground: theme.foreground,
      card: theme.card,
      'card-foreground': theme.foreground,
      popover: theme.popover,
      'popover-foreground': theme.foreground,
      primary: theme.primary,
      'primary-foreground': theme.primaryForeground,
      secondary: theme.secondary,
      'secondary-foreground': theme.foreground,
      muted: theme.secondary,
      'muted-foreground': theme.mutedForeground,
      accent: theme.accent,
      'accent-foreground': theme.mode === 'light' ? theme.primary : theme.foreground,
      destructive: theme.destructive,
      border: theme.border,
      input: theme.input,
      ring: theme.ring,
      'chart-1': theme.primary,
      'chart-2': theme.success,
      'chart-3': theme.warning,
      'chart-4': theme.purple,
      'chart-5': theme.destructive,
      sidebar: theme.card,
      'sidebar-foreground': theme.foreground,
      'sidebar-primary': theme.primary,
      'sidebar-primary-foreground': theme.primaryForeground,
      'sidebar-accent': theme.secondary,
      'sidebar-accent-foreground': theme.foreground,
      'sidebar-border': theme.border,
      'sidebar-ring': theme.ring,
      'plugin-accent': theme.purple,
      'plugin-active': theme.accent,
      'plugin-active-foreground': theme.foreground,
      'plugin-active-icon': theme.primary,
      'plugin-active-border': theme.ring,
    },
    syntax: theme.syntax,
  };
}

const rainglowThemeSeeds = [
  {
    "id": "rainglow-absent-contrast",
    "label": "Absent Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0e1114",
      "#228a96",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0e1114",
    "foreground": "#aeb9c4",
    "card": "#181e23",
    "popover": "#0a0c0e",
    "primary": "#228a96",
    "primaryForeground": "#ffffff",
    "secondary": "#14191d",
    "mutedForeground": "#343f4a",
    "accent": "#6ba77f",
    "destructive": "#e61f44",
    "border": "#384450",
    "input": "#030405",
    "ring": "#228a96",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#44515e",
      "text": "#aeb9c4",
      "keyword": "#228a96",
      "variable": "#bed0e2",
      "annotation": "#6ba77f",
      "constant": "#6ba77f",
      "tag": "#228a96",
      "string": "#addbbc",
      "interpolated": "#addbbc",
      "number": "#61bcc6",
      "function": "#e6eaef",
      "support": "#6ba77f",
      "misc": "#64778a",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-absent",
    "label": "Absent (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#252c33",
      "#228a96",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#252c33",
    "foreground": "#aeb9c4",
    "card": "#303942",
    "popover": "#21272d",
    "primary": "#228a96",
    "primaryForeground": "#ffffff",
    "secondary": "#2b343c",
    "mutedForeground": "#4c5a68",
    "accent": "#6ba77f",
    "destructive": "#e61f44",
    "border": "#505f6e",
    "input": "#1a1f24",
    "ring": "#228a96",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#44515e",
      "text": "#aeb9c4",
      "keyword": "#228a96",
      "variable": "#bed0e2",
      "annotation": "#6ba77f",
      "constant": "#6ba77f",
      "tag": "#228a96",
      "string": "#addbbc",
      "interpolated": "#addbbc",
      "number": "#61bcc6",
      "function": "#e6eaef",
      "support": "#6ba77f",
      "misc": "#64778a",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-absent-light",
    "label": "Absent Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#228a96",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#465360",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#228a96",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#6ba77f",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#228a96",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#aeb9c4",
      "text": "#465360",
      "keyword": "#228a96",
      "variable": "#353f49",
      "annotation": "#6ba77f",
      "constant": "#6ba77f",
      "tag": "#228a96",
      "string": "#478e5f",
      "interpolated": "#478e5f",
      "number": "#61bcc6",
      "function": "#465360",
      "support": "#6ba77f",
      "misc": "#8293a4",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-chocolate-light",
    "label": "Chocolate Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#5b472c",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#150f08",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#5b472c",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#a08f76",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#5b472c",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#e2cdb0",
      "text": "#150f08",
      "keyword": "#8e744f",
      "variable": "#150f08",
      "annotation": "#a08f76",
      "constant": "#a08f76",
      "tag": "#5b472c",
      "string": "#f7a21b",
      "interpolated": "#f7a21b",
      "number": "#f7a21b",
      "function": "#b5a48d",
      "support": "#5b472c",
      "misc": "#cdaa78",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-codecourse-contrast",
    "label": "Codecourse Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#05080a",
      "#1ea8fc",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#05080a",
    "foreground": "#b6ced8",
    "card": "#0d161b",
    "popover": "#020303",
    "primary": "#1ea8fc",
    "primaryForeground": "#ffffff",
    "secondary": "#0a1014",
    "mutedForeground": "#243947",
    "accent": "#5dcdfd",
    "destructive": "#e61f44",
    "border": "#273e4e",
    "input": "#000000",
    "ring": "#1ea8fc",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#456b7c",
      "text": "#b6ced8",
      "keyword": "#1ea8fc",
      "variable": "#ffffff",
      "annotation": "#5dcdfd",
      "constant": "#5dcdfd",
      "tag": "#1ea8fc",
      "string": "#cccccc",
      "interpolated": "#cccccc",
      "number": "#aaaaaa",
      "function": "#ffffff",
      "support": "#5dcdfd",
      "misc": "#6494a9",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-friction-light",
    "label": "Friction Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#8d89a5",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#ffffff",
    "foreground": "#38363f",
    "card": "#ffffff",
    "popover": "#fafafa",
    "primary": "#8d89a5",
    "primaryForeground": "#ffffff",
    "secondary": "#ffffff",
    "mutedForeground": "#ffffff",
    "accent": "#6aa7a7",
    "destructive": "#e61f44",
    "border": "#ffffff",
    "input": "#f2f2f2",
    "ring": "#8d89a5",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#545263",
      "text": "#38363f",
      "keyword": "#8d89a5",
      "variable": "#403e4c",
      "annotation": "#6aa7a7",
      "constant": "#6aa7a7",
      "tag": "#8d89a5",
      "string": "#bc6b79",
      "interpolated": "#bc6b79",
      "number": "#bcae6b",
      "function": "#c2bed6",
      "support": "#6aa7a7",
      "misc": "#78758d",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-github-contrast",
    "label": "Github Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#111111",
      "#7385bc",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#111111",
    "foreground": "#ffffff",
    "card": "#1e1e1e",
    "popover": "#0c0c0c",
    "primary": "#7385bc",
    "primaryForeground": "#ffffff",
    "secondary": "#191919",
    "mutedForeground": "#3f3f3f",
    "accent": "#66c4c4",
    "destructive": "#e61f44",
    "border": "#444444",
    "input": "#040404",
    "ring": "#7385bc",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#555555",
      "text": "#ffffff",
      "keyword": "#cccccc",
      "variable": "#26c1c1",
      "annotation": "#66c4c4",
      "constant": "#66c4c4",
      "tag": "#7385bc",
      "string": "#e53d67",
      "interpolated": "#e53d67",
      "number": "#e53d67",
      "function": "#e53d67",
      "support": "#5a6fad",
      "misc": "#7b7b7b",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-glowfish-contrast",
    "label": "Glowfish Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#090b07",
      "#95cc5e",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#090b07",
    "foreground": "#6ea240",
    "card": "#161b11",
    "popover": "#040503",
    "primary": "#95cc5e",
    "primaryForeground": "#ffffff",
    "secondary": "#11140d",
    "mutedForeground": "#37432b",
    "accent": "#db784d",
    "destructive": "#e61f44",
    "border": "#3c492f",
    "input": "#000000",
    "ring": "#95cc5e",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#3c4e2d",
      "text": "#6ea240",
      "keyword": "#d65940",
      "variable": "#6ea240",
      "annotation": "#db784d",
      "constant": "#db784d",
      "tag": "#95cc5e",
      "string": "#f8bb39",
      "interpolated": "#f8bb39",
      "number": "#95cc5e",
      "function": "#60a365",
      "support": "#95cc5e",
      "misc": "#617e49",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-glowfish",
    "label": "Glowfish (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#191f13",
      "#95cc5e",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#191f13",
    "foreground": "#6ea240",
    "card": "#262f1d",
    "popover": "#14190f",
    "primary": "#95cc5e",
    "primaryForeground": "#ffffff",
    "secondary": "#212819",
    "mutedForeground": "#475836",
    "accent": "#db784d",
    "destructive": "#e61f44",
    "border": "#4c5e3a",
    "input": "#0c0f09",
    "ring": "#95cc5e",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#3c4e2d",
      "text": "#6ea240",
      "keyword": "#d65940",
      "variable": "#6ea240",
      "annotation": "#db784d",
      "constant": "#db784d",
      "tag": "#95cc5e",
      "string": "#f8bb39",
      "interpolated": "#f8bb39",
      "number": "#95cc5e",
      "function": "#60a365",
      "support": "#95cc5e",
      "misc": "#617e49",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-grunge-contrast",
    "label": "Grunge Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0c0c0a",
      "#d1f2a5",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0c0c0a",
    "foreground": "#f8f8f2",
    "card": "#1a1a16",
    "popover": "#060605",
    "primary": "#d1f2a5",
    "primaryForeground": "#5c634f",
    "secondary": "#141411",
    "mutedForeground": "#3e3e34",
    "accent": "#f56991",
    "destructive": "#e61f44",
    "border": "#444438",
    "input": "#000000",
    "ring": "#d1f2a5",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#5c634f",
      "text": "#f8f8f2",
      "keyword": "#91a374",
      "variable": "#f8f8f2",
      "annotation": "#f56991",
      "constant": "#f56991",
      "tag": "#d1f2a5",
      "string": "#d1f2a5",
      "interpolated": "#d1f2a5",
      "number": "#f56991",
      "function": "#ffc48c",
      "support": "#ffc48c",
      "misc": "#848e71",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hawaii-contrast",
    "label": "Hawaii Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#111110",
      "#edbd44",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#111110",
    "foreground": "#e8e1de",
    "card": "#1e1e1c",
    "popover": "#0c0c0b",
    "primary": "#edbd44",
    "primaryForeground": "#ffffff",
    "secondary": "#191917",
    "mutedForeground": "#40403d",
    "accent": "#f75431",
    "destructive": "#e61f44",
    "border": "#464641",
    "input": "#040404",
    "ring": "#edbd44",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#706864",
      "text": "#e8e1de",
      "keyword": "#e2922f",
      "variable": "#ffffff",
      "annotation": "#f75431",
      "constant": "#f75431",
      "tag": "#edbd44",
      "string": "#a2d66b",
      "interpolated": "#a2d66b",
      "number": "#88c448",
      "function": "#52b4d8",
      "support": "#92d8e8",
      "misc": "#968e8a",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hawaii",
    "label": "Hawaii (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#333130",
      "#edbd44",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#333130",
    "foreground": "#e8e1de",
    "card": "#403e3c",
    "popover": "#2e2c2b",
    "primary": "#edbd44",
    "primaryForeground": "#ffffff",
    "secondary": "#3b3937",
    "mutedForeground": "#625e5d",
    "accent": "#f75431",
    "destructive": "#e61f44",
    "border": "#686361",
    "input": "#262424",
    "ring": "#edbd44",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#706864",
      "text": "#e8e1de",
      "keyword": "#e2922f",
      "variable": "#ffffff",
      "annotation": "#f75431",
      "constant": "#f75431",
      "tag": "#edbd44",
      "string": "#a2d66b",
      "interpolated": "#a2d66b",
      "number": "#88c448",
      "function": "#52b4d8",
      "support": "#92d8e8",
      "misc": "#968e8a",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hawaii-light",
    "label": "Hawaii Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#edbd44",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#6d6764",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#edbd44",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#f75431",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#edbd44",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#c4b5ae",
      "text": "#6d6764",
      "keyword": "#e2922f",
      "variable": "#6d6764",
      "annotation": "#f75431",
      "constant": "#f75431",
      "tag": "#edbd44",
      "string": "#a2d66b",
      "interpolated": "#a2d66b",
      "number": "#88c448",
      "function": "#52b4d8",
      "support": "#92d8e8",
      "misc": "#a48d82",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-heroku-contrast",
    "label": "Heroku Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0b0b0f",
      "#585480",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0b0b0f",
    "foreground": "#c8c7d5",
    "card": "#16161e",
    "popover": "#070709",
    "primary": "#585480",
    "primaryForeground": "#ffffff",
    "secondary": "#111118",
    "mutedForeground": "#323244",
    "accent": "#7873ae",
    "destructive": "#e61f44",
    "border": "#36364a",
    "input": "#000000",
    "ring": "#585480",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#505067",
      "text": "#c8c7d5",
      "keyword": "#7873ae",
      "variable": "#c8c7d5",
      "annotation": "#7873ae",
      "constant": "#7873ae",
      "tag": "#585480",
      "string": "#a6fa62",
      "interpolated": "#a6fa62",
      "number": "#a6fa62",
      "function": "#ffffff",
      "support": "#a6fa62",
      "misc": "#727291",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-heroku",
    "label": "Heroku (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#1b1b24",
      "#585480",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#1b1b24",
    "foreground": "#c8c7d5",
    "card": "#262633",
    "popover": "#17171e",
    "primary": "#585480",
    "primaryForeground": "#ffffff",
    "secondary": "#22222d",
    "mutedForeground": "#424258",
    "accent": "#7873ae",
    "destructive": "#e61f44",
    "border": "#47475e",
    "input": "#101015",
    "ring": "#585480",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#505067",
      "text": "#c8c7d5",
      "keyword": "#7873ae",
      "variable": "#c8c7d5",
      "annotation": "#7873ae",
      "constant": "#7873ae",
      "tag": "#585480",
      "string": "#a6fa62",
      "interpolated": "#a6fa62",
      "number": "#a6fa62",
      "function": "#ffffff",
      "support": "#a6fa62",
      "misc": "#727291",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-heroku-light",
    "label": "Heroku Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#f7f7fc",
      "#585480",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#f7f7fc",
    "foreground": "#1b1b24",
    "card": "#e4e4f5",
    "popover": "#f0f0f9",
    "primary": "#585480",
    "primaryForeground": "#ffffff",
    "secondary": "#ececf8",
    "mutedForeground": "#adade0",
    "accent": "#7873ae",
    "destructive": "#e61f44",
    "border": "#cacaeb",
    "input": "#f7f7fc",
    "ring": "#585480",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#505067",
      "text": "#1b1b24",
      "keyword": "#7873ae",
      "variable": "#1b1b24",
      "annotation": "#7873ae",
      "constant": "#7873ae",
      "tag": "#585480",
      "string": "#6daf36",
      "interpolated": "#6daf36",
      "number": "#6daf36",
      "function": "#b0add3",
      "support": "#6daf36",
      "misc": "#2f2f3c",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hive-contrast",
    "label": "Hive Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0f1016",
      "#7cb8ba",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0f1016",
    "foreground": "#ffffff",
    "card": "#191b25",
    "popover": "#0b0c10",
    "primary": "#7cb8ba",
    "primaryForeground": "#ffffff",
    "secondary": "#15171f",
    "mutedForeground": "#34384d",
    "accent": "#6e81a0",
    "destructive": "#e61f44",
    "border": "#383c53",
    "input": "#050507",
    "ring": "#7cb8ba",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#41435b",
      "text": "#ffffff",
      "keyword": "#7cb8ba",
      "variable": "#ffffff",
      "annotation": "#6e81a0",
      "constant": "#6e81a0",
      "tag": "#7cb8ba",
      "string": "#dbc583",
      "interpolated": "#dbc583",
      "number": "#83ba7c",
      "function": "#ffffff",
      "support": "#6e81a0",
      "misc": "#616488",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hive",
    "label": "Hive (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#2d3142",
      "#7cb8ba",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#2d3142",
    "foreground": "#ffffff",
    "card": "#373c51",
    "popover": "#292c3c",
    "primary": "#7cb8ba",
    "primaryForeground": "#ffffff",
    "secondary": "#33384b",
    "mutedForeground": "#525a79",
    "accent": "#6e81a0",
    "destructive": "#e61f44",
    "border": "#565e7f",
    "input": "#232633",
    "ring": "#7cb8ba",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#4e556d",
      "text": "#ffffff",
      "keyword": "#7cb8ba",
      "variable": "#ffffff",
      "annotation": "#6e81a0",
      "constant": "#6e81a0",
      "tag": "#7cb8ba",
      "string": "#dbc583",
      "interpolated": "#dbc583",
      "number": "#83ba7c",
      "function": "#ffffff",
      "support": "#6e81a0",
      "misc": "#6f7998",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hive-light",
    "label": "Hive Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#7cb8ba",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#2d3142",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#7cb8ba",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#6e81a0",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#7cb8ba",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#9b9fb2",
      "text": "#2d3142",
      "keyword": "#7cb8ba",
      "variable": "#484e68",
      "annotation": "#6e81a0",
      "constant": "#6e81a0",
      "tag": "#7cb8ba",
      "string": "#dbc583",
      "interpolated": "#dbc583",
      "number": "#83ba7c",
      "function": "#2d3142",
      "support": "#6e81a0",
      "misc": "#707691",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-horizon-contrast",
    "label": "Horizon Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#11101c",
      "#fd8a25",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#11101c",
    "foreground": "#edebe6",
    "card": "#1b192c",
    "popover": "#0d0c15",
    "primary": "#fd8a25",
    "primaryForeground": "#ffffff",
    "secondary": "#171626",
    "mutedForeground": "#343156",
    "accent": "#b133dc",
    "destructive": "#e61f44",
    "border": "#38355d",
    "input": "#07070c",
    "ring": "#fd8a25",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#36345a",
      "text": "#edebe6",
      "keyword": "#e5194b",
      "variable": "#edebe6",
      "annotation": "#b133dc",
      "constant": "#b133dc",
      "tag": "#fd8a25",
      "string": "#fd8a25",
      "interpolated": "#fd8a25",
      "number": "#e524a9",
      "function": "#fed230",
      "support": "#e524a9",
      "misc": "#53508a",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-horizon",
    "label": "Horizon (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#474466",
      "#fd8a25",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#474466",
    "foreground": "#ffffff",
    "card": "#524e75",
    "popover": "#434060",
    "primary": "#fd8a25",
    "primaryForeground": "#ffffff",
    "secondary": "#4d4a6f",
    "mutedForeground": "#6e6a9c",
    "accent": "#ba66d6",
    "destructive": "#e61f44",
    "border": "#7470a0",
    "input": "#3c3a57",
    "ring": "#fd8a25",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#736faa",
      "text": "#ffffff",
      "keyword": "#e5194b",
      "variable": "#dddced",
      "annotation": "#ba66d6",
      "constant": "#ba66d6",
      "tag": "#fd8a25",
      "string": "#fd8a25",
      "interpolated": "#fd8a25",
      "number": "#e524a9",
      "function": "#fed230",
      "support": "#e524a9",
      "misc": "#a29fc6",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-horizon-light",
    "label": "Horizon Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#fd8a25",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#474466",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#fd8a25",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#ba66d6",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#fd8a25",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#736faa",
      "text": "#474466",
      "keyword": "#e5194b",
      "variable": "#686491",
      "annotation": "#ba66d6",
      "constant": "#ba66d6",
      "tag": "#fd8a25",
      "string": "#fd8a25",
      "interpolated": "#fd8a25",
      "number": "#e524a9",
      "function": "#fed230",
      "support": "#e524a9",
      "misc": "#4f4c81",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hub-contrast",
    "label": "Hub Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#191d21",
      "#e85362",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#191d21",
    "foreground": "#ffffff",
    "card": "#242a2f",
    "popover": "#15181b",
    "primary": "#e85362",
    "primaryForeground": "#ffffff",
    "secondary": "#20252a",
    "mutedForeground": "#414b55",
    "accent": "#5392db",
    "destructive": "#e61f44",
    "border": "#45505b",
    "input": "#0e1012",
    "ring": "#e85362",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#718493",
      "text": "#ffffff",
      "keyword": "#e85362",
      "variable": "#ffffff",
      "annotation": "#5392db",
      "constant": "#5392db",
      "tag": "#e85362",
      "string": "#9fbde0",
      "interpolated": "#9fbde0",
      "number": "#9fbde0",
      "function": "#5392db",
      "support": "#9b78db",
      "misc": "#9caab4",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hub",
    "label": "Hub (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#3b444c",
      "#e85362",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#3b444c",
    "foreground": "#ffffff",
    "card": "#46515a",
    "popover": "#373f46",
    "primary": "#e85362",
    "primaryForeground": "#ffffff",
    "secondary": "#424c55",
    "mutedForeground": "#637280",
    "accent": "#5392db",
    "destructive": "#e61f44",
    "border": "#687785",
    "input": "#30373e",
    "ring": "#e85362",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#718493",
      "text": "#ffffff",
      "keyword": "#e85362",
      "variable": "#ffffff",
      "annotation": "#5392db",
      "constant": "#5392db",
      "tag": "#e85362",
      "string": "#9fbde0",
      "interpolated": "#9fbde0",
      "number": "#9fbde0",
      "function": "#5392db",
      "support": "#9b78db",
      "misc": "#9caab4",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hyrule-contrast",
    "label": "Hyrule Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0c0c0c",
      "#f5c504",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0c0c0c",
    "foreground": "#c0d5c1",
    "card": "#191919",
    "popover": "#070707",
    "primary": "#f5c504",
    "primaryForeground": "#ffffff",
    "secondary": "#141414",
    "mutedForeground": "#3a3a3a",
    "accent": "#569e16",
    "destructive": "#e61f44",
    "border": "#3f3f3f",
    "input": "#000000",
    "ring": "#f5c504",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#716d6a",
      "text": "#c0d5c1",
      "keyword": "#90c93f",
      "variable": "#c0d5c1",
      "annotation": "#569e16",
      "constant": "#569e16",
      "tag": "#f5c504",
      "string": "#ce830d",
      "interpolated": "#ce830d",
      "number": "#f5c504",
      "function": "#90c93f",
      "support": "#f5c504",
      "misc": "#979390",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hyrule",
    "label": "Hyrule (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#2d2c2b",
      "#f5c504",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#2d2c2b",
    "foreground": "#c0d5c1",
    "card": "#3a3937",
    "popover": "#282726",
    "primary": "#f5c504",
    "primaryForeground": "#ffffff",
    "secondary": "#353432",
    "mutedForeground": "#5c5a58",
    "accent": "#569e16",
    "destructive": "#e61f44",
    "border": "#615f5d",
    "input": "#201f1f",
    "ring": "#f5c504",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#716d6a",
      "text": "#c0d5c1",
      "keyword": "#90c93f",
      "variable": "#c0d5c1",
      "annotation": "#569e16",
      "constant": "#569e16",
      "tag": "#f5c504",
      "string": "#ce830d",
      "interpolated": "#ce830d",
      "number": "#f5c504",
      "function": "#90c93f",
      "support": "#f5c504",
      "misc": "#979390",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-hyrule-light",
    "label": "Hyrule Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#c0d5c1",
      "#b7950c",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#c0d5c1",
    "foreground": "#2d2c2b",
    "card": "#b1cbb2",
    "popover": "#bad1bb",
    "primary": "#b7950c",
    "primaryForeground": "#ffffff",
    "secondary": "#b7cfb8",
    "mutedForeground": "#83ac85",
    "accent": "#407710",
    "destructive": "#e61f44",
    "border": "#9bbd9d",
    "input": "#c0d5c1",
    "ring": "#b7950c",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#93a594",
      "text": "#2d2c2b",
      "keyword": "#68912e",
      "variable": "#2d2c2b",
      "annotation": "#407710",
      "constant": "#407710",
      "tag": "#b7950c",
      "string": "#ce830d",
      "interpolated": "#ce830d",
      "number": "#f5c504",
      "function": "#68912e",
      "support": "#b7950c",
      "misc": "#6b806c",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-iceberg-contrast",
    "label": "Iceberg Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0b0e0e",
      "#59c0e3",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0b0e0e",
    "foreground": "#bdd6db",
    "card": "#161c1c",
    "popover": "#070808",
    "primary": "#59c0e3",
    "primaryForeground": "#ffffff",
    "secondary": "#121717",
    "mutedForeground": "#334141",
    "accent": "#2d8da1",
    "destructive": "#e61f44",
    "border": "#384747",
    "input": "#000000",
    "ring": "#59c0e3",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#537178",
      "text": "#bdd6db",
      "keyword": "#b1e2f2",
      "variable": "#bdd6db",
      "annotation": "#2d8da1",
      "constant": "#2d8da1",
      "tag": "#59c0e3",
      "string": "#ffffff",
      "interpolated": "#ffffff",
      "number": "#ffffff",
      "function": "#ffffff",
      "support": "#ffffff",
      "misc": "#7799a1",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-iceberg",
    "label": "Iceberg (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#323b3d",
      "#59c0e3",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#323b3d",
    "foreground": "#bdd6db",
    "card": "#3d494b",
    "popover": "#2d3637",
    "primary": "#59c0e3",
    "primaryForeground": "#ffffff",
    "secondary": "#394345",
    "mutedForeground": "#5b6c6f",
    "accent": "#2d8da1",
    "destructive": "#e61f44",
    "border": "#607175",
    "input": "#272d2f",
    "ring": "#59c0e3",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#537178",
      "text": "#bdd6db",
      "keyword": "#b1e2f2",
      "variable": "#bdd6db",
      "annotation": "#2d8da1",
      "constant": "#2d8da1",
      "tag": "#59c0e3",
      "string": "#ffffff",
      "interpolated": "#ffffff",
      "number": "#ffffff",
      "function": "#ffffff",
      "support": "#ffffff",
      "misc": "#7799a1",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-iceberg-light",
    "label": "Iceberg Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#bdd6db",
      "#499fbc",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#bdd6db",
    "foreground": "#323b3d",
    "card": "#adccd2",
    "popover": "#b6d2d7",
    "primary": "#499fbc",
    "primaryForeground": "#ffffff",
    "secondary": "#b3d0d6",
    "mutedForeground": "#7badb7",
    "accent": "#2d8da1",
    "destructive": "#e61f44",
    "border": "#95bdc5",
    "input": "#bdd6db",
    "ring": "#499fbc",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#7e9296",
      "text": "#323b3d",
      "keyword": "#7ea3af",
      "variable": "#323b3d",
      "annotation": "#2d8da1",
      "constant": "#2d8da1",
      "tag": "#499fbc",
      "string": "#2d8da1",
      "interpolated": "#2d8da1",
      "number": "#2d8da1",
      "function": "#323b3d",
      "support": "#323b3d",
      "misc": "#5a6b6e",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-isotope-contrast",
    "label": "Isotope Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0e0f11",
      "#72b01d",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0e0f11",
    "foreground": "#f3eff5",
    "card": "#191b1f",
    "popover": "#090a0b",
    "primary": "#72b01d",
    "primaryForeground": "#ffffff",
    "secondary": "#151619",
    "mutedForeground": "#373b43",
    "accent": "#b3dd49",
    "destructive": "#e61f44",
    "border": "#3c4049",
    "input": "#020303",
    "ring": "#72b01d",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#7b85a0",
      "text": "#f3eff5",
      "keyword": "#b3dd49",
      "variable": "#ffffff",
      "annotation": "#b3dd49",
      "constant": "#b3dd49",
      "tag": "#72b01d",
      "string": "#86baba",
      "interpolated": "#86baba",
      "number": "#afd1d1",
      "function": "#ffffff",
      "support": "#72b01d",
      "misc": "#a7aec0",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-isotope",
    "label": "Isotope (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#454955",
      "#72b01d",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#454955",
    "foreground": "#f3eff5",
    "card": "#505563",
    "popover": "#40444f",
    "primary": "#72b01d",
    "primaryForeground": "#ffffff",
    "secondary": "#4c505d",
    "mutedForeground": "#6e7588",
    "accent": "#b3dd49",
    "destructive": "#e61f44",
    "border": "#73798d",
    "input": "#3a3d47",
    "ring": "#72b01d",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#7b85a0",
      "text": "#f3eff5",
      "keyword": "#b3dd49",
      "variable": "#ffffff",
      "annotation": "#b3dd49",
      "constant": "#b3dd49",
      "tag": "#72b01d",
      "string": "#86baba",
      "interpolated": "#86baba",
      "number": "#afd1d1",
      "function": "#ffffff",
      "support": "#72b01d",
      "misc": "#a7aec0",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-keen-light",
    "label": "Keen Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#cccccc",
      "#6f8b94",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#cccccc",
    "foreground": "#111111",
    "card": "#bfbfbf",
    "popover": "#c7c7c7",
    "primary": "#6f8b94",
    "primaryForeground": "#ffffff",
    "secondary": "#c4c4c4",
    "mutedForeground": "#999999",
    "accent": "#8767b7",
    "destructive": "#e61f44",
    "border": "#adadad",
    "input": "#cccccc",
    "ring": "#6f8b94",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#6b8eaf",
      "text": "#111111",
      "keyword": "#6f8b94",
      "variable": "#111111",
      "annotation": "#8767b7",
      "constant": "#8767b7",
      "tag": "#6f8b94",
      "string": "#7c9669",
      "interpolated": "#7c9669",
      "number": "#7c9669",
      "function": "#7c9669",
      "support": "#8767b7",
      "misc": "#486885",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-lavender-light",
    "label": "Lavender Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#a29dfa",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#29222e",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#a29dfa",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#b657ff",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#a29dfa",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#9177a3",
      "text": "#29222e",
      "keyword": "#8e6da6",
      "variable": "#29222e",
      "annotation": "#b657ff",
      "constant": "#b657ff",
      "tag": "#a29dfa",
      "string": "#f5b0ef",
      "interpolated": "#f5b0ef",
      "number": "#f25ae6",
      "function": "#f5b0ef",
      "support": "#8e69c9",
      "misc": "#6a537b",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-prime-contrast",
    "label": "Prime Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0b0b11",
      "#9d50ba",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0b0b11",
    "foreground": "#9090b2",
    "card": "#151520",
    "popover": "#07070b",
    "primary": "#9d50ba",
    "primaryForeground": "#ffffff",
    "secondary": "#11111a",
    "mutedForeground": "#2f2f49",
    "accent": "#ee4266",
    "destructive": "#e61f44",
    "border": "#33334f",
    "input": "#010102",
    "ring": "#9d50ba",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#4c4c70",
      "text": "#9090b2",
      "keyword": "#f3fcf0",
      "variable": "#d5d5e8",
      "annotation": "#ee4266",
      "constant": "#ee4266",
      "tag": "#9d50ba",
      "string": "#a2d66b",
      "interpolated": "#a2d66b",
      "number": "#88c448",
      "function": "#ffd23f",
      "support": "#ee4266",
      "misc": "#6d6d9c",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-prime",
    "label": "Prime (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#202030",
      "#9d50ba",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#202030",
    "foreground": "#9090b2",
    "card": "#2a2a3f",
    "popover": "#1c1c2a",
    "primary": "#9d50ba",
    "primaryForeground": "#ffffff",
    "secondary": "#262639",
    "mutedForeground": "#454567",
    "accent": "#ee4266",
    "destructive": "#e61f44",
    "border": "#49496d",
    "input": "#161621",
    "ring": "#9d50ba",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#4c4c70",
      "text": "#9090b2",
      "keyword": "#f3fcf0",
      "variable": "#d5d5e8",
      "annotation": "#ee4266",
      "constant": "#ee4266",
      "tag": "#9d50ba",
      "string": "#a2d66b",
      "interpolated": "#a2d66b",
      "number": "#88c448",
      "function": "#ffd23f",
      "support": "#ee4266",
      "misc": "#6d6d9c",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-rebellion-contrast",
    "label": "Rebellion Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0c0c09",
      "#fe5f00",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0c0c09",
    "foreground": "#d6c7ab",
    "card": "#1b1b14",
    "popover": "#060605",
    "primary": "#fe5f00",
    "primaryForeground": "#ffffff",
    "secondary": "#151510",
    "mutedForeground": "#404030",
    "accent": "#988f2a",
    "destructive": "#e61f44",
    "border": "#464635",
    "input": "#000000",
    "ring": "#fe5f00",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#51513d",
      "text": "#d6c7ab",
      "keyword": "#fe5f00",
      "variable": "#edebe6",
      "annotation": "#988f2a",
      "constant": "#988f2a",
      "tag": "#fe5f00",
      "string": "#fdb825",
      "interpolated": "#fdb825",
      "number": "#fd9825",
      "function": "#8e7547",
      "support": "#988f2a",
      "misc": "#7d7d5e",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-rebellion",
    "label": "Rebellion (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#23231a",
      "#fe5f00",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#23231a",
    "foreground": "#d6c7ab",
    "card": "#323225",
    "popover": "#1d1d16",
    "primary": "#fe5f00",
    "primaryForeground": "#ffffff",
    "secondary": "#2c2c21",
    "mutedForeground": "#585841",
    "accent": "#988f2a",
    "destructive": "#e61f44",
    "border": "#5e5e45",
    "input": "#14140f",
    "ring": "#fe5f00",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#51513d",
      "text": "#d6c7ab",
      "keyword": "#fe5f00",
      "variable": "#edebe6",
      "annotation": "#988f2a",
      "constant": "#988f2a",
      "tag": "#fe5f00",
      "string": "#fdb825",
      "interpolated": "#fdb825",
      "number": "#fd9825",
      "function": "#8e7547",
      "support": "#988f2a",
      "misc": "#7d7d5e",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-rebellion-light",
    "label": "Rebellion Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ede8de",
      "#fe5f00",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ede8de",
    "foreground": "#443a27",
    "card": "#e4dcce",
    "popover": "#e9e3d7",
    "primary": "#fe5f00",
    "primaryForeground": "#ffffff",
    "secondary": "#e8e1d4",
    "mutedForeground": "#c9ba9c",
    "accent": "#988f2a",
    "destructive": "#e61f44",
    "border": "#d7ccb6",
    "input": "#ede8de",
    "ring": "#fe5f00",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#8e8e70",
      "text": "#443a27",
      "keyword": "#fe5f00",
      "variable": "#705e3d",
      "annotation": "#988f2a",
      "constant": "#988f2a",
      "tag": "#fe5f00",
      "string": "#fdb825",
      "interpolated": "#fdb825",
      "number": "#fd9825",
      "function": "#8e7547",
      "support": "#988f2a",
      "misc": "#63634e",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-shrek-light",
    "label": "Shrek Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#b2de62",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#222222",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#b2de62",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#857a5e",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#b2de62",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#aaaaaa",
      "text": "#222222",
      "keyword": "#bfb59b",
      "variable": "#555555",
      "annotation": "#857a5e",
      "constant": "#857a5e",
      "tag": "#b2de62",
      "string": "#81e911",
      "interpolated": "#81e911",
      "number": "#81e911",
      "function": "#afb2a7",
      "support": "#b2de62",
      "misc": "#848484",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-slime",
    "label": "Slime (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#292d30",
      "#faffdb",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#292d30",
    "foreground": "#ffffff",
    "card": "#353a3e",
    "popover": "#24282a",
    "primary": "#faffdb",
    "primaryForeground": "#3b3a32",
    "secondary": "#303538",
    "mutedForeground": "#535b62",
    "accent": "#9fb3c2",
    "destructive": "#e61f44",
    "border": "#586167",
    "input": "#1d2022",
    "ring": "#faffdb",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#4f5a63",
      "text": "#ffffff",
      "keyword": "#9fb3c2",
      "variable": "#ffffff",
      "annotation": "#9fb3c2",
      "constant": "#9fb3c2",
      "tag": "#faffdb",
      "string": "#faffdb",
      "interpolated": "#faffdb",
      "number": "#c7af3f",
      "function": "#c7af3f",
      "support": "#c7af3f",
      "misc": "#71818e",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-stealth-contrast",
    "label": "Stealth Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#0d0e0f",
      "#3c4044",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#0d0e0f",
    "foreground": "#5f656d",
    "card": "#191b1d",
    "popover": "#08090a",
    "primary": "#3c4044",
    "primaryForeground": "#ffffff",
    "secondary": "#141617",
    "mutedForeground": "#383c40",
    "accent": "#474c51",
    "destructive": "#e61f44",
    "border": "#3c4146",
    "input": "#010101",
    "ring": "#3c4044",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#323538",
      "text": "#5f656d",
      "keyword": "#474c51",
      "variable": "#727982",
      "annotation": "#474c51",
      "constant": "#474c51",
      "tag": "#3c4044",
      "string": "#545a60",
      "interpolated": "#545a60",
      "number": "#545a60",
      "function": "#545a60",
      "support": "#3c4044",
      "misc": "#565b60",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-stealth",
    "label": "Stealth (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#27292b",
      "#3c4044",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#27292b",
    "foreground": "#5f656d",
    "card": "#333638",
    "popover": "#222426",
    "primary": "#3c4044",
    "primaryForeground": "#ffffff",
    "secondary": "#2e3133",
    "mutedForeground": "#53575b",
    "accent": "#474c51",
    "destructive": "#e61f44",
    "border": "#575c60",
    "input": "#1b1c1e",
    "ring": "#3c4044",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#323538",
      "text": "#5f656d",
      "keyword": "#474c51",
      "variable": "#727982",
      "annotation": "#474c51",
      "constant": "#474c51",
      "tag": "#3c4044",
      "string": "#545a60",
      "interpolated": "#545a60",
      "number": "#545a60",
      "function": "#545a60",
      "support": "#3c4044",
      "misc": "#565b60",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-stealth-light",
    "label": "Stealth Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#bbbbbb",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#cccccc",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#bbbbbb",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#dddddd",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#bbbbbb",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#dddddd",
      "text": "#cccccc",
      "keyword": "#eeeeee",
      "variable": "#cccccc",
      "annotation": "#dddddd",
      "constant": "#dddddd",
      "tag": "#bbbbbb",
      "string": "#888888",
      "interpolated": "#888888",
      "number": "#888888",
      "function": "#aaaaaa",
      "support": "#bbbbbb",
      "misc": "#b7b7b7",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-tickle",
    "label": "Tickle (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#39393a",
      "#85ffc7",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#39393a",
    "foreground": "#c1c1c1",
    "card": "#464647",
    "popover": "#343435",
    "primary": "#85ffc7",
    "primaryForeground": "#35443d",
    "secondary": "#414142",
    "mutedForeground": "#666668",
    "accent": "#40a5a5",
    "destructive": "#e61f44",
    "border": "#6c6c6d",
    "input": "#2c2c2d",
    "ring": "#85ffc7",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#606063",
      "text": "#c1c1c1",
      "keyword": "#85ffc7",
      "variable": "#ffffff",
      "annotation": "#40a5a5",
      "constant": "#40a5a5",
      "tag": "#85ffc7",
      "string": "#86baba",
      "interpolated": "#86baba",
      "number": "#afd1d1",
      "function": "#ff8552",
      "support": "#ff8552",
      "misc": "#86868a",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-vision-colorblind",
    "label": "Vision (Colorblind) (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#000000",
      "#fc4d1f",
      "#1ba2f7",
      "#81209e"
    ],
    "background": "#000000",
    "foreground": "#ffffff",
    "card": "#0d0d0d",
    "popover": "#000000",
    "primary": "#fc4d1f",
    "primaryForeground": "#ffffff",
    "secondary": "#080808",
    "mutedForeground": "#2e2e2e",
    "accent": "#fdba2c",
    "destructive": "#f87856",
    "border": "#333333",
    "input": "#000000",
    "ring": "#fc4d1f",
    "success": "#1ba2f7",
    "warning": "#81209e",
    "purple": "#81209e",
    "syntax": {
      "comment": "#555555",
      "text": "#ffffff",
      "keyword": "#136efb",
      "variable": "#aaaaaa",
      "annotation": "#fdba2c",
      "constant": "#fdba2c",
      "tag": "#fc4d1f",
      "string": "#21c0fc",
      "interpolated": "#21c0fc",
      "number": "#fdba2c",
      "function": "#21c0fc",
      "support": "#fc1264",
      "misc": "#7b7b7b",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-vision-light-colorblind",
    "label": "Vision Light (Colorblind) (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#81209e",
      "#1ba2f7",
      "#81209e"
    ],
    "background": "#ffffff",
    "foreground": "#000000",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#81209e",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#1ba2f7",
    "destructive": "#f87856",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#81209e",
    "success": "#1ba2f7",
    "warning": "#81209e",
    "purple": "#81209e",
    "syntax": {
      "comment": "#555555",
      "text": "#000000",
      "keyword": "#f87856",
      "variable": "#1ba2f7",
      "annotation": "#1ba2f7",
      "constant": "#1ba2f7",
      "tag": "#81209e",
      "string": "#0b6aa5",
      "interpolated": "#0b6aa5",
      "number": "#0b6aa5",
      "function": "#f87856",
      "support": "#81209e",
      "misc": "#2f2f2f",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-yitzchok-contrast",
    "label": "Yitzchok Contrast (Rainglow)",
    "mode": "dark",
    "kind": "contrast",
    "swatches": [
      "#101316",
      "#e7be45",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#101316",
    "foreground": "#afb7bf",
    "card": "#1b2025",
    "popover": "#0c0e10",
    "primary": "#e7be45",
    "primaryForeground": "#ffffff",
    "secondary": "#161b1f",
    "mutedForeground": "#37414b",
    "accent": "#7a8289",
    "destructive": "#e61f44",
    "border": "#3b4651",
    "input": "#050607",
    "ring": "#e7be45",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#49525b",
      "text": "#afb7bf",
      "keyword": "#e7be45",
      "variable": "#d0d9e2",
      "annotation": "#7a8289",
      "constant": "#7a8289",
      "tag": "#e7be45",
      "string": "#eae18f",
      "interpolated": "#eae18f",
      "number": "#bab47c",
      "function": "#e6eaef",
      "support": "#7a8289",
      "misc": "#6b7885",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-yitzchok-light",
    "label": "Yitzchok Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#e7be45",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#6a7684",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#e7be45",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#7a8289",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#e7be45",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#aeb9c4",
      "text": "#6a7684",
      "keyword": "#e7be45",
      "variable": "#535d68",
      "annotation": "#7a8289",
      "constant": "#7a8289",
      "tag": "#e7be45",
      "string": "#afa441",
      "interpolated": "#afa441",
      "number": "#998d29",
      "function": "#6a7684",
      "support": "#7a8289",
      "misc": "#8293a4",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-yule-light",
    "label": "Yule Light (Rainglow)",
    "mode": "light",
    "kind": "light",
    "swatches": [
      "#ffffff",
      "#39b81f",
      "#59a50b",
      "#6a1faf"
    ],
    "background": "#ffffff",
    "foreground": "#444444",
    "card": "#f2f2f2",
    "popover": "#fafafa",
    "primary": "#39b81f",
    "primaryForeground": "#ffffff",
    "secondary": "#f7f7f7",
    "mutedForeground": "#cccccc",
    "accent": "#d63131",
    "destructive": "#e61f44",
    "border": "#e0e0e0",
    "input": "#ffffff",
    "ring": "#39b81f",
    "success": "#59a50b",
    "warning": "#c48405",
    "purple": "#6a1faf",
    "syntax": {
      "comment": "#aaaaaa",
      "text": "#444444",
      "keyword": "#39b81f",
      "variable": "#444444",
      "annotation": "#d63131",
      "constant": "#d63131",
      "tag": "#39b81f",
      "string": "#ebb626",
      "interpolated": "#ebb626",
      "number": "#ebb626",
      "function": "#ebb626",
      "support": "#d63131",
      "misc": "#848484",
      "invalid": "#cf433e"
    }
  },
  {
    "id": "rainglow-zacks",
    "label": "Zacks (Rainglow)",
    "mode": "dark",
    "kind": "dark",
    "swatches": [
      "#222222",
      "#9c7ddb",
      "#a7da1e",
      "#9d37fc"
    ],
    "background": "#222222",
    "foreground": "#f0f0f0",
    "card": "#2f2f2f",
    "popover": "#1d1d1d",
    "primary": "#9c7ddb",
    "primaryForeground": "#ffffff",
    "secondary": "#2a2a2a",
    "mutedForeground": "#505050",
    "accent": "#ff6a38",
    "destructive": "#e61f44",
    "border": "#555555",
    "input": "#151515",
    "ring": "#9c7ddb",
    "success": "#a7da1e",
    "warning": "#f7b83d",
    "purple": "#9d37fc",
    "syntax": {
      "comment": "#777777",
      "text": "#f0f0f0",
      "keyword": "#ff6a38",
      "variable": "#f0f0f0",
      "annotation": "#ff6a38",
      "constant": "#ff6a38",
      "tag": "#9c7ddb",
      "string": "#bcd42a",
      "interpolated": "#bcd42a",
      "number": "#bcd42a",
      "function": "#bcd42a",
      "support": "#9c7ddb",
      "misc": "#9d9d9d",
      "invalid": "#cf433e"
    }
  }
] satisfies RainglowSeed[];

export const rainglowThemeIds: RainglowThemeId[] = rainglowThemeSeeds.map((theme) => theme.id);
export const rainglowLightThemeIds: RainglowThemeId[] = rainglowThemeSeeds
  .filter((theme) => theme.kind === 'light')
  .map((theme) => theme.id);
export const rainglowDarkThemeIds: RainglowThemeId[] = rainglowThemeSeeds
  .filter((theme) => theme.kind === 'dark')
  .map((theme) => theme.id);
export const rainglowContrastThemeIds: RainglowThemeId[] = rainglowThemeSeeds
  .filter((theme) => theme.kind === 'contrast')
  .map((theme) => theme.id);

export const rainglowThemes = Object.fromEntries(
  rainglowThemeSeeds.map((theme) => {
    const seed = createRainglowSeed(theme);

    return [
      theme.id,
      {
        id: theme.id,
        label: seed.label,
        family: 'Rainglow',
        mode: seed.mode,
        swatches: seed.swatches,
        variables: seed.variables,
        syntax: createSyntaxHighlighterStyle(seed),
      },
    ];
  }),
) as Record<RainglowThemeId, AppTheme>;
