import { createSyntaxHighlighterStyle, type AppTheme, type ThemeSeed, type TokyoNightThemeId } from './types';

const tokyoNightThemeSeeds = {
  'tokyo-night-light': {
    label: 'Tokyo Night Light',
    mode: 'light',
    swatches: ['#e6e7ed', '#2959aa', '#33635c', '#5a3e8e'],
    variables: {
      background: '#e6e7ed',
      foreground: '#343b58',
      card: '#d6d8df',
      'card-foreground': '#363c4d',
      popover: '#dcdee3',
      'popover-foreground': '#363c4d',
      primary: '#2959aa',
      'primary-foreground': '#ffffff',
      secondary: '#d6d8df',
      'secondary-foreground': '#343b58',
      muted: '#dcdee3',
      'muted-foreground': '#707280',
      accent: '#c8ccda',
      'accent-foreground': '#2959aa',
      destructive: '#942f2f',
      border: '#c1c2c7',
      input: '#e6e7ed',
      ring: '#2959aa',
      'chart-1': '#2959aa',
      'chart-2': '#33635c',
      'chart-3': '#8f5e15',
      'chart-4': '#5a3e8e',
      'chart-5': '#8c4351',
      sidebar: '#d6d8df',
      'sidebar-foreground': '#363c4d',
      'sidebar-primary': '#2959aa',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#e6e7ed',
      'sidebar-accent-foreground': '#2959aa',
      'sidebar-border': '#c1c2c7',
      'sidebar-ring': '#2959aa',
      'plugin-accent': '#5a3e8e',
      'plugin-active': '#e6e7ed',
      'plugin-active-foreground': '#2959aa',
      'plugin-active-icon': '#006c86',
      'plugin-active-border': '#7a85a8',
    },
    syntax: {
      comment: '#6c6e75',
      text: '#343b58',
      keyword: '#5a3e8e',
      variable: '#343b58',
      annotation: '#634f30',
      constant: '#965027',
      tag: '#8c4351',
      string: '#385f0d',
      interpolated: '#33635c',
      number: '#965027',
      function: '#2959aa',
      support: '#006c86',
      misc: '#0f4b6e',
      invalid: '#942f2f',
    },
  },
  'tokyo-night': {
    label: 'Tokyo Night',
    mode: 'dark',
    swatches: ['#1a1b26', '#7aa2f7', '#73daca', '#bb9af7'],
    variables: {
      background: '#1a1b26',
      foreground: '#a9b1d6',
      card: '#16161e',
      'card-foreground': '#a9b1d6',
      popover: '#101014',
      'popover-foreground': '#a9b1d6',
      primary: '#7aa2f7',
      'primary-foreground': '#101014',
      secondary: '#1e202e',
      'secondary-foreground': '#a9b1d6',
      muted: '#202330',
      'muted-foreground': '#787c99',
      accent: '#202330',
      'accent-foreground': '#7dcfff',
      destructive: '#db4b4b',
      border: '#101014',
      input: '#14141b',
      ring: '#7aa2f7',
      'chart-1': '#7aa2f7',
      'chart-2': '#73daca',
      'chart-3': '#e0af68',
      'chart-4': '#bb9af7',
      'chart-5': '#f7768e',
      sidebar: '#16161e',
      'sidebar-foreground': '#787c99',
      'sidebar-primary': '#7aa2f7',
      'sidebar-primary-foreground': '#101014',
      'sidebar-accent': '#1e202e',
      'sidebar-accent-foreground': '#a9b1d6',
      'sidebar-border': '#101014',
      'sidebar-ring': '#7aa2f7',
      'plugin-accent': '#bb9af7',
      'plugin-active': '#1e202e',
      'plugin-active-foreground': '#c0caf5',
      'plugin-active-icon': '#73daca',
      'plugin-active-border': '#3d59a1',
    },
    syntax: {
      comment: '#565f89',
      text: '#a9b1d6',
      keyword: '#bb9af7',
      variable: '#c0caf5',
      annotation: '#9abdf5',
      constant: '#ff9e64',
      tag: '#f7768e',
      string: '#9ece6a',
      interpolated: '#73daca',
      number: '#ff9e64',
      function: '#7aa2f7',
      support: '#2ac3de',
      misc: '#7dcfff',
      invalid: '#db4b4b',
    },
  },
  'tokyo-night-storm': {
    label: 'Tokyo Night Storm',
    mode: 'dark',
    swatches: ['#24283b', '#7aa2f7', '#73daca', '#bb9af7'],
    variables: {
      background: '#24283b',
      foreground: '#a9b1d6',
      card: '#1f2335',
      'card-foreground': '#a9b1d6',
      popover: '#1b1e2e',
      'popover-foreground': '#a9b1d6',
      primary: '#7aa2f7',
      'primary-foreground': '#1b1e2e',
      secondary: '#292e42',
      'secondary-foreground': '#a9b1d6',
      muted: '#2c324a',
      'muted-foreground': '#8089b3',
      accent: '#292e42',
      'accent-foreground': '#7dcfff',
      destructive: '#db4b4b',
      border: '#1b1e2e',
      input: '#1b1e2e',
      ring: '#7aa2f7',
      'chart-1': '#7aa2f7',
      'chart-2': '#73daca',
      'chart-3': '#e0af68',
      'chart-4': '#bb9af7',
      'chart-5': '#f7768e',
      sidebar: '#1f2335',
      'sidebar-foreground': '#8089b3',
      'sidebar-primary': '#7aa2f7',
      'sidebar-primary-foreground': '#1b1e2e',
      'sidebar-accent': '#292e42',
      'sidebar-accent-foreground': '#a9b1d6',
      'sidebar-border': '#1b1e2e',
      'sidebar-ring': '#7aa2f7',
      'plugin-accent': '#bb9af7',
      'plugin-active': '#292e42',
      'plugin-active-foreground': '#c0caf5',
      'plugin-active-icon': '#73daca',
      'plugin-active-border': '#3d59a1',
    },
    syntax: {
      comment: '#565f89',
      text: '#a9b1d6',
      keyword: '#bb9af7',
      variable: '#c0caf5',
      annotation: '#9abdf5',
      constant: '#ff9e64',
      tag: '#f7768e',
      string: '#9ece6a',
      interpolated: '#73daca',
      number: '#ff9e64',
      function: '#7aa2f7',
      support: '#2ac3de',
      misc: '#7dcfff',
      invalid: '#db4b4b',
    },
  },
} satisfies Record<TokyoNightThemeId, ThemeSeed>;

export const tokyoNightThemes = Object.fromEntries(
  Object.entries(tokyoNightThemeSeeds).map(([id, theme]) => [
    id,
    {
      id,
      label: theme.label,
      family: 'Tokyo Night',
      mode: theme.mode,
      swatches: theme.swatches,
      variables: theme.variables,
      syntax: createSyntaxHighlighterStyle(theme),
    },
  ]),
) as Record<TokyoNightThemeId, AppTheme>;
