import { createSyntaxHighlighterStyle, type AppTheme, type ThemeSeed, type VisualStudioCppThemeId } from './types';

const visualStudioCppThemeSeeds = {
  'vs-cpp-light': {
    label: 'Light (Visual Studio - C/C++)',
    mode: 'light',
    swatches: ['#ffffff', '#007acc', '#2b91af', '#8f08c4'],
    variables: {
      background: '#ffffff',
      foreground: '#1e1e1e',
      card: '#f3f3f3',
      'card-foreground': '#1e1e1e',
      popover: '#f3f3f3',
      'popover-foreground': '#1e1e1e',
      primary: '#007acc',
      'primary-foreground': '#ffffff',
      secondary: '#e5ebf1',
      'secondary-foreground': '#1e1e1e',
      muted: '#eeeeee',
      'muted-foreground': '#686868',
      accent: '#e5f3ff',
      'accent-foreground': '#005a9e',
      destructive: '#c72e0f',
      border: '#d6d6d6',
      input: '#cecece',
      ring: '#90c2f9',
      'chart-1': '#007acc',
      'chart-2': '#008000',
      'chart-3': '#8f08c4',
      'chart-4': '#74531f',
      'chart-5': '#a31515',
      sidebar: '#f3f3f3',
      'sidebar-foreground': '#333333',
      'sidebar-primary': '#007acc',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#e5ebf1',
      'sidebar-accent-foreground': '#005a9e',
      'sidebar-border': '#d6d6d6',
      'sidebar-ring': '#90c2f9',
      'plugin-accent': '#8f08c4',
      'plugin-active': '#e5f3ff',
      'plugin-active-foreground': '#1f377f',
      'plugin-active-icon': '#007acc',
      'plugin-active-border': '#90c2f9',
    },
    syntax: {
      comment: '#008000',
      text: '#000000',
      keyword: '#8f08c4',
      variable: '#1f377f',
      annotation: '#808080',
      constant: '#0070c1',
      tag: '#800000',
      string: '#a31515',
      interpolated: '#0000ff',
      number: '#098658',
      function: '#74531f',
      support: '#2b91af',
      misc: '#0451a5',
      invalid: '#cd3131',
    },
  },
  'vs-cpp-dark': {
    label: 'Dark (Visual Studio - C/C++)',
    mode: 'dark',
    swatches: ['#1e1e1e', '#007acc', '#4ec9b0', '#d8a0df'],
    variables: {
      background: '#1e1e1e',
      foreground: '#dadada',
      card: '#252526',
      'card-foreground': '#dadada',
      popover: '#303031',
      'popover-foreground': '#cccccc',
      primary: '#007acc',
      'primary-foreground': '#ffffff',
      secondary: '#2d2d30',
      'secondary-foreground': '#cccccc',
      muted: '#2d2d30',
      'muted-foreground': '#a9a8a7',
      accent: '#094771',
      'accent-foreground': '#ffffff',
      destructive: '#f44747',
      border: '#3f3f46',
      input: '#3f3f46',
      ring: '#569cd6',
      'chart-1': '#569cd6',
      'chart-2': '#57a64a',
      'chart-3': '#d8a0df',
      'chart-4': '#dcdcaa',
      'chart-5': '#ce9178',
      sidebar: '#252526',
      'sidebar-foreground': '#cccccc',
      'sidebar-primary': '#007acc',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#37373d',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#3f3f46',
      'sidebar-ring': '#569cd6',
      'plugin-accent': '#d8a0df',
      'plugin-active': '#094771',
      'plugin-active-foreground': '#ffffff',
      'plugin-active-icon': '#4ec9b0',
      'plugin-active-border': '#569cd6',
    },
    syntax: {
      comment: '#57a64a',
      text: '#dadada',
      keyword: '#d8a0df',
      variable: '#9cdcfe',
      annotation: '#9a9a9a',
      constant: '#4fc1ff',
      tag: '#569cd6',
      string: '#ce9178',
      interpolated: '#569cd6',
      number: '#b5cea8',
      function: '#dcdcaa',
      support: '#4ec9b0',
      misc: '#9cdcfe',
      invalid: '#f44747',
    },
  },
  'vs-cpp-2017-light': {
    label: '2017 Light (Visual Studio - C/C++)',
    mode: 'light',
    swatches: ['#ffffff', '#007acc', '#2b91af', '#0000ff'],
    variables: {
      background: '#ffffff',
      foreground: '#000000',
      card: '#f3f3f3',
      'card-foreground': '#000000',
      popover: '#f3f3f3',
      'popover-foreground': '#000000',
      primary: '#007acc',
      'primary-foreground': '#ffffff',
      secondary: '#e5ebf1',
      'secondary-foreground': '#000000',
      muted: '#eeeeee',
      'muted-foreground': '#767676',
      accent: '#e5f3ff',
      'accent-foreground': '#0451a5',
      destructive: '#cd3131',
      border: '#d3d3d3',
      input: '#cecece',
      ring: '#90c2f9',
      'chart-1': '#007acc',
      'chart-2': '#008000',
      'chart-3': '#2b91af',
      'chart-4': '#bd63c5',
      'chart-5': '#a31515',
      sidebar: '#f3f3f3',
      'sidebar-foreground': '#6f6f6f',
      'sidebar-primary': '#007acc',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#e8e8e8',
      'sidebar-accent-foreground': '#0451a5',
      'sidebar-border': '#d3d3d3',
      'sidebar-ring': '#90c2f9',
      'plugin-accent': '#bd63c5',
      'plugin-active': '#e5f3ff',
      'plugin-active-foreground': '#0000ff',
      'plugin-active-icon': '#2b91af',
      'plugin-active-border': '#90c2f9',
    },
    syntax: {
      comment: '#008000',
      text: '#000000',
      keyword: '#0000ff',
      variable: '#000000',
      annotation: '#808080',
      constant: '#2f4f4f',
      tag: '#800000',
      string: '#a31515',
      interpolated: '#0000ff',
      number: '#098658',
      function: '#000000',
      support: '#2b91af',
      misc: '#0451a5',
      invalid: '#cd3131',
    },
  },
  'vs-cpp-2017-dark': {
    label: '2017 Dark (Visual Studio - C/C++)',
    mode: 'dark',
    swatches: ['#1e1e1e', '#007acc', '#4ec9b0', '#569cd6'],
    variables: {
      background: '#1e1e1e',
      foreground: '#d4d4d4',
      card: '#252526',
      'card-foreground': '#d4d4d4',
      popover: '#303031',
      'popover-foreground': '#cccccc',
      primary: '#007acc',
      'primary-foreground': '#ffffff',
      secondary: '#2d2d30',
      'secondary-foreground': '#d4d4d4',
      muted: '#2d2d30',
      'muted-foreground': '#a6a6a6',
      accent: '#094771',
      'accent-foreground': '#ffffff',
      destructive: '#f44747',
      border: '#404040',
      input: '#3a3d41',
      ring: '#569cd6',
      'chart-1': '#569cd6',
      'chart-2': '#6a9955',
      'chart-3': '#4ec9b0',
      'chart-4': '#d69d85',
      'chart-5': '#ce9178',
      sidebar: '#252526',
      'sidebar-foreground': '#bbbbbb',
      'sidebar-primary': '#007acc',
      'sidebar-primary-foreground': '#ffffff',
      'sidebar-accent': '#37373d',
      'sidebar-accent-foreground': '#ffffff',
      'sidebar-border': '#404040',
      'sidebar-ring': '#569cd6',
      'plugin-accent': '#4ec9b0',
      'plugin-active': '#094771',
      'plugin-active-foreground': '#ffffff',
      'plugin-active-icon': '#9cdcfe',
      'plugin-active-border': '#569cd6',
    },
    syntax: {
      comment: '#6a9955',
      text: '#d4d4d4',
      keyword: '#569cd6',
      variable: '#c8c8c8',
      annotation: '#9b9b9b',
      constant: '#b8d7a3',
      tag: '#569cd6',
      string: '#ce9178',
      interpolated: '#569cd6',
      number: '#b5cea8',
      function: '#c8c8c8',
      support: '#4ec9b0',
      misc: '#9cdcfe',
      invalid: '#f44747',
    },
  },
} satisfies Record<VisualStudioCppThemeId, ThemeSeed>;

export const visualStudioCppThemes = Object.fromEntries(
  Object.entries(visualStudioCppThemeSeeds).map(([id, theme]) => [
    id,
    {
      id,
      label: theme.label,
      family: 'Visual Studio C/C++',
      mode: theme.mode,
      swatches: theme.swatches,
      variables: theme.variables,
      syntax: createSyntaxHighlighterStyle(theme),
    },
  ]),
) as Record<VisualStudioCppThemeId, AppTheme>;
