export type ShaderPreset = {
  name: string;
  filename: string;
  description: string;
  source: string;
};

const header = `// Generated by Feather Particle System Playground
// LÖVE pixel shader for particle systems.
`;

export const SHADER_PRESETS: ShaderPreset[] = [
  {
    name: 'Default Test Shader',
    filename: 'default-test-shader.glsl',
    description: 'Obvious animated tint shader for verifying shader compile, apply, and u_time.',
    source: `${header}
extern number u_time;

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float pulse = 0.65 + 0.35 * sin(u_time * 4.0);
  vec3 tint = mix(vec3(0.25, 0.75, 1.0), vec3(1.0, 0.25, 0.85), pulse);
  return vec4(px.rgb * tint * 1.8, px.a);
}
`,
  },
  {
    name: 'Clean Alpha',
    filename: 'clean-alpha.glsl',
    description: 'Neutral passthrough shader. Good reset point before custom edits.',
    source: `${header}
vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords);
  return px * color;
}
`,
  },
  {
    name: 'Soft Glow',
    filename: 'soft-glow.glsl',
    description: 'Boosts bright particles and feathered edges for fire, magic, and sparks.',
    source: `${header}
vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float alpha = smoothstep(0.02, 0.85, px.a);
  vec3 glow = px.rgb * (1.0 + alpha * 1.35);
  return vec4(glow, px.a * alpha);
}
`,
  },
  {
    name: 'Ember Heat',
    filename: 'ember-heat.glsl',
    description: 'Warm animated flicker for embers, flames, and explosions.',
    source: `${header}
extern number u_time;

float hash(vec2 p) {
  return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float n = hash(floor(texture_coords * 18.0 + u_time * 9.0));
  float heat = 0.85 + n * 0.45;
  vec3 warm = vec3(px.r * 1.35, px.g * 0.82, px.b * 0.35);
  return vec4(mix(px.rgb, warm, 0.65) * heat, px.a);
}
`,
  },
  {
    name: 'Smoke Softener',
    filename: 'smoke-softener.glsl',
    description: 'Desaturates and softens alpha for smoke, mist, and dust.',
    source: `${header}
vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float gray = dot(px.rgb, vec3(0.299, 0.587, 0.114));
  vec3 smoke = mix(vec3(gray), px.rgb, 0.18);
  float alpha = smoothstep(0.05, 0.95, px.a) * 0.72;
  return vec4(smoke, px.a * alpha);
}
`,
  },
  {
    name: 'Sparkle Pulse',
    filename: 'sparkle-pulse.glsl',
    description: 'Time-based shimmer for stars, glitter, and magical sparks.',
    source: `${header}
extern number u_time;

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  vec2 centered = texture_coords - vec2(0.5);
  float ray = abs(centered.x * centered.y) * 18.0;
  float pulse = 0.75 + 0.45 * sin(u_time * 9.0 + (texture_coords.x + texture_coords.y) * 18.0);
  vec3 tint = mix(px.rgb, vec3(1.0, 0.92, 0.45), 0.45);
  return vec4(tint * (pulse + ray), px.a);
}
`,
  },
  {
    name: 'Magic Chromatic',
    filename: 'magic-chromatic.glsl',
    description: 'Hue-split magical tint with subtle animated color cycling.',
    source: `${header}
extern number u_time;

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  vec3 cycle = 0.65 + 0.35 * cos(vec3(0.0, 2.1, 4.2) + u_time * 2.4 + texture_coords.xyx * 5.0);
  vec3 magic = mix(px.rgb, cycle, 0.55);
  return vec4(magic * (1.0 + px.a * 0.6), px.a);
}
`,
  },
  {
    name: 'Dissolve Noise',
    filename: 'dissolve-noise.glsl',
    description: 'Noisy broken edges for sparks, ash, teleport effects, and debris.',
    source: `${header}
extern number u_time;

float hash(vec2 p) {
  return fract(sin(dot(p, vec2(41.0, 289.0))) * 45758.5453);
}

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float n = hash(floor(texture_coords * 28.0 + u_time * 5.0));
  float edge = smoothstep(0.18, 0.62, n + px.a * 0.75);
  return vec4(px.rgb * (0.9 + n * 0.5), px.a * edge);
}
`,
  },
  {
    name: 'Radial Ring',
    filename: 'radial-ring.glsl',
    description: 'Turns soft blobs into ring-like pulses and shockwave particles.',
    source: `${header}
vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float d = distance(texture_coords, vec2(0.5));
  float ring = smoothstep(0.46, 0.34, abs(d - 0.33));
  float core = smoothstep(0.5, 0.1, d) * 0.2;
  return vec4(px.rgb * (1.0 + ring * 1.8), px.a * max(ring, core));
}
`,
  },
  {
    name: 'Energy Core',
    filename: 'energy-core.glsl',
    description: 'Bright center with colored falloff for plasma, portals, and beams.',
    source: `${header}
vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec4 px = Texel(tex, texture_coords) * color;
  float d = distance(texture_coords, vec2(0.5));
  float core = smoothstep(0.42, 0.0, d);
  vec3 energy = mix(px.rgb, vec3(0.35, 0.9, 1.0), 0.55) + core * vec3(0.8, 0.9, 1.0);
  return vec4(energy, px.a * smoothstep(0.55, 0.08, d));
}
`,
  },
].sort((a, b) => a.name.localeCompare(b.name));
