import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import {
  fetchManifest,
  getLocalPluginIds,
  getPluginIds,
  installCore,
  installCoreFromLocal,
  installPlugin,
  installPluginsFromLocal,
  normalizeInstallDir,
} from '../lib/install.js';
import { configTemplate, luaKey, luaValue } from '../lib/config.js';
import { chooseInitMode, type InitMode, type InitSetup } from '../ui/init-mode.js';
import { pluginCatalog } from '../generated/plugin-catalog.js';
import { resolveLocalLuaRoot } from '../lib/paths.js';
import { fail } from '../lib/command.js';
import { createSpinner, icon, style } from '../lib/output.js';

export interface InitOptions {
  branch?: string;
  remote?: boolean;
  localSrc?: string;
  noPlugins?: boolean;
  plugins?: string[];
  installDir?: string;
  yes?: boolean;
  mode?: InitMode;
}

const knownPlugins = pluginCatalog.map((plugin) => plugin.id);

const toLocalName = (id: string) =>
  id
    .split(/[-.]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

function toLuaModule(installDir = 'feather'): string {
  return normalizeInstallDir(installDir).replace(/\//g, '.');
}

function patchMainLua(mainPath: string, installDir = 'feather'): boolean {
  const src = readFileSync(mainPath, 'utf8');
  const luaModule = toLuaModule(installDir);
  if (src.includes('FEATHER-INIT-BEGIN require') || src.includes(`${luaModule}.auto`)) return false;

  const patch = `\n-- FEATHER-INIT-BEGIN require\n-- Feather debugger (https://github.com/Kyonru/feather)\n-- Set USE_DEBUGGER=1 to load Feather for local/dev runs.\nlocal featherUseDebugger = os.getenv("USE_DEBUGGER")\nif featherUseDebugger and featherUseDebugger ~= "0" and featherUseDebugger:lower() ~= "false" then\n  require("${luaModule}.auto")\nend\n-- FEATHER-INIT-END require\n`;
  const updatePatch = `\n  -- FEATHER-INIT update\n  if DEBUGGER then DEBUGGER:update(dt) end`;

  let out = patch + src;

  if (!out.includes('FEATHER-INIT update')) {
    out = out.replace(/function love\.update\s*\((\w+)\)\s*\n/, `function love.update($1)\n${updatePatch}\n`);
  }

  writeFileSync(mainPath, out);
  return true;
}

function patchMainLuaForManual(mainPath: string): boolean {
  const src = readFileSync(mainPath, 'utf8');
  if (src.includes('FEATHER-INIT-BEGIN require') || src.includes('feather.debugger.lua')) return false;

  const patch = `\n-- FEATHER-INIT-BEGIN require\n-- Loads the Feather manual debugger entrypoint generated by feather init.\n-- Set USE_DEBUGGER=1 to load Feather for local/dev runs.\n-- This uses love.filesystem.load because Lua require maps dots to folders.\nlocal featherUseDebugger = os.getenv("USE_DEBUGGER")\nif featherUseDebugger and featherUseDebugger ~= "0" and featherUseDebugger:lower() ~= "false" then\n  local featherDebuggerChunk = assert(love.filesystem.load("feather.debugger.lua"))\n  featherDebuggerChunk()\nend\n-- FEATHER-INIT-END require\n`;
  const updatePatch = `\n  -- FEATHER-INIT update\n  if DEBUGGER then DEBUGGER:update(dt) end`;

  let out = patch + src;
  if (!out.includes('FEATHER-INIT update')) {
    out = out.replace(/function love\.update\s*\((\w+)\)\s*\n/, `function love.update($1)\n${updatePatch}\n`);
  }

  writeFileSync(mainPath, out);
  return true;
}

export async function initCommand(dir: string, opts: InitOptions): Promise<void> {
  const target = resolve(dir);

  if (!existsSync(join(target, 'main.lua'))) {
    fail(`No main.lua found in ${target}. Is this a love2d project?`);
  }

  const setup: InitSetup =
    !opts.yes && process.stdin.isTTY
      ? await chooseInitMode(opts.mode ?? 'auto', basename(target), opts.branch ?? 'main', opts.installDir ?? 'feather')
      : {
          mode: opts.mode ?? 'auto',
          source: opts.remote ? 'remote' : 'local',
          branch: opts.branch ?? 'main',
          installDir: opts.installDir ?? 'feather',
          installPlugins: opts.noPlugins ? false : true,
          config: {},
          exclude: [],
        };
  const mode = setup.mode;
  const installDir = normalizeInstallDir(setup.installDir);
  const pluginsDisabled = opts.noPlugins || setup.installPlugins === false;
  const alreadyInstalled = existsSync(join(target, installDir, 'init.lua'));
  const useRemote = opts.remote === true || setup.source === 'remote';

  if (mode === 'cli') {
    writeConfig(target, setup.config, {
      mode,
      installDir,
      source: useRemote ? `github:${setup.branch || opts.branch || 'main'}` : 'local',
    });
    console.log(`\n${style.heading('Done!')} Run this project through Feather CLI.\n`);
    console.log(style.muted(`  feather run ${dir}`));
    console.log(style.muted('  Use `--config <path>` if feather.config.lua lives elsewhere.\n'));
    return;
  }

  if (alreadyInstalled) {
    console.log(style.warning('Feather is already installed in this project.'));
    console.log(style.muted('Run `feather update` to update to the latest version.'));
  }

  const branch = setup.branch || opts.branch || 'main';
  let entries: Awaited<ReturnType<typeof fetchManifest>> = [];
  let installedPluginIds: string[] = [];

  if (!alreadyInstalled) {
    if (useRemote) {
      const spinner = createSpinner('Fetching manifest…').start();

      try {
        entries = await fetchManifest(branch);
        spinner.succeed(`Manifest loaded (${entries.length} files)`);
      } catch (err) {
        spinner.fail(`Could not fetch manifest: ${(err as Error).message}`);
        fail((err as Error).message, { cause: err, silent: true });
      }

      const coreSpinner = createSpinner('Installing feather core from GitHub…').start();
      try {
        await installCore(entries, target, branch, (f) => {
          coreSpinner.text = `Installing ${f}…`;
        }, installDir);
        coreSpinner.succeed('Feather core installed');
      } catch (err) {
        coreSpinner.fail(`Core install failed: ${(err as Error).message}`);
        fail((err as Error).message, { cause: err, silent: true });
      }

      if (!pluginsDisabled) {
        const excluded = new Set(setup.exclude);
        const pluginIds = (opts.plugins ?? getPluginIds(entries)).filter((id) => !excluded.has(id));
        installedPluginIds = pluginIds;
        const pluginSpinner = createSpinner(`Installing ${pluginIds.length} plugins from GitHub…`).start();
        let failed = 0;
        for (const id of pluginIds) {
          try {
            await installPlugin(id, entries, target, branch, undefined, installDir);
            pluginSpinner.text = `Installed plugin: ${id}`;
          } catch {
            failed++;
          }
        }
        pluginSpinner.succeed(`Plugins installed${failed > 0 ? style.warning(` (${failed} failed)`) : ''}`);
      }
    } else {
      const sourceRoot = resolveLocalLuaRoot(opts);
      const coreSpinner = createSpinner(`Copying feather core from ${sourceRoot}…`).start();
      try {
        installCoreFromLocal(sourceRoot, target, installDir, (f) => {
          coreSpinner.text = `Copying ${f}…`;
        });
        coreSpinner.succeed('Feather core installed');
      } catch (err) {
        coreSpinner.fail(`Core install failed: ${(err as Error).message}`);
        fail((err as Error).message, { cause: err, silent: true });
      }

      if (!pluginsDisabled) {
        const excluded = new Set(setup.exclude);
        const pluginIds = (opts.plugins ?? getLocalPluginIds(sourceRoot)).filter((id) => !excluded.has(id));
        installedPluginIds = pluginIds;
        const pluginSpinner = createSpinner(`Copying ${pluginIds.length} plugins…`).start();
        let failed = 0;
        for (const id of pluginIds) {
          try {
            installPluginsFromLocal([id], sourceRoot, target, installDir);
            pluginSpinner.text = `Copied plugin: ${id}`;
          } catch {
            failed++;
          }
        }
        pluginSpinner.succeed(`Plugins installed${failed > 0 ? style.warning(` (${failed} failed)`) : ''}`);
      }
    }
  }

  const mainPath = join(target, 'main.lua');

  if (mode === 'auto') {
    const patched = patchMainLua(mainPath, installDir);
    if (patched) {
      console.log(`${icon.success} Patched main.lua with feather.auto require`);
    } else {
      console.log(style.muted('  main.lua already references feather — skipped patch'));
    }
  } else if (mode === 'manual') {
    const pluginIds =
      installedPluginIds.length > 0
        ? installedPluginIds
        : pluginsDisabled
          ? []
          : (opts.plugins ?? knownPlugins).filter((id) => !setup.exclude.includes(id));
    const created = writeManualDebugger(target, setup.config, pluginIds, installDir);
    const patched = patchMainLuaForManual(mainPath);

    if (created) {
      console.log(`${icon.success} Created feather.debugger.lua`);
    } else {
      console.log(style.muted('  feather.debugger.lua already exists — skipped'));
    }

    if (patched) {
      console.log(`${icon.success} Patched main.lua with feather.debugger.lua loader`);
    } else {
      console.log(style.muted('  main.lua already references Feather — skipped patch'));
    }
  }

  writeConfig(target, setup.config, {
    mode,
    installDir,
    source: useRemote ? `github:${branch}` : 'local',
    manualEntrypoint: mode === 'manual' ? 'feather.debugger.lua' : undefined,
  });

  console.log(`\n${style.heading('Done!')} Start the Feather desktop app, then run your game.\n`);

  if (mode === 'manual') {
    console.log(style.muted('  Manual setup lives in feather.debugger.lua and is loaded from main.lua.\n'));
  } else {
    console.log(style.muted('  Tip: use `feather run .` to inject without touching game code.\n'));
  }
}

function writeConfig(
  target: string,
  config: Record<string, unknown> = {},
  context: { mode?: string; installDir?: string; source?: string; manualEntrypoint?: string } = {},
): void {
  const configPath = join(target, 'feather.config.lua');
  if (!existsSync(configPath)) {
    writeFileSync(configPath, configTemplate(config, context));
    console.log(`${icon.success} Created feather.config.lua`);
  } else {
    console.log(style.muted('  feather.config.lua already exists — skipped'));
  }
}

function writeManualDebugger(target: string, config: Record<string, unknown>, pluginIds: string[], installDir: string): boolean {
  const manualPath = join(target, 'feather.debugger.lua');
  if (existsSync(manualPath)) return false;
  writeFileSync(manualPath, buildManualDebuggerFile(config, pluginIds, installDir));
  return true;
}

function buildManualDebuggerFile(config: Record<string, unknown>, pluginIds: string[], installDir = 'feather'): string {
  const luaModule = toLuaModule(installDir);
  const manualConfig: Record<string, unknown> = { debug: true, ...config };
  const lines: string[] = [
    '-- feather.debugger.lua',
    '-- Generated by feather init --mode manual.',
    '--',
    '-- FEATHER-MANAGED-BEGIN',
    '-- This file is safe for a future `feather remove` command to delete.',
    '-- Main.lua contains a matching FEATHER-INIT loader block and update hook.',
    '-- Feather is loaded only when USE_DEBUGGER is set to a truthy value.',
    `-- installDir: ${normalizeInstallDir(installDir)}`,
    `-- luaModule: ${luaModule}`,
    '-- FEATHER-MANAGED-END',
    '',
    'local featherUseDebugger = os.getenv("USE_DEBUGGER")',
    'if not (featherUseDebugger and featherUseDebugger ~= "0" and featherUseDebugger:lower() ~= "false") then',
    '  return nil',
    'end',
    '',
    'if DEBUGGER then',
    '  return DEBUGGER',
    'end',
    '',
    `local FeatherDebugger = require("${luaModule}")`,
    `local FeatherPluginManager = require("${luaModule}.plugin_manager")`,
  ];

  for (const id of pluginIds) {
    lines.push(`local ${toLocalName(id)}Plugin = require("${luaModule}.plugins.${id}")`);
  }

  lines.push('', 'DEBUGGER = FeatherDebugger({');

  const configEntries = Object.entries(manualConfig).filter(
    ([key]) => key !== 'include' && key !== 'exclude' && key !== 'pluginOptions',
  );
  for (const [key, value] of configEntries) {
    lines.push(`  ${luaKey(key)} = ${luaValue(value, 2)},`);
  }

  if (pluginIds.length > 0) {
    const pluginOptions = (manualConfig.pluginOptions && typeof manualConfig.pluginOptions === 'object'
      ? (manualConfig.pluginOptions as Record<string, unknown>)
      : {}) as Record<string, unknown>;

    lines.push('  plugins = {');
    for (const id of pluginIds) {
      const options = pluginOptions[id] ?? {};
      lines.push(`    FeatherPluginManager.createPlugin(${toLocalName(id)}Plugin, ${JSON.stringify(id)}, ${luaValue(options, 4)}),`);
    }
    lines.push('  },');
  } else {
    lines.push('  plugins = {},');
  }

  lines.push('})', '', 'return DEBUGGER');

  return lines.join('\n') + '\n';
}
