import type { CSSProperties } from 'react';
import featherDarkSyntax from './dark';
import featherLightSyntax from './light';

export const THEME_CSS_VARIABLES = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
  'plugin-accent',
  'plugin-active',
  'plugin-active-foreground',
  'plugin-active-icon',
  'plugin-active-border',
] as const;

export type ThemeCssVariable = (typeof THEME_CSS_VARIABLES)[number];
export type ThemeMode = 'light' | 'dark';
export type ThemeFamily = 'Feather' | 'Noctis';
export type ThemeId =
  | 'light'
  | 'dark'
  | 'noctis-lux'
  | 'noctis-hibernus'
  | 'noctis-lilac'
  | 'noctis'
  | 'noctis-azureus'
  | 'noctis-bordo'
  | 'noctis-obscuro'
  | 'noctis-sereno'
  | 'noctis-uva'
  | 'noctis-viola'
  | 'noctis-minimus';
export type ThemePreference = 'system' | ThemeId;
export type ThemeVariables = Record<ThemeCssVariable, string>;
export type SyntaxHighlighterStyle = Record<string, CSSProperties>;

export type AppTheme = {
  id: ThemeId;
  label: string;
  family: ThemeFamily;
  mode: ThemeMode;
  swatches: string[];
  variables: ThemeVariables;
  syntax: SyntaxHighlighterStyle;
};

type NoctisSyntaxPalette = {
  comment: string;
  text: string;
  keyword: string;
  variable: string;
  annotation: string;
  constant: string;
  tag: string;
  string: string;
  interpolated: string;
  number: string;
  function: string;
  support: string;
  misc: string;
  invalid: string;
};

type NoctisThemeSeed = {
  label: string;
  mode: ThemeMode;
  swatches: string[];
  variables: ThemeVariables;
  syntax: NoctisSyntaxPalette;
};

const featherLightVariables: ThemeVariables = {
  background: '#f0f4f8',
  foreground: '#403f53',
  card: '#f8fbff',
  'card-foreground': '#403f53',
  popover: '#f8fbff',
  'popover-foreground': '#403f53',
  primary: '#ad5b68',
  'primary-foreground': '#ffffff',
  secondary: '#e5ebf3',
  'secondary-foreground': '#403f53',
  muted: '#e5ebf3',
  'muted-foreground': '#6c6f85',
  accent: '#f3dfe4',
  'accent-foreground': '#873f4d',
  destructive: '#d3423e',
  border: '#d4dce8',
  input: '#c9d3e3',
  ring: '#ad5b68',
  'chart-1': '#ad5b68',
  'chart-2': '#0c969b',
  'chart-3': '#994cc3',
  'chart-4': '#c96765',
  'chart-5': '#d3423e',
  sidebar: '#e8eef6',
  'sidebar-foreground': '#403f53',
  'sidebar-primary': '#ad5b68',
  'sidebar-primary-foreground': '#ffffff',
  'sidebar-accent': '#f0dce3',
  'sidebar-accent-foreground': '#873f4d',
  'sidebar-border': '#d4dce8',
  'sidebar-ring': '#ad5b68',
  'plugin-accent': '#8a5a9f',
  'plugin-active': '#eee1f2',
  'plugin-active-foreground': '#563965',
  'plugin-active-icon': '#74498a',
  'plugin-active-border': '#d5bddf',
};

const featherDarkVariables: ThemeVariables = {
  background: '#0d1117',
  foreground: '#c9d1d9',
  card: '#161b22',
  'card-foreground': '#c9d1d9',
  popover: '#161b22',
  'popover-foreground': '#c9d1d9',
  primary: '#8b949e',
  'primary-foreground': '#0d1117',
  secondary: '#21262d',
  'secondary-foreground': '#c9d1d9',
  muted: '#21262d',
  'muted-foreground': '#8b949e',
  accent: '#30363d',
  'accent-foreground': '#c9d1d9',
  destructive: '#f85149',
  border: '#30363d',
  input: '#30363d',
  ring: '#8b949e',
  'chart-1': '#8b949e',
  'chart-2': '#3fb950',
  'chart-3': '#bc8cff',
  'chart-4': '#d29922',
  'chart-5': '#f85149',
  sidebar: '#161b22',
  'sidebar-foreground': '#c9d1d9',
  'sidebar-primary': '#8b949e',
  'sidebar-primary-foreground': '#0d1117',
  'sidebar-accent': '#21262d',
  'sidebar-accent-foreground': '#c9d1d9',
  'sidebar-border': '#30363d',
  'sidebar-ring': '#ff9aa2',
  'plugin-accent': '#c9a0dc',
  'plugin-active': '#31263a',
  'plugin-active-foreground': '#f1def8',
  'plugin-active-icon': '#dfb7f0',
  'plugin-active-border': '#7f4d94',
};

function createSyntaxHighlighterStyle(theme: NoctisThemeSeed): SyntaxHighlighterStyle {
  const { syntax, variables } = theme;

  return {
    'hljs-comment': { color: syntax.comment },
    'hljs-quote': { color: syntax.comment },
    'hljs-variable': { color: syntax.variable },
    'hljs-template-variable': { color: syntax.interpolated },
    'hljs-tag': { color: syntax.tag },
    'hljs-name': { color: syntax.tag },
    'hljs-selector-id': { color: syntax.variable },
    'hljs-selector-class': { color: syntax.variable },
    'hljs-regexp': { color: syntax.string },
    'hljs-deletion': { color: syntax.invalid },
    'hljs-number': { color: syntax.number },
    'hljs-built_in': { color: syntax.support },
    'hljs-builtin-name': { color: syntax.support },
    'hljs-literal': { color: syntax.number },
    'hljs-type': { color: syntax.annotation },
    'hljs-params': { color: syntax.text },
    'hljs-meta': { color: syntax.comment },
    'hljs-link': { color: syntax.misc },
    'hljs-attribute': { color: syntax.constant },
    'hljs-string': { color: syntax.string },
    'hljs-symbol': { color: syntax.string },
    'hljs-bullet': { color: syntax.string },
    'hljs-addition': { color: syntax.string },
    'hljs-title': { color: syntax.function },
    'hljs-section': { color: syntax.function },
    'hljs-keyword': { color: syntax.keyword },
    'hljs-selector-tag': { color: syntax.tag },
    hljs: {
      display: 'block',
      overflowX: 'auto',
      background: variables.background,
      color: syntax.text,
      padding: '0.5em',
    },
    'hljs-emphasis': { fontStyle: 'italic' },
    'hljs-strong': { fontWeight: 'bold' },
  };
}

const noctisThemeSeeds = {
  'noctis-lux': {
    label: 'Noctis Lux',
    mode: 'light',
    swatches: ['#fef8ec', '#099', '#00b368', '#ff5792'],
    variables: {
      background: '#fef8ec',
      foreground: '#005661',
      card: '#f9f1e1',
      'card-foreground': '#888477',
      popover: '#f2edde',
      'popover-foreground': '#6a7a7c',
      primary: '#099',
      'primary-foreground': '#f1f1f1',
      secondary: '#f2e7ca',
      'secondary-foreground': '#888477',
      muted: '#d1ebefcc',
      'muted-foreground': '#929ea0',
      accent: '#ade2eb77',
      'accent-foreground': '#0099ad',
      destructive: '#ff4000',
      border: '#f0e7d1',
      input: '#fef8ec',
      ring: '#f2edde',
      'chart-1': '#0095a8',
      'chart-2': '#00b368',
      'chart-3': '#5842ff',
      'chart-4': '#fa8900',
      'chart-5': '#ff5792',
      sidebar: '#f9f1e1',
      'sidebar-foreground': '#888477',
      'sidebar-primary': '#0099ad',
      'sidebar-primary-foreground': '#fef8ec',
      'sidebar-accent': '#f2e7ca',
      'sidebar-accent-foreground': '#0099ad',
      'sidebar-border': '#f0e7d1',
      'sidebar-ring': '#0099ad',
      'plugin-accent': '#5842ff',
      'plugin-active': '#d1ebefcc',
      'plugin-active-foreground': '#ff5792',
      'plugin-active-icon': '#00bdd6',
      'plugin-active-border': '#0094f0',
    },
    syntax: {
      comment: '#8ca6a6',
      text: '#004d57',
      keyword: '#ff5792',
      variable: '#fa8900',
      annotation: '#b3694d',
      constant: '#a88c00',
      tag: '#e64100',
      string: '#00b368',
      interpolated: '#009456',
      number: '#5842ff',
      function: '#0095a8',
      support: '#00bdd6',
      misc: '#0094f0',
      invalid: '#ff530f',
    },
  },
  'noctis-hibernus': {
    label: 'Noctis Hibernus',
    mode: 'light',
    swatches: ['#f4f6f6', '#099', '#00b368', '#ff5792'],
    variables: {
      background: '#f4f6f6',
      foreground: '#005661',
      card: '#e7f2f3',
      'card-foreground': '#71838e',
      popover: '#e0eff1',
      'popover-foreground': '#6a7a7c',
      primary: '#099',
      'primary-foreground': '#f1f1f1',
      secondary: '#c1def0',
      'secondary-foreground': '#71838e',
      muted: '#d1ebefcc',
      'muted-foreground': '#929ea0',
      accent: '#ade2eb77',
      'accent-foreground': '#0099ad',
      destructive: '#ff4000',
      border: '#d0edf1',
      input: '#f4f6f6',
      ring: '#e0eff1',
      'chart-1': '#0095a8',
      'chart-2': '#00b368',
      'chart-3': '#5842ff',
      'chart-4': '#fa8900',
      'chart-5': '#ff5792',
      sidebar: '#e7f2f3',
      'sidebar-foreground': '#71838e',
      'sidebar-primary': '#0099ad',
      'sidebar-primary-foreground': '#f4f6f6',
      'sidebar-accent': '#c1def0',
      'sidebar-accent-foreground': '#0099ad',
      'sidebar-border': '#d0edf1',
      'sidebar-ring': '#0099ad',
      'plugin-accent': '#5842ff',
      'plugin-active': '#d1ebefcc',
      'plugin-active-foreground': '#ff5792',
      'plugin-active-icon': '#00bdd6',
      'plugin-active-border': '#0094f0',
    },
    syntax: {
      comment: '#8ca6a6',
      text: '#004d57',
      keyword: '#ff5792',
      variable: '#fa8900',
      annotation: '#b3694d',
      constant: '#a88c00',
      tag: '#e64100',
      string: '#00b368',
      interpolated: '#009456',
      number: '#5842ff',
      function: '#0095a8',
      support: '#00bdd6',
      misc: '#0094f0',
      invalid: '#ff530f',
    },
  },
  'noctis-lilac': {
    label: 'Noctis Lilac',
    mode: 'light',
    swatches: ['#f2f1f8', '#8e80ff', '#00b368', '#ff5792'],
    variables: {
      background: '#f2f1f8',
      foreground: '#0c006b',
      card: '#edecf8',
      'card-foreground': '#75718e',
      popover: '#dedbf5',
      'popover-foreground': '#666284',
      primary: '#8e80ff',
      'primary-foreground': '#f1f1f1',
      secondary: '#dedbf5',
      'secondary-foreground': '#75718e',
      muted: '#d5d2ef99',
      'muted-foreground': '#908ea4',
      accent: '#b4adeb77',
      'accent-foreground': '#7060eb',
      destructive: '#ff4000',
      border: '#d4d0f1',
      input: '#f2f1f8',
      ring: '#dedbf5',
      'chart-1': '#0095a8',
      'chart-2': '#00b368',
      'chart-3': '#5842ff',
      'chart-4': '#fa8900',
      'chart-5': '#ff5792',
      sidebar: '#edecf8',
      'sidebar-foreground': '#75718e',
      'sidebar-primary': '#7060eb',
      'sidebar-primary-foreground': '#f2f1f8',
      'sidebar-accent': '#dedbf5',
      'sidebar-accent-foreground': '#7060eb',
      'sidebar-border': '#d4d0f1',
      'sidebar-ring': '#7060eb',
      'plugin-accent': '#5842ff',
      'plugin-active': '#d5d2ef99',
      'plugin-active-foreground': '#ff5792',
      'plugin-active-icon': '#00bdd6',
      'plugin-active-border': '#0094f0',
    },
    syntax: {
      comment: '#9995b7',
      text: '#0c006b',
      keyword: '#ff5792',
      variable: '#fa8900',
      annotation: '#b3694d',
      constant: '#a88c00',
      tag: '#e64100',
      string: '#00b368',
      interpolated: '#009456',
      number: '#5842ff',
      function: '#0095a8',
      support: '#00bdd6',
      misc: '#0094f0',
      invalid: '#ff530f',
    },
  },
  noctis: {
    label: 'Noctis',
    mode: 'dark',
    swatches: ['#052529', '#099', '#49e9a6', '#df769b'],
    variables: {
      background: '#052529',
      foreground: '#b2cacd',
      card: '#041d20',
      'card-foreground': '#a5b5b5',
      popover: '#073940',
      'popover-foreground': '#87a7ab',
      primary: '#099',
      'primary-foreground': '#ebfdff',
      secondary: '#083d44',
      'secondary-foreground': '#a5b5b5',
      muted: '#083d44ee',
      'muted-foreground': '#929ea0',
      accent: '#169fb144',
      'accent-foreground': '#40d4e7',
      destructive: '#e34e1c',
      border: '#0f1415',
      input: '#052529',
      ring: '#073940',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#041d20',
      'sidebar-foreground': '#a5b5b5',
      'sidebar-primary': '#40d4e7',
      'sidebar-primary-foreground': '#0f1415',
      'sidebar-accent': '#083d44',
      'sidebar-accent-foreground': '#40d4e7',
      'sidebar-border': '#0f1415',
      'sidebar-ring': '#40d4e7',
      'plugin-accent': '#7060eb',
      'plugin-active': '#083d44ee',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#5b858b',
      text: '#b2cacd',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-azureus': {
    label: 'Noctis Azureus',
    mode: 'dark',
    swatches: ['#07273b', '#007f99', '#49e9a6', '#df769b'],
    variables: {
      background: '#07273b',
      foreground: '#becfda',
      card: '#062132',
      'card-foreground': '#9fb6c6',
      popover: '#09334e',
      'popover-foreground': '#9fb6c6',
      primary: '#007f99',
      'primary-foreground': '#ebf7ff',
      secondary: '#09334e',
      'secondary-foreground': '#9fb6c6',
      muted: '#003c61ee',
      'muted-foreground': '#61a6d1',
      accent: '#1679b655',
      'accent-foreground': '#49ace9',
      destructive: '#e34e1c',
      border: '#0f1315',
      input: '#051b29',
      ring: '#09334e',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#062132',
      'sidebar-foreground': '#9fb6c6',
      'sidebar-primary': '#49ace9',
      'sidebar-primary-foreground': '#0f1315',
      'sidebar-accent': '#09334e',
      'sidebar-accent-foreground': '#49ace9',
      'sidebar-border': '#0f1315',
      'sidebar-ring': '#49ace9',
      'plugin-accent': '#7060eb',
      'plugin-active': '#003c61ee',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#5988a6',
      text: '#becfda',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-bordo': {
    label: 'Noctis Bordo',
    mode: 'dark',
    swatches: ['#322a2d', '#007f99', '#49e9a6', '#df769b'],
    variables: {
      background: '#322a2d',
      foreground: '#cbbec2',
      card: '#2c2528',
      'card-foreground': '#bbaab0',
      popover: '#413036',
      'popover-foreground': '#bbaab0',
      primary: '#007f99',
      'primary-foreground': '#edebff',
      secondary: '#413036',
      'secondary-foreground': '#bbaab0',
      muted: '#453138aa',
      'muted-foreground': '#bb778f',
      accent: '#99758255',
      'accent-foreground': '#f18eb0',
      destructive: '#e34e1c',
      border: '#1f191b',
      input: '#272022',
      ring: '#413036',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#2c2528',
      'sidebar-foreground': '#bbaab0',
      'sidebar-primary': '#f18eb0',
      'sidebar-primary-foreground': '#1f191b',
      'sidebar-accent': '#413036',
      'sidebar-accent-foreground': '#f18eb0',
      'sidebar-border': '#1f191b',
      'sidebar-ring': '#f18eb0',
      'plugin-accent': '#7060eb',
      'plugin-active': '#453138aa',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#8b747c',
      text: '#cbbec2',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-obscuro': {
    label: 'Noctis Obscuro',
    mode: 'dark',
    swatches: ['#031417', '#099', '#49e9a6', '#df769b'],
    variables: {
      background: '#031417',
      foreground: '#b2cacd',
      card: '#021012',
      'card-foreground': '#a5b5b5',
      popover: '#062e32',
      'popover-foreground': '#87a7ab',
      primary: '#099',
      'primary-foreground': '#ebfdff',
      secondary: '#083d44',
      'secondary-foreground': '#a5b5b5',
      muted: '#083d44ee',
      'muted-foreground': '#929ea0',
      accent: '#169fb144',
      'accent-foreground': '#40d4e7',
      destructive: '#e34e1c',
      border: '#000000',
      input: '#052529',
      ring: '#062e32',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#021012',
      'sidebar-foreground': '#a5b5b5',
      'sidebar-primary': '#40d4e7',
      'sidebar-primary-foreground': '#0f1415',
      'sidebar-accent': '#083d44',
      'sidebar-accent-foreground': '#40d4e7',
      'sidebar-border': '#000000',
      'sidebar-ring': '#40d4e7',
      'plugin-accent': '#7060eb',
      'plugin-active': '#083d44ee',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#5b858b',
      text: '#b2cacd',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-sereno': {
    label: 'Noctis Sereno',
    mode: 'dark',
    swatches: ['#062e32', '#099', '#49e9a6', '#df769b'],
    variables: {
      background: '#062e32',
      foreground: '#b2cacd',
      card: '#052629',
      'card-foreground': '#a5b5b5',
      popover: '#083d44',
      'popover-foreground': '#87a7ab',
      primary: '#099',
      'primary-foreground': '#ebfdff',
      secondary: '#083d44',
      'secondary-foreground': '#a5b5b5',
      muted: '#083d44ee',
      'muted-foreground': '#929ea0',
      accent: '#169fb144',
      'accent-foreground': '#40d4e7',
      destructive: '#e34e1c',
      border: '#0f1415',
      input: '#062e32',
      ring: '#083d44',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#052629',
      'sidebar-foreground': '#a5b5b5',
      'sidebar-primary': '#40d4e7',
      'sidebar-primary-foreground': '#0f1415',
      'sidebar-accent': '#083d44',
      'sidebar-accent-foreground': '#40d4e7',
      'sidebar-border': '#0f1415',
      'sidebar-ring': '#40d4e7',
      'plugin-accent': '#7060eb',
      'plugin-active': '#083d44ee',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#5b858b',
      text: '#b2cacd',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-uva': {
    label: 'Noctis Uva',
    mode: 'dark',
    swatches: ['#292640', '#007f99', '#49e9a6', '#df769b'],
    variables: {
      background: '#292640',
      foreground: '#c5c2d6',
      card: '#232136',
      'card-foreground': '#a9a5c0',
      popover: '#2f2c49',
      'popover-foreground': '#a9a5c0',
      primary: '#007f99',
      'primary-foreground': '#edebff',
      secondary: '#2f2c49',
      'secondary-foreground': '#a9a5c0',
      muted: '#35305aee',
      'muted-foreground': '#7a70c2',
      accent: '#6e67a855',
      'accent-foreground': '#998ef1',
      destructive: '#e34e1c',
      border: '#171523',
      input: '#1f1d30',
      ring: '#2f2c49',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#232136',
      'sidebar-foreground': '#a9a5c0',
      'sidebar-primary': '#998ef1',
      'sidebar-primary-foreground': '#171523',
      'sidebar-accent': '#2f2c49',
      'sidebar-accent-foreground': '#998ef1',
      'sidebar-border': '#171523',
      'sidebar-ring': '#998ef1',
      'plugin-accent': '#7060eb',
      'plugin-active': '#35305aee',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#716c93',
      text: '#c5c2d6',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-viola': {
    label: 'Noctis Viola',
    mode: 'dark',
    swatches: ['#30243d', '#007f99', '#49e9a6', '#df769b'],
    variables: {
      background: '#30243d',
      foreground: '#ccbfd9',
      card: '#2b2136',
      'card-foreground': '#b3a5c0',
      popover: '#3d2e4d',
      'popover-foreground': '#b3a5c0',
      primary: '#007f99',
      'primary-foreground': '#edebff',
      secondary: '#3d2e4d',
      'secondary-foreground': '#b3a5c0',
      muted: '#402d53ee',
      'muted-foreground': '#996bc7',
      accent: '#8767a855',
      'accent-foreground': '#bf8ef1',
      destructive: '#e34e1c',
      border: '#1c1226',
      input: '#291d35',
      ring: '#3d2e4d',
      'chart-1': '#16a3b6',
      'chart-2': '#49e9a6',
      'chart-3': '#7060eb',
      'chart-4': '#e4b781',
      'chart-5': '#df769b',
      sidebar: '#2b2136',
      'sidebar-foreground': '#b3a5c0',
      'sidebar-primary': '#bf8ef1',
      'sidebar-primary-foreground': '#1c1226',
      'sidebar-accent': '#3d2e4d',
      'sidebar-accent-foreground': '#bf8ef1',
      'sidebar-border': '#1c1226',
      'sidebar-ring': '#bf8ef1',
      'plugin-accent': '#7060eb',
      'plugin-active': '#402d53ee',
      'plugin-active-foreground': '#df769b',
      'plugin-active-icon': '#49d6e9',
      'plugin-active-border': '#49ace9',
    },
    syntax: {
      comment: '#7f659a',
      text: '#ccbfd9',
      keyword: '#df769b',
      variable: '#e4b781',
      annotation: '#d67e5c',
      constant: '#d5971a',
      tag: '#e66533',
      string: '#49e9a6',
      interpolated: '#16b673',
      number: '#7060eb',
      function: '#16a3b6',
      support: '#49d6e9',
      misc: '#49ace9',
      invalid: '#e3541c',
    },
  },
  'noctis-minimus': {
    label: 'Noctis Minimus',
    mode: 'dark',
    swatches: ['#1b2932', '#2e616b', '#72c09f', '#c88da2'],
    variables: {
      background: '#1b2932',
      foreground: '#c5cdd3',
      card: '#17232b',
      'card-foreground': '#96a8b6',
      popover: '#202e37',
      'popover-foreground': '#96a8b6',
      primary: '#2e616b',
      'primary-foreground': '#ebf7ff',
      secondary: '#202e37',
      'secondary-foreground': '#96a8b6',
      muted: '#1d3544ee',
      'muted-foreground': '#6496b4',
      accent: '#496d8355',
      'accent-foreground': '#5998c0',
      destructive: '#b96346',
      border: '#101213',
      input: '#0e1920',
      ring: '#202e37',
      'chart-1': '#3f848d',
      'chart-2': '#72c09f',
      'chart-3': '#7068b1',
      'chart-4': '#d3b692',
      'chart-5': '#c88da2',
      sidebar: '#17232b',
      'sidebar-foreground': '#96a8b6',
      'sidebar-primary': '#5998c0',
      'sidebar-primary-foreground': '#101213',
      'sidebar-accent': '#202e37',
      'sidebar-accent-foreground': '#5998c0',
      'sidebar-border': '#101213',
      'sidebar-ring': '#5998c0',
      'plugin-accent': '#7068b1',
      'plugin-active': '#1d3544ee',
      'plugin-active-foreground': '#c88da2',
      'plugin-active-icon': '#72b7c0',
      'plugin-active-border': '#5998c0',
    },
    syntax: {
      comment: '#5e7887',
      text: '#c5cdd3',
      keyword: '#c88da2',
      variable: '#d3b692',
      annotation: '#be856f',
      constant: '#a88c00',
      tag: '#c37455',
      string: '#72c09f',
      interpolated: '#3f8d6c',
      number: '#7068b1',
      function: '#3f848d',
      support: '#72b7c0',
      misc: '#5998c0',
      invalid: '#b16a4e',
    },
  },
} satisfies Record<Exclude<ThemeId, 'light' | 'dark'>, NoctisThemeSeed>;

const noctisThemes = Object.fromEntries(
  Object.entries(noctisThemeSeeds).map(([id, theme]) => [
    id,
    {
      id,
      label: theme.label,
      family: 'Noctis',
      mode: theme.mode,
      swatches: theme.swatches,
      variables: theme.variables,
      syntax: createSyntaxHighlighterStyle(theme),
    },
  ]),
) as Record<Exclude<ThemeId, 'light' | 'dark'>, AppTheme>;

export const appThemes: Record<ThemeId, AppTheme> = {
  light: {
    id: 'light',
    label: 'Feather Light',
    family: 'Feather',
    mode: 'light',
    swatches: ['#f0f4f8', '#ad5b68', '#0c969b', '#994cc3'],
    variables: featherLightVariables,
    syntax: featherLightSyntax as SyntaxHighlighterStyle,
  },
  dark: {
    id: 'dark',
    label: 'Feather Dark',
    family: 'Feather',
    mode: 'dark',
    swatches: ['#0d1117', '#8b949e', '#3fb950', '#bc8cff'],
    variables: featherDarkVariables,
    syntax: featherDarkSyntax as SyntaxHighlighterStyle,
  },
  ...noctisThemes,
};

export type ThemeSelectorOption = {
  value: ThemePreference;
  label: string;
  mode: ThemeMode | 'system';
  swatches: string[];
};

export type ThemeSelectorGroup = {
  label: string;
  options: ThemeSelectorOption[];
};

function optionForTheme(id: ThemeId): ThemeSelectorOption {
  const theme = appThemes[id];
  return {
    value: id,
    label: theme.label,
    mode: theme.mode,
    swatches: theme.swatches,
  };
}

export const themeSelectorGroups: ThemeSelectorGroup[] = [
  {
    label: 'Default',
    options: [
      {
        value: 'system',
        label: 'System',
        mode: 'system',
        swatches: ['#f0f4f8', '#0d1117', '#ad5b68', '#8b949e'],
      },
      optionForTheme('light'),
      optionForTheme('dark'),
    ],
  },
  {
    label: 'Noctis Light',
    options: [optionForTheme('noctis-lux'), optionForTheme('noctis-hibernus'), optionForTheme('noctis-lilac')],
  },
  {
    label: 'Noctis Dark',
    options: [
      optionForTheme('noctis'),
      optionForTheme('noctis-azureus'),
      optionForTheme('noctis-bordo'),
      optionForTheme('noctis-obscuro'),
      optionForTheme('noctis-sereno'),
      optionForTheme('noctis-uva'),
      optionForTheme('noctis-viola'),
      optionForTheme('noctis-minimus'),
    ],
  },
];

export const themePreferences = themeSelectorGroups.flatMap((group) =>
  group.options.map((option) => option.value),
) as ThemePreference[];

export function isThemePreference(value: unknown): value is ThemePreference {
  return typeof value === 'string' && themePreferences.includes(value as ThemePreference);
}

export function normalizeThemePreference(value: unknown): ThemePreference {
  return isThemePreference(value) ? value : 'system';
}

export function resolveThemeId(preference: ThemePreference, systemMode: ThemeMode): ThemeId {
  return preference === 'system' ? systemMode : preference;
}

export function resolveTheme(preference: ThemePreference, systemMode: ThemeMode): AppTheme {
  return appThemes[resolveThemeId(preference, systemMode)];
}
