import { existsSync } from "node:fs";
import { sha256Buffer } from "./checksum.js";
import type { Lockfile } from "./lockfile.js";
import { planPackageTarget, resolveProjectTarget } from "./target.js";
import type { ResolvedPackage, ResolvedDependencyAlias } from "./resolve.js";

export type DependencyAliasPlan = {
  name: string;
  target: string;
  requirePath: string;
  content: string;
  sha256: string;
  dependency: string;
};

export type DependencyAliasPlanResult =
  | { ok: true; aliases: DependencyAliasPlan[] }
  | { ok: false; error: string; aliases: DependencyAliasPlan[] };

export function luaModulePathFromTarget(target: string): string {
  const normalized = target.replace(/\\/g, "/").replace(/^\.\//, "");
  const withoutLua = normalized.endsWith(".lua") ? normalized.slice(0, -4) : normalized;
  const withoutInit = withoutLua.endsWith("/init") ? withoutLua.slice(0, -5) : withoutLua;
  return withoutInit.split("/").filter(Boolean).join(".");
}

export function packageDependencyAliasContent(requirePath: string): string {
  return `-- Generated by Feather package manager. Do not edit.\nreturn require("${requirePath}")\n`;
}

function requireSuffix(requirePath: string): string {
  const parts = requirePath.split(".").filter(Boolean);
  return parts.length > 1 ? parts.slice(1).join(".") : requirePath;
}

function findEffectiveDependencyRequire(alias: ResolvedDependencyAlias, lockfile: Lockfile): string | null {
  if (alias.require) return alias.require;
  const dependencyLock = lockfile.packages[alias.dependency];
  if (!dependencyLock) return null;

  const defaultRequire = alias.dependencyEntry.require;
  const exact = dependencyLock.files.find((file) => luaModulePathFromTarget(file.target) === defaultRequire);
  if (exact) return luaModulePathFromTarget(exact.target);

  const suffix = requireSuffix(defaultRequire);
  const suffixMatch = dependencyLock.files.find((file) => {
    const modulePath = luaModulePathFromTarget(file.target);
    return modulePath === suffix || modulePath.endsWith(`.${suffix}`);
  });
  return suffixMatch ? luaModulePathFromTarget(suffixMatch.target) : defaultRequire;
}

function lockfileOwnerForTarget(lockfile: Lockfile, target: string): string | null {
  for (const [id, entry] of Object.entries(lockfile.packages)) {
    if (entry.files.some((file) => file.target === target)) return id;
  }
  return null;
}

export function planDependencyAliases(
  pkg: ResolvedPackage,
  lockfile: Lockfile,
  opts: { installDir?: string; targetOverride?: string; dryRun?: boolean },
): DependencyAliasPlanResult {
  const aliases: DependencyAliasPlan[] = [];
  if (!pkg.dependencyAliases?.length) return { ok: true, aliases };
  if (opts.targetOverride) {
    return { ok: false, aliases, error: `${pkg.id} dependency aliases cannot be flattened.` };
  }

  const savedInstallDir = lockfile.packages[pkg.id]?.installDir;
  const layout = pkg.entry.install?.layout;
  const fixedLayout = layout === "fixed";
  const effectiveInstallDir = fixedLayout ? undefined : (opts.installDir ?? savedInstallDir);

  for (const alias of pkg.dependencyAliases) {
    const requirePath = findEffectiveDependencyRequire(alias, lockfile) ?? (opts.dryRun ? alias.require ?? alias.dependencyEntry.require : null);
    if (!requirePath) {
      return { ok: false, aliases, error: `${pkg.id} dependency alias requires missing dependency "${alias.dependency}".` };
    }
    const target = planPackageTarget(
      { name: alias.target, target: alias.target },
      { installDir: effectiveInstallDir, layout },
    );
    const content = packageDependencyAliasContent(requirePath);
    aliases.push({
      name: alias.target,
      target,
      requirePath,
      content,
      sha256: sha256Buffer(Buffer.from(content, "utf8")),
      dependency: alias.dependency,
    });
  }

  return { ok: true, aliases };
}

export function checkDependencyAliasTarget(
  projectDir: string,
  lockfile: Lockfile,
  packageId: string,
  alias: DependencyAliasPlan,
): string | null {
  const owner = lockfileOwnerForTarget(lockfile, alias.target);
  if (owner && owner !== packageId) {
    return `${alias.target} is already managed by package "${owner}".`;
  }
  if (owner === packageId) return null;

  const absTarget = resolveProjectTarget(projectDir, alias.target);
  if (!absTarget) return `${alias.target} escapes the project root.`;
  if (existsSync(absTarget)) {
    return `${alias.target} already exists and is not managed by Feather.`;
  }
  return null;
}
