-- Generated by Feather Particles Playground
-- 2026-05-29 23:30:59
local LG = love.graphics

---@class ParticlePayload
---@field x? number
---@field y? number
---@field r? number
---@field loop? boolean
---@field systemIndex? integer

local activeInstances = {}
local pooledInstances = {}
local systems = {}
local particles = { x = 400, y = 300, systems = systems, instances = activeInstances }
local function compileShader(name, source)
  local ok, shader = pcall(LG.newShader, source)
  if ok then
    return shader
  end
  print("[Particles] Could not compile shader " .. tostring(name) .. ": " .. tostring(shader))
  return nil
end

local timeline = {
  duration = 3,
  loop = true,
  tracks = {
    {
      systemIndex = 1,
      clips = {
        { start = 0.7, ["end"] = 1.3, emit = 0 },
      },
      lanes = {},
    },
    {
      systemIndex = 2,
      clips = {
        { start = 1.7, ["end"] = 1.8, emit = 0 },
      },
      lanes = {
        opacity = {
          { time = 1.7, value = 1, easing = "linear" },
          { time = 1.9, value = 0, easing = "linear" },
        },
        sizeScale = {
          { time = 1.7, value = 1, easing = "outExpo" },
          { time = 1.9, value = 2, easing = "linear" },
        },
      },
    },
    {
      systemIndex = 3,
      clips = {
        { start = 0.3, ["end"] = 1.7, emit = 0 },
      },
      lanes = {
        speedScale = {
          { time = 1.2, value = 0, easing = "inOutExpo" },
          { time = 1.8, value = 1, easing = "linear" },
        },
        sizeScale = {
          { time = 0.9, value = 1, easing = "inOutBounce" },
          { time = 1, value = 1.1, easing = "inOutBounce" },
          { time = 1.1, value = 1, easing = "inElastic" },
          { time = 1.8, value = 3, easing = "linear" },
        },
      },
    },
  },
}
local timelineState = { time = 0, playing = false, loop = nil, directionOffset = 0 }
local MAX_POOLED_INSTANCES = 8
local release

local image1 = LG.newImage("particles/circle.png")
image1:setFilter("linear", "linear")
local image2 = LG.newImage("particles/ring.png")
image2:setFilter("linear", "linear")
local shader1Raw = [[
vec4 feather_template_chromatic_aberration_preset_subgraph_1780104014462_pixel(Image tex, vec2 texture_coords, vec2 screen_coords, vec4 color, vec2 sg_in_uv) {
  float v_preset_node_1780104014456_out = 0.006;
  vec2 v_preset_node_1780104014457_out = vec2(0.0, 0.0);
  vec2 v_preset_node_1780104014458_out_center = vec2(0.5) + v_preset_node_1780104014457_out;
  vec2 v_preset_node_1780104014458_out_delta = sg_in_uv - v_preset_node_1780104014458_out_center;
  vec2 v_preset_node_1780104014458_out_dir = length(v_preset_node_1780104014458_out_delta) > 0.0001 ? normalize(v_preset_node_1780104014458_out_delta) : vec2(0.0);
  vec2 v_preset_node_1780104014458_out_off = v_preset_node_1780104014458_out_dir * v_preset_node_1780104014456_out;
  vec4 v_preset_node_1780104014458_out_base = Texel(tex, sg_in_uv);
  vec4 v_preset_node_1780104014458_out = vec4(Texel(tex, sg_in_uv + v_preset_node_1780104014458_out_off).r, v_preset_node_1780104014458_out_base.g, Texel(tex, sg_in_uv - v_preset_node_1780104014458_out_off).b, v_preset_node_1780104014458_out_base.a);
  vec4 v_template_output_rgba_1780104014461_out = v_preset_node_1780104014458_out;
  return v_template_output_rgba_1780104014461_out;
}

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec2 v_template_root_uv_1780104014464_out = texture_coords;
  vec4 v_preset_instance_1780104014463_rgba = feather_template_chromatic_aberration_preset_subgraph_1780104014462_pixel(tex, texture_coords, screen_coords, color, v_template_root_uv_1780104014464_out);
  return v_preset_instance_1780104014463_rgba * color;
}
]]
local shader1 = compileShader("chromatic-aberration.glsl", shader1Raw)
local shader2Raw = [[
vec4 feather_template_pixelate_preset_subgraph_1780104944728_pixel(Image tex, vec2 texture_coords, vec2 screen_coords, vec4 color, vec2 sg_in_uv) {
  float v_preset_node_1780104944722_out = 25.0;
  vec2 v_preset_node_1780104944723_out_cells = max(vec2(1.0), love_ScreenSize.xy / max(v_preset_node_1780104944722_out, 1.0));
  vec2 v_preset_node_1780104944723_out = floor(sg_in_uv * v_preset_node_1780104944723_out_cells) / v_preset_node_1780104944723_out_cells;
  vec4 v_preset_node_1780104944724_out = Texel(tex, v_preset_node_1780104944723_out);
  vec4 v_template_output_rgba_1780104944727_out = v_preset_node_1780104944724_out;
  return v_template_output_rgba_1780104944727_out;
}

vec4 effect(vec4 color, Image tex, vec2 texture_coords, vec2 screen_coords) {
  vec2 v_template_root_uv_1780104944730_out = texture_coords;
  vec4 v_preset_instance_1780104944729_rgba = feather_template_pixelate_preset_subgraph_1780104944728_pixel(tex, texture_coords, screen_coords, color, v_template_root_uv_1780104944730_out);
  return v_preset_instance_1780104944729_rgba * color;
}
]]
local shader2 = compileShader("pixelate.glsl", shader2Raw)

local function clearSystemsAlias()
  for key in pairs(systems) do
    systems[key] = nil
  end
end

local function publishSystems(instance)
  clearSystemsAlias()
  if not instance then
    return
  end
  for index, emitter in ipairs(instance.systems or {}) do
    systems[index] = emitter
  end
end

local function releaseInstance(instance)
  if not instance then
    return
  end
  for index, emitter in ipairs(instance.systems or {}) do
    if emitter.system then
      emitter.system:release()
    end
    instance.systems[index] = nil
  end
end

local function createInstance()
  local instanceSystems = {}
  local instance = {
    systems = instanceSystems,
    time = 0,
    playing = false,
    loop = nil,
    directionOffset = 0,
    active = false,
    systemIndex = nil,
  }
  local ps1 = LG.newParticleSystem(image1, 1000)
  ps1:setColors(
    0.361,
    0.027,
    0,
    1,
    1,
    0.1,
    0,
    0,
    1,
    0.5,
    0.1,
    1,
    0.361,
    0.027,
    0,
    0.313,
    1,
    0.5,
    0.1,
    1,
    1,
    0.5,
    0.1,
    1,
    1,
    0.5,
    0.1,
    1,
    1,
    0.5,
    0.1,
    1
  )
  ps1:setDirection(4.712)
  ps1:setEmissionArea("none", 0, 0, 0, false)
  ps1:setEmissionRate(100)
  ps1:setEmitterLifetime(-1)
  ps1:setInsertMode("top")
  ps1:setLinearAcceleration(0, 319, 0, 754)
  ps1:setLinearDamping(0.03, 0.03)
  ps1:setOffset(32, 32)
  ps1:setParticleLifetime(0.35, 1.3)
  ps1:setRadialAcceleration(29, 145)
  ps1:setRelativeRotation(false)
  ps1:setRotation(0, 0)
  ps1:setSizes(1, 0.268, 0, 0)
  ps1:setSizeVariation(0)
  ps1:setSpeed(234, 806)
  ps1:setSpin(0, 0)
  ps1:setSpinVariation(0)
  ps1:setSpread(1.658)
  ps1:setTangentialAcceleration(0, 0)
  ps1:setPosition(particles.x + 0, particles.y + 0)
  instanceSystems[1] = {
    system = ps1,
    enabled = true,
    kickStartSteps = 0,
    kickStartDt = 0.016667,
    emitAtStart = 0,
    blendMode = "alpha",
    shader = nil,
    texturePreset = "circle",
    texturePath = "",
    shaderPath = "",
    shaderFilename = "",
    x = 0,
    y = 0,
    opacity = 1,
    base = {
      emissionRate = 100,
      emitterLifetime = -1,
      speedMin = 234,
      speedMax = 806,
      sizes = { 1, 0.268, 0, 0 },
      direction = 4.712,
      spread = 1.658,
      offsetX = 32,
      offsetY = 32,
    },
  }
  local ps2 = LG.newParticleSystem(image2, 1000)
  ps2:setColors(1, 1, 1, 0.1)
  ps2:setDirection(-1.570796)
  ps2:setEmissionArea("none", 0, 0, 0, false)
  ps2:setEmissionRate(0)
  ps2:setEmitterLifetime(-1)
  ps2:setInsertMode("top")
  ps2:setLinearAcceleration(0, 0, 0, 0)
  ps2:setLinearDamping(0, 0)
  ps2:setOffset(32, 32)
  ps2:setParticleLifetime(0.35, 1)
  ps2:setRadialAcceleration(0, 0)
  ps2:setRelativeRotation(false)
  ps2:setRotation(0, 0)
  ps2:setSizes(0, 10, 10, 10, 10, 10, 10, 10)
  ps2:setSizeVariation(0)
  ps2:setSpeed(0, 0)
  ps2:setSpin(0, 0)
  ps2:setSpinVariation(0)
  ps2:setSpread(1.047198)
  ps2:setTangentialAcceleration(0, 0)
  ps2:setPosition(particles.x + 0, particles.y + 0)
  instanceSystems[2] = {
    system = ps2,
    enabled = true,
    kickStartSteps = 0,
    kickStartDt = 0.016667,
    emitAtStart = 0,
    blendMode = "alpha",
    shader = shader1,
    texturePreset = "ring",
    texturePath = "",
    shaderPath = "",
    shaderFilename = "chromatic-aberration.glsl",
    x = 0,
    y = 0,
    opacity = 1,
    base = {
      emissionRate = 0,
      emitterLifetime = -1,
      speedMin = 0,
      speedMax = 0,
      sizes = { 0, 10, 10, 10, 10, 10, 10, 10 },
      direction = -1.570796,
      spread = 1.047198,
      offsetX = 32,
      offsetY = 32,
    },
  }
  local ps3 = LG.newParticleSystem(image1, 1000)
  ps3:setColors(0.149, 0.243, 0.059, 1, 0.361, 0.027, 0, 0, 0.376, 0.376, 0.376, 0)
  ps3:setDirection(4.712)
  ps3:setEmissionArea("none", 0, 0, 0, false)
  ps3:setEmissionRate(100)
  ps3:setEmitterLifetime(-1)
  ps3:setInsertMode("top")
  ps3:setLinearAcceleration(0, 0, 0, 0)
  ps3:setLinearDamping(0.18, 0.22)
  ps3:setOffset(32, 32)
  ps3:setParticleLifetime(0.35, 1.3)
  ps3:setRadialAcceleration(145, 435)
  ps3:setRelativeRotation(false)
  ps3:setRotation(0, 0)
  ps3:setSizes(0.995377, 0.995377, 0.995377)
  ps3:setSizeVariation(0)
  ps3:setSpeed(0.342547, 1.198913)
  ps3:setSpin(0, 0)
  ps3:setSpinVariation(0)
  ps3:setSpread(6.283)
  ps3:setTangentialAcceleration(0, 43.5)
  ps3:setPosition(particles.x + 0, particles.y + 0)
  instanceSystems[3] = {
    system = ps3,
    enabled = true,
    kickStartSteps = 0,
    kickStartDt = 0.016667,
    emitAtStart = 0,
    blendMode = "alpha",
    shader = shader2,
    texturePreset = "circle",
    texturePath = "",
    shaderPath = "",
    shaderFilename = "pixelate.glsl",
    x = 0,
    y = 0,
    opacity = 1,
    base = {
      emissionRate = 100,
      emitterLifetime = -1,
      speedMin = 0.342547,
      speedMax = 1.198913,
      sizes = { 0.995377, 0.995377, 0.995377 },
      direction = 4.712,
      spread = 6.283,
      offsetX = 32,
      offsetY = 32,
    },
  }

  return instance
end

local function init()
  release()
  clearSystemsAlias()
  local instance = createInstance()
  pooledInstances[#pooledInstances + 1] = instance
  publishSystems(instance)
  return particles
end

local TimelineRuntime = (function()
  local Runtime = {}

  local VALID_EASINGS = {
    linear = true,
    hold = true,
    inSine = true,
    outSine = true,
    inOutSine = true,
    inQuad = true,
    outQuad = true,
    inOutQuad = true,
    inCubic = true,
    outCubic = true,
    inOutCubic = true,
    inQuart = true,
    outQuart = true,
    inOutQuart = true,
    inExpo = true,
    outExpo = true,
    inOutExpo = true,
    inBack = true,
    outBack = true,
    inOutBack = true,
    inElastic = true,
    outElastic = true,
    inOutElastic = true,
    inBounce = true,
    outBounce = true,
    inOutBounce = true,
  }

  function Runtime.safeNumber(value, fallback)
    local n = tonumber(value)
    if n ~= nil and n == n and n ~= math.huge and n ~= -math.huge then
      return n
    end
    return fallback
  end

  local function clamp(value, minValue, maxValue)
    if value < minValue then
      return minValue
    end
    if value > maxValue then
      return maxValue
    end
    return value
  end

  function Runtime.parseNumberList(value)
    if type(value) == "table" then
      local out = {}
      for _, item in ipairs(value) do
        out[#out + 1] = Runtime.safeNumber(item, 0)
      end
      return out
    end

    local out = {}
    for part in tostring(value or ""):gmatch("[^,%s]+") do
      local n = tonumber(part)
      if n ~= nil then
        out[#out + 1] = n
      end
    end
    return out
  end

  function Runtime.normalizeTimelineEasing(easing)
    easing = tostring(easing or "linear")
    return VALID_EASINGS[easing] and easing or "linear"
  end

  local function easeOutBounce(t)
    local n1 = 7.5625
    local d1 = 2.75
    if t < 1 / d1 then
      return n1 * t * t
    elseif t < 2 / d1 then
      t = t - 1.5 / d1
      return n1 * t * t + 0.75
    elseif t < 2.5 / d1 then
      t = t - 2.25 / d1
      return n1 * t * t + 0.9375
    end
    t = t - 2.625 / d1
    return n1 * t * t + 0.984375
  end

  function Runtime.easeTimelineValue(easing, t)
    easing = Runtime.normalizeTimelineEasing(easing)
    t = clamp(Runtime.safeNumber(t, 0), 0, 1)
    local c1 = 1.70158
    local c2 = c1 * 1.525
    local c3 = c1 + 1
    local c4 = (2 * math.pi) / 3
    local c5 = (2 * math.pi) / 4.5
    if easing == "hold" then
      return 0
    end
    if easing == "inSine" then
      return 1 - math.cos((t * math.pi) / 2)
    end
    if easing == "outSine" then
      return math.sin((t * math.pi) / 2)
    end
    if easing == "inOutSine" then
      return -(math.cos(math.pi * t) - 1) / 2
    end
    if easing == "inQuad" then
      return t * t
    end
    if easing == "outQuad" then
      return 1 - (1 - t) * (1 - t)
    end
    if easing == "inOutQuad" then
      return t < 0.5 and 2 * t * t or 1 - ((-2 * t + 2) ^ 2) / 2
    end
    if easing == "inCubic" then
      return t * t * t
    end
    if easing == "outCubic" then
      return 1 - ((1 - t) ^ 3)
    end
    if easing == "inOutCubic" then
      return t < 0.5 and 4 * t * t * t or 1 - ((-2 * t + 2) ^ 3) / 2
    end
    if easing == "inQuart" then
      return t * t * t * t
    end
    if easing == "outQuart" then
      return 1 - ((1 - t) ^ 4)
    end
    if easing == "inOutQuart" then
      return t < 0.5 and 8 * t * t * t * t or 1 - ((-2 * t + 2) ^ 4) / 2
    end
    if easing == "inExpo" then
      return t == 0 and 0 or 2 ^ (10 * t - 10)
    end
    if easing == "outExpo" then
      return t == 1 and 1 or 1 - 2 ^ (-10 * t)
    end
    if easing == "inOutExpo" then
      if t == 0 or t == 1 then
        return t
      end
      return t < 0.5 and (2 ^ (20 * t - 10)) / 2 or (2 - 2 ^ (-20 * t + 10)) / 2
    end
    if easing == "inBack" then
      return c3 * t * t * t - c1 * t * t
    end
    if easing == "outBack" then
      return 1 + c3 * ((t - 1) ^ 3) + c1 * ((t - 1) ^ 2)
    end
    if easing == "inOutBack" then
      return t < 0.5 and (((2 * t) ^ 2) * ((c2 + 1) * 2 * t - c2)) / 2
        or (((2 * t - 2) ^ 2) * ((c2 + 1) * (2 * t - 2) + c2) + 2) / 2
    end
    if easing == "inElastic" then
      if t == 0 or t == 1 then
        return t
      end
      return -(2 ^ (10 * t - 10)) * math.sin((t * 10 - 10.75) * c4)
    end
    if easing == "outElastic" then
      if t == 0 or t == 1 then
        return t
      end
      return (2 ^ (-10 * t)) * math.sin((t * 10 - 0.75) * c4) + 1
    end
    if easing == "inOutElastic" then
      if t == 0 or t == 1 then
        return t
      end
      return t < 0.5 and -((2 ^ (20 * t - 10)) * math.sin((20 * t - 11.125) * c5)) / 2
        or ((2 ^ (-20 * t + 10)) * math.sin((20 * t - 11.125) * c5)) / 2 + 1
    end
    if easing == "inBounce" then
      return 1 - easeOutBounce(1 - t)
    end
    if easing == "outBounce" then
      return easeOutBounce(t)
    end
    if easing == "inOutBounce" then
      return t < 0.5 and (1 - easeOutBounce(1 - 2 * t)) / 2 or (1 + easeOutBounce(2 * t - 1)) / 2
    end
    return t
  end

  function Runtime.evaluateKeyframes(points, time, fallback)
    if type(points) ~= "table" or #points == 0 then
      return fallback
    end
    if time <= Runtime.safeNumber(points[1].time, 0) then
      return Runtime.safeNumber(points[1].value, fallback)
    end
    for i = 1, #points - 1 do
      local a = points[i]
      local b = points[i + 1]
      local at = Runtime.safeNumber(a.time, 0)
      local bt = Runtime.safeNumber(b.time, at)
      if time >= at and time <= bt then
        local span = math.max(0.0001, bt - at)
        local t = clamp((time - at) / span, 0, 1)
        local eased = Runtime.easeTimelineValue(a.easing, t)
        local av = Runtime.safeNumber(a.value, fallback)
        local bv = Runtime.safeNumber(b.value, fallback)
        return av + (bv - av) * eased
      end
    end
    return Runtime.safeNumber(points[#points].value, fallback)
  end

  function Runtime.clipAllowsEmission(clip, time, emitterLifetime)
    local startTime = Runtime.safeNumber(clip and clip.start, 0)
    local endTime = Runtime.safeNumber(clip and clip["end"], 0)
    if time < startTime or time > endTime then
      return false
    end
    local lifetime = Runtime.safeNumber(emitterLifetime, -1)
    if lifetime < 0 then
      return true
    end
    return time <= startTime + lifetime
  end

  function Runtime.trackAllowsEmission(track, time, emitterLifetime)
    for _, clip in ipairs(track and track.clips or {}) do
      if Runtime.clipAllowsEmission(clip, time, emitterLifetime) then
        return true
      end
    end
    return false
  end

  local function callParticle(ps, method, ...)
    local fn = ps and ps[method]
    if type(fn) ~= "function" then
      return false
    end
    return pcall(fn, ps, ...)
  end

  local function resolveOption(option, emitter)
    if type(option) == "function" then
      return option(emitter)
    end
    return option
  end

  function Runtime.applyTimelineToEmitter(emitter, track, time, allowEmission, options)
    options = options or {}
    if type(emitter) ~= "table" then
      return nil
    end
    local ps = resolveOption(options.system, emitter) or emitter.system or emitter.ps
    if not ps then
      return nil
    end
    local base = resolveOption(options.base, emitter)
    if type(base) ~= "table" then
      base = emitter.base or emitter._timelineBase or {}
    end
    local lanes = track and track.lanes or {}
    local active = Runtime.trackAllowsEmission(track, time, Runtime.safeNumber(base.emitterLifetime, -1))

    local emissionRate =
      math.max(0, Runtime.evaluateKeyframes(lanes.emissionRate, time, Runtime.safeNumber(base.emissionRate, 0)))
    if not active or allowEmission ~= true then
      emissionRate = 0
    end
    callParticle(ps, "setEmissionRate", emissionRate)

    local speedScale = math.max(0, Runtime.evaluateKeyframes(lanes.speedScale, time, 1))
    callParticle(
      ps,
      "setSpeed",
      Runtime.safeNumber(base.speedMin, 0) * speedScale,
      Runtime.safeNumber(base.speedMax, 0) * speedScale
    )

    local sizeScale = math.max(0, Runtime.evaluateKeyframes(lanes.sizeScale, time, 1))
    local sizes = Runtime.parseNumberList(base.sizes)
    if #sizes > 0 then
      for i, value in ipairs(sizes) do
        sizes[i] = math.max(0, value * sizeScale)
      end
      callParticle(ps, "setSizes", unpack(sizes))
    end

    local directionOffset = Runtime.safeNumber(resolveOption(options.directionOffset, emitter), 0)
    callParticle(
      ps,
      "setDirection",
      Runtime.evaluateKeyframes(lanes.direction, time, Runtime.safeNumber(base.direction, 0)) + directionOffset
    )
    callParticle(ps, "setSpread", Runtime.evaluateKeyframes(lanes.spread, time, Runtime.safeNumber(base.spread, 0)))
    callParticle(
      ps,
      "setOffset",
      Runtime.evaluateKeyframes(lanes.offsetX, time, Runtime.safeNumber(base.offsetX, 0)),
      Runtime.evaluateKeyframes(lanes.offsetY, time, Runtime.safeNumber(base.offsetY, 0))
    )

    local opacity = clamp(Runtime.evaluateKeyframes(lanes.opacity, time, 1), 0, 1)
    emitter[options.opacityField or "opacity"] = opacity

    return {
      active = active,
      emissionRate = emissionRate,
      speedScale = speedScale,
      sizeScale = sizeScale,
      opacity = opacity,
    }
  end

  return Runtime
end)()

local function applyTimeline(instance, time, allowEmission)
  if not instance then
    return
  end
  for index, track in ipairs(timeline.tracks or {}) do
    local emitter = instance.systems[index]
    if
      emitter
      and emitter.enabled
      and emitter.system
      and (not instance.systemIndex or instance.systemIndex == index)
    then
      TimelineRuntime.applyTimelineToEmitter(emitter, track, time, allowEmission == true, {
        base = emitter.base or {},
        directionOffset = instance.directionOffset or 0,
        opacityField = "opacity",
      })
    end
  end
end

local function clipBurstCount(clip, emitter)
  local base = tonumber(clip.emit)
  if base == nil then
    base = tonumber(emitter.emitAtStart)
  end
  return math.max(0, math.floor(base or 0))
end

local function emitTimelineStarts(instance, previousTime, nextTime)
  if not instance then
    return
  end
  for index, track in ipairs(timeline.tracks or {}) do
    local emitter = instance.systems[index]
    if
      emitter
      and emitter.enabled
      and emitter.system
      and (not instance.systemIndex or instance.systemIndex == index)
    then
      for _, clip in ipairs(track.clips or {}) do
        local start = tonumber(clip.start) or 0
        if previousTime <= start and nextTime >= start then
          local count = clipBurstCount(clip, emitter)
          emitter.system:setEmitterLifetime((emitter.base and emitter.base.emitterLifetime) or -1)
          emitter.system:start()
          if count > 0 then
            emitter.system:emit(count)
          end
        end
      end
    end
  end
end

local function emitTimelineStartsForAdvance(instance, previousTime, elapsed)
  if elapsed <= 0 then
    return previousTime
  end
  local cursor = previousTime
  local remaining = elapsed
  local guard = 0
  while remaining > 0 and guard < 128 do
    if cursor >= timeline.duration then
      cursor = 0
    end
    local room = math.max(0, timeline.duration - cursor)
    if room <= 0 then
      cursor = 0
      room = timeline.duration
    end
    local segment = math.min(remaining, room)
    local nextCursor = cursor + segment
    if segment > 0 then
      emitTimelineStarts(instance, cursor, nextCursor)
    end
    remaining = remaining - segment
    cursor = nextCursor
    if remaining > 0 and cursor >= timeline.duration then
      cursor = 0
    end
    guard = guard + 1
  end
  return cursor >= timeline.duration and 0 or cursor
end

local function timelineShouldLoop(instance)
  if instance and instance.loop ~= nil then
    return instance.loop == true
  end
  if timelineState.loop ~= nil then
    return timelineState.loop == true
  end
  return timeline.loop == true
end

local function setLoop(loop)
  if type(loop) == "boolean" then
    timelineState.loop = loop
  else
    timelineState.loop = nil
  end
  for _, instance in ipairs(activeInstances) do
    instance.loop = timelineState.loop
  end
  return timelineShouldLoop(nil)
end

local function resetInstance(instance, payload)
  payload = type(payload) == "table" and payload or {}
  local x = tonumber(payload.x) or particles.x
  local y = tonumber(payload.y) or particles.y
  instance.time = 0
  instance.playing = true
  instance.active = true
  if type(payload.loop) == "boolean" then
    instance.loop = payload.loop
  else
    instance.loop = timelineState.loop
  end
  instance.directionOffset = tonumber(payload.r) or 0
  instance.systemIndex = tonumber(payload.systemIndex)
  for index, emitter in ipairs(instance.systems or {}) do
    local participates = not instance.systemIndex or instance.systemIndex == index
    if emitter.enabled and emitter.system then
      emitter.system:reset()
      emitter.system:setEmitterLifetime((emitter.base and emitter.base.emitterLifetime) or -1)
      emitter.system:setPosition(x + (emitter.x or 0), y + (emitter.y or 0))
      emitter.opacity = participates and 1 or 0
      if participates then
        emitter.system:start()
      else
        emitter.system:setEmissionRate(0)
        emitter.system:stop()
      end
    end
  end
  applyTimeline(instance, 0, true)
  emitTimelineStarts(instance, 0, 0)
  return instance
end

local function recycleInstance(instance)
  if not instance then
    return
  end
  instance.active = false
  instance.playing = false
  instance.time = 0
  instance.loop = nil
  instance.directionOffset = 0
  instance.systemIndex = nil
  for _, emitter in ipairs(instance.systems or {}) do
    if emitter.system then
      emitter.system:reset()
      emitter.system:setEmissionRate(0)
      emitter.system:setEmitterLifetime((emitter.base and emitter.base.emitterLifetime) or -1)
    end
    emitter.opacity = 1
  end
  if #pooledInstances < MAX_POOLED_INSTANCES then
    pooledInstances[#pooledInstances + 1] = instance
  else
    releaseInstance(instance)
  end
end

local function checkoutInstance(payload)
  local instance = table.remove(pooledInstances)
  if not instance then
    instance = createInstance()
  end
  activeInstances[#activeInstances + 1] = instance
  resetInstance(instance, payload)
  publishSystems(instance)
  return instance
end

local function instanceHasParticles(instance)
  for _, emitter in ipairs(instance.systems or {}) do
    if emitter.enabled and emitter.system then
      local ok, count = pcall(emitter.system.getCount, emitter.system)
      if ok and (tonumber(count) or 0) > 0 then
        return true
      end
    end
  end
  return false
end

local function update(dt)
  for i = #activeInstances, 1, -1 do
    local instance = activeInstances[i]
    if instance.playing then
      local previous = instance.time
      local nextTime = previous + dt
      if nextTime > timeline.duration then
        if timelineShouldLoop(instance) then
          nextTime = emitTimelineStartsForAdvance(instance, previous, dt)
        else
          emitTimelineStarts(instance, previous, timeline.duration)
          nextTime = timeline.duration
          instance.playing = false
        end
      else
        emitTimelineStarts(instance, previous, nextTime)
      end
      instance.time = nextTime
    end
    applyTimeline(instance, instance.time, instance.playing)
    for index, emitter in ipairs(instance.systems or {}) do
      if emitter.enabled and emitter.system and (not instance.systemIndex or instance.systemIndex == index) then
        emitter.system:update(dt)
      end
    end
    if not instance.playing and not instanceHasParticles(instance) then
      table.remove(activeInstances, i)
      recycleInstance(instance)
    end
  end
  local latest = activeInstances[#activeInstances]
  timelineState.time = latest and latest.time or 0
  timelineState.playing = latest and latest.playing or false
  timelineState.directionOffset = latest and latest.directionOffset or 0
end

local function draw()
  local previousBlend, previousAlphaMode = LG.getBlendMode()
  local previousShader = LG.getShader()
  local r, g, b, a = LG.getColor()

  for _, instance in ipairs(activeInstances) do
    for index, emitter in ipairs(instance.systems or {}) do
      if emitter.enabled and emitter.system and (not instance.systemIndex or instance.systemIndex == index) then
        LG.setBlendMode(emitter.blendMode or "alpha")
        if emitter.shader and emitter.shader.send and love.timer then
          pcall(emitter.shader.send, emitter.shader, "u_time", love.timer.getTime())
        end
        LG.setShader(emitter.shader)
        LG.setColor(1, 1, 1, emitter.opacity or 1)
        LG.draw(emitter.system, 0, 0)
      end
    end
  end

  LG.setBlendMode(previousBlend, previousAlphaMode)
  LG.setShader(previousShader)
  LG.setColor(r, g, b, a)
end

---Play the authored particle timeline.
---@param payload ParticlePayload
local function play(payload)
  if type(payload) ~= "table" then
    payload = {}
  end
  return checkoutInstance(payload)
end

local function pause()
  timelineState.playing = false
  for _, instance in ipairs(activeInstances) do
    instance.playing = false
    applyTimeline(instance, instance.time, false)
  end
  return true
end

local function stop(resetParticles)
  timelineState.time = 0
  timelineState.playing = false
  timelineState.loop = nil
  timelineState.directionOffset = 0
  for i = #activeInstances, 1, -1 do
    local instance = activeInstances[i]
    instance.playing = false
    instance.loop = nil
    instance.directionOffset = 0
    applyTimeline(instance, instance.time or 0, false)
    if resetParticles ~= false then
      table.remove(activeInstances, i)
      recycleInstance(instance)
    end
  end
  if resetParticles ~= false then
    publishSystems(nil)
  end
  return true
end

local function emit(payload)
  return play(payload)
end

release = function()
  for i = #activeInstances, 1, -1 do
    releaseInstance(activeInstances[i])
    activeInstances[i] = nil
  end
  for i = #pooledInstances, 1, -1 do
    releaseInstance(pooledInstances[i])
    pooledInstances[i] = nil
  end
  clearSystemsAlias()
  return true
end

return {
  init = init,
  draw = draw,
  update = update,
  play = play,
  pause = pause,
  stop = stop,
  setLoop = setLoop,
  isLooping = timelineShouldLoop,
  emit = emit,
  release = release,
}
