name: Feather release
on:
  push:
    tags: # Will upload to luarocks.org when a tag is pushed
      - '*'
  pull_request: # Will test a local install without uploading to luarocks.org

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fail if changelog entry does not exist
        run: grep -q "${{ github.ref_name }}" CHANGELOG.md
      - name: Get version from tag
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"  # remove the 'v' prefix
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        with:
          license: Feather License
          labels: |
            love2d
            löve
            debug
          copy_directories: |
            src-lua/feather
          summary: Debug & Inspect Tool for LÖVE (love2d)
          detailed_description: |
            Feather is a debugger tool with a plugin system for Love2D projects.
          fail_on_duplicate: true
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: feather-${{ steps.get_version.outputs.version }}-1.rockspec, feather-${{ steps.get_version.outputs.version }}-1.src.rock
          bodyFile: 'CHANGELOG.md'
          allowUpdates: true
      # - name: Upload binaries to release
      #   uses: softprops/action-gh-release@v1
      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     files: |
      #       feather-${{ steps.get_version.outputs.version }}-1.rockspec
      #       feather-${{ steps.get_version.outputs.version }}-1.src.rock

  tauri-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ env.TAG_NAME }}
        with:
          tagName: ${{ github.ref_name }}
          args: ${{ matrix.args }}
